### ISSUE TITLE
few questions

### ISSUE THREAD

**Issue by bsr203** [szwacz/electron-boilerplate#1]
Hi Jakub,

Thanks for this project, as I have been struggling with somewhat official [electron-starter](https://github.com/atom/electron-starter).  This boilerplate worked so great and set up was a breeze. I have couple of questions.

1. How do you compare with `electron-starter`. I think they build the `electron` itself to customize the menu icons,... Any tradeoff I need to be aware of.
2. Is there a way not to distribute the application in source format. `electron` [doc mentions](https://github.com/atom/electron/blob/master/docs/tutorial/application-distribution.md#packaging-your-app-into-a-file) they have `asar` for that. Can you incorporate that in your release pipeline? or atleast minify the source files.
4. What is the best way to get rid of all the chrome menus. In the release version, I see a file `default_app.js` with these menus configured but not sure a way to specify in my app.

Thanks again for your effort. I was a lifesaver :-)

Cheers.
bsr

**Comment by szwacz** [comment]
1. I was struggling with electron-starter as well :) Actually failed to install it and abandon further attepts. Wasn't also able to easily understand what that project does and how is constructed. Electron-boilerplate is actually a port of my other project nw-boilerplate which has been in development for some longer time.
2. Asar is not that difficult to configure, so I thought I'll leave it out for simlicity. But if more people ask for it this will find it's way into this project. Also pull requests are very welcome :)
3. Menus is something I've been neglecting so far. Isn't answer to your question in https://github.com/atom/electron/blob/master/docs/api/menu.md ?

**Comment by bsr203** [comment]
thanks Jakub. I will start using this project and will back with more feedback/qns.
