### ISSUE TITLE
Error during rollup Error: Could not load null: path must be a string

### ISSUE THREAD

**Issue by Fristing** [szwacz/electron-boilerplate#102]
Hi,
I have a problem when i want to make a relase of my application. This is the output : "
C:\Users\Quentin Laffont\Desktop\boiler\electron-boilerplate>npm run release

> @ release C:\Users\Quentin Laffont\Desktop\boiler\electron-boilerplate
> gulp release --env=production

[12:04:47] Using gulpfile ~\Desktop\boiler\electron-boilerplate\gulpfile.js
[12:04:47] Starting 'clean'...
[12:04:47] Finished 'clean' after 59 ms
[12:04:47] Starting 'bundle'...
[12:04:47] Starting 'less'...
[12:04:47] Starting 'copy'...
[12:04:47] Starting 'finalize'...
[12:04:47] Finished 'finalize' after 1.7 ms
Treating 'electron' as external dependency
Build: Error during rollup Error: Could not load null: path must be a string
    at C:\Users\Quentin Laffont\Desktop\boiler\electron-boilerplate\node_modules
\rollup\dist\rollup.js:7608:10
    at tryCatch (C:\Users\Quentin Laffont\Desktop\boiler\electron-boilerplate\no
de_modules\rollup\dist\rollup.js:337:12)
    at invokeCallback (C:\Users\Quentin Laffont\Desktop\boiler\electron-boilerpl
ate\node_modules\rollup\dist\rollup.js:349:13)
    at publish (C:\Users\Quentin Laffont\Desktop\boiler\electron-boilerplate\nod
e_modules\rollup\dist\rollup.js:320:7)
    at publishRejection (C:\Users\Quentin Laffont\Desktop\boiler\electron-boiler
plate\node_modules\rollup\dist\rollup.js:270:3)
    at flush (C:\Users\Quentin Laffont\Desktop\boiler\electron-boilerplate\node_
modules\rollup\dist\rollup.js:131:5)
    at process._tickCallback (node.js:355:11)
Treating 'electron' as external dependency
Treating 'electron' as external dependency
Treating 'fs-jetpack' as external dependency
Treating 'fs-jetpack' as external dependency
[12:04:47] Finished 'less' after 88 ms
[12:04:48] Finished 'copy' after 333 ms
"

And my build.js : "
'use strict';

var pathUtil = require('path');
var Q = require('q');
var gulp = require('gulp');
var rollup = require('rollup');
var less = require('gulp-less');
var jetpack = require('fs-jetpack');

var utils = require('./utils');
var generateSpecsImportFile = require('./generate_specs_import');

var projectDir = jetpack;
var srcDir = projectDir.cwd('./app');
var destDir = projectDir.cwd('./build');

var paths = {
    copyFromAppDir: [
        './node_modules/**',
        './vendor/**',
        './css/**',
        './js/**',
        './**/*.html',
        './**/*.+(jpg|png|svg)',
    ],
}

// -------------------------------------
// Tasks
// -------------------------------------

gulp.task('clean', function (callback) {
    return destDir.dirAsync('.', { empty: true });
});

var copyTask = function () {
    return projectDir.copyAsync('app', destDir.path(), {
        overwrite: true,
        matching: paths.copyFromAppDir
    });
};
gulp.task('copy', ['clean'], copyTask);
gulp.task('copy-watch', copyTask);

var bundle = function (src, dest) {
    var deferred = Q.defer();

    rollup.rollup({
        entry: src,
    }).then(function (bundle) {
        var jsFile = pathUtil.basename(dest);
        var result = bundle.generate({
            format: 'cjs',
            sourceMap: true,
            sourceMapFile: jsFile,
        });
        // Wrap code in self invoking function so the variables don't
        // pollute the global namespace.
        var isolatedCode = '(function () {' + result.code + '\n}());';
        return Q.all([
            destDir.writeAsync(dest, isolatedCode + '\n//# sourceMappingURL=' + jsFile + '.map'),
            destDir.writeAsync(dest + '.map', result.map.toString()),
        ]);
    }).then(function () {
        deferred.resolve();
    }).catch(function (err) {
        console.error('Build: Error during rollup', err.stack);
    });

    return deferred.promise;
};

var bundleApplication = function () {
    return Q.all([
        bundle(srcDir.path('background.js'), destDir.path('background.js')),
        bundle(srcDir.path('app.js'), destDir.path('app.js')),
    ]);
};

var bundleSpecs = function () {
    generateSpecsImportFile().then(function (specEntryPointPath) {
        return Q.all([
            bundle(srcDir.path('background.js'), destDir.path('background.js')),
            bundle(specEntryPointPath, destDir.path('spec.js')),
        ]);
    });
};

var bundleTask = function () {
    if (utils.getEnvName() === 'test') {
        return bundleSpecs();
    }
    return bundleApplication();
};
gulp.task('bundle', ['clean'], bundleTask);
gulp.task('bundle-watch', bundleTask);

var lessTask = function () {
    return gulp.src('app/stylesheets/main.less')
    .pipe(less())
    .pipe(gulp.dest(destDir.path('stylesheets')));
};
gulp.task('less', ['clean'], lessTask);
gulp.task('less-watch', lessTask);

gulp.task('finalize', ['clean'], function () {
    var manifest = srcDir.read('package.json', 'json');

    // Add "dev" or "test" suffix to name, so Electron will write all data
    // like cookies and localStorage in separate places for each environment.
    switch (utils.getEnvName()) {
        case 'development':
            manifest.name += '-dev';
            manifest.productName += ' Dev';
            break;
        case 'test':
            manifest.name += '-test';
            manifest.productName += ' Test';
            break;
    }

    // Copy environment variables to package.json file for easy use
    // in the running application. This is not official way of doing
    // things, but also isn't prohibited ;)
    manifest.env = projectDir.read('config/env_' + utils.getEnvName() + '.json', 'json');

    destDir.write('package.json', manifest);
});

gulp.task('watch', function () {
    gulp.watch('app/**/*.js', ['bundle-watch']);
    gulp.watch(paths.copyFromAppDir, { cwd: 'app' }, ['copy-watch']);
    gulp.watch('app/**/*.less', ['less-watch']);
});

gulp.task('build', ['bundle', 'less', 'copy', 'finalize']);
"

Thanks for all.

**Comment by szwacz** [comment]
Rollup is erroring. It looks like malformed `import something from 'something'` statement, so I would suggest to comment all imports and uncomment them one by one to find the culprit line.

**Comment by Fristing** [comment]
I comment everything and same error ..

**Comment by szwacz** [comment]
Does it work when you do `npm start` instead of `npm run release`?

**Comment by Fristing** [comment]
before it's work and now same error.

**Comment by Fristing** [comment]
I erase the project and I create another project, If I have a problem I post a ticket.Thanks for all. QL.

**Comment by JimmyBoh** [comment]
@szwacz So it looks like I'm getting this error as well. I've tried commenting everything but it still appears. I'll try to dig in to what the issue actually is. Any other tips on debugging?

**Comment by JimmyBoh** [comment]
So I'm not sure exactly why, but I tried to move `app.html` and `app.js` down one level into a `ui` folder, which threw the whole thing off. But it seems to be working fine now!

**Comment by black-snow** [comment]
@JimmyBoh did you adjust your *build.js*, too? *app.js* and *background.js* are referenced there; see https://github.com/szwacz/electron-boilerplate/blob/master/tasks/build.js#L76

**Comment by JimmyBoh** [comment]
@black-snow Yeah, I believe I updated the reference to `app.js` inside of `build.js`. I even put a whole bunch of `debugger` and `console.log` calls inside of the `node_modules/rollup/dist/rollup.js` to try and track it down. No luck. But maybe I never changed the reference to `app.js`, and that was the issue. Since I changed it back, I've got a working dev environment and was able to build a Windows installer on the first try. Thank you @szwacz!!

**Comment by gimox** [comment]
go to /tasks/build/build.js
and comment line 51
`bundle(srcDir.path('app.js'), destDir.path('app.js')),`
it must work now.

**Comment by baerrach** [comment]
I had this problem when my file for `entry` didn't exist.

**Comment by dupski** [comment]
This is a terrible error message for a simple (and I imagine fairly common) config error - I get this when my `entry` config value points to a non-existent file.

**Comment by szwacz** [comment]
@dupski I'd say this is a rollup's area of responsibility. Actually there is PR for it: https://github.com/rollup/rollup/pull/804
