### ISSUE TITLE
Fresh install

### ISSUE THREAD

**Issue by DatTran** [szwacz/electron-boilerplate#104]
App threw an error when running [TypeError: Cannot read property 'getAppPath' of undefined]

I get this error.

**Comment by szwacz** [comment]
Hmm, too little data to say something. Which electron version has been used? What operating system?

**Comment by louptheron** [comment]
Hi, I have the same error : 
I am on Ubuntu 14.04 LTS, electron-prebuilt version 0.36.0 (tested whith 0.36.0) : 

[TypeError: Cannot read property 'getAppPath' of undefined]
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'getAppPath' of undefined
    at /home/rouxbot/WebstormProjects/electron-boilerplate/build/background.js:76:29
    at Object.<anonymous> (/home/rouxbot/WebstormProjects/electron-boilerplate/build/background.js:122:2)
   [...]

Thank you

**Comment by dmr** [comment]
Same problem here: I just did npm install, nothing special.
npm start throws that error.

electron 0.4.1 on OSX 10.11.3

**Comment by szwacz** [comment]
electron 0.4.1? Is it mistype or really you ment that? The latest electron is 0.36.7

**Comment by dmr** [comment]
Oh, you are right. 0.36.7.
I was confused by a npm package called "electron" with is something different ^^.

npm -v
3.7.1

node -v 
v5.5.0

Still the same issue: [TypeError: Cannot read property 'getAppPath' of undefined]

**Comment by black-snow** [comment]
`getAppPath()` is a method of electron's `app` object. There's two occurences in the boilerplate: https://github.com/szwacz/electron-boilerplate/search?utf8=%E2%9C%93&q=getAppPath

**Comment by dmr** [comment]
Sorry for the noise here, the problem has to do with the package electron that I installed in another project: --> npm install electron-prebuilt

"electron" is another program which has nothing to do with all of this!

If the package electron is installed anywhere it will cause a problem which leads to app not being defined.

https://github.com/atom/electron/issues/3708

**Comment by szwacz** [comment]
Ha! Never would anticipate that. Thanks for clearing this out!
