### ISSUE TITLE
Upgrade to 0.36.2

### ISSUE THREAD

**Issue by black-snow** [szwacz/electron-boilerplate#106]
Any chance you're upgrading to prebuilt *0.36.2* soon? (https://github.com/atom/electron/releases)

**Comment by szwacz** [comment]
Sure, it just happend. But this is change of one string in package json, so you what's the hassle? :)

**Comment by black-snow** [comment]
I had some issues with 0.36 - but I can't access that machine until thursday. Will report back if those issues remain.
