### ISSUE TITLE
Write more .exe details (Windows)

### ISSUE THREAD

**Issue by black-snow** [szwacz/electron-boilerplate#107]
I see that you use **rcedit** to overwrite the icon and the version string of the *.exe*. Sadly that seems to be pretty much everything **rcedit** is capable of which leaves all the GitHub and electron stuff in the .exe's details.

Do you know any other tool to overwrite those details? Or should I open an issue at **rcedit's** page?

**Comment by szwacz** [comment]
Already stumbled upon this: https://github.com/atom/rcedit/issues/2 This is documentation issue, rcedit is capable of doing this.

BUT, if you're using windows 10 then other issues come on stage: https://github.com/atom/rcedit/issues/3

**Comment by black-snow** [comment]
I didn't experience the issues mentioned in https://github.com/atom/rcedit/issues/3
I'll try to change those other properties with rcedit next week and report back.

Thanks for the reply!

**Comment by szwacz** [comment]
This boilerplate should utilize already some of those extra fields. If find any more for which it makes sense to add them here PR will be welcome!

**Comment by black-snow** [comment]
Alright, tried it on another machine - works well.

I've added
 
    'ProductVersion': manifest.version,
    'CompanyName': manifest.author,
    'LegalCopyright': manifest.copyright // I added a "copyright" field to app/package.json, dunno if this is "okay"

Also there's `OriginalFilename` and `InternalName` of which the first one should be set to `manifest.productName + '.exe'` I guess.

Please tell me whether you think it's okay to add custom fields to `package.json` or not and I'll file a PR. (for I think these are things that should be done by default)

**Comment by szwacz** [comment]
OSX has also ability to support copyright field so I'm guessing it's cool to add this field to package.json, so please do!

**Comment by black-snow** [comment]
PR here: https://github.com/szwacz/electron-boilerplate/pull/108

Didn't know what the helper stuff is on OS X so I didn't touch that.

**Comment by szwacz** [comment]
awesome!
