### ISSUE TITLE
Issue with node version 5.4.0

### ISSUE THREAD

**Issue by tezlopchan** [szwacz/electron-boilerplate#109]
![error](https://cloud.githubusercontent.com/assets/5461675/12259222/435d23e6-b93c-11e5-8cc3-f8ce01dc185e.png)

**Comment by black-snow** [comment]
What did you do? Please provide some details.

**Comment by szwacz** [comment]
Please try update `electron-prebuilt` dependency to latest version.

**Comment by tezlopchan** [comment]
:+1:

**Comment by black-snow** [comment]
@tezlopchan please close the issue if it has been resolved :)
