### ISSUE TITLE
Adding WebChimera dependency

### ISSUE THREAD

**Issue by ardoramor** [szwacz/electron-boilerplate#110]
I'm having issue with including wcjs-player to my app. In order to install it, I've created a `preinstall` script in `electron-boilerplate/app/tasks` which sets the required WebChimera.js environment variables:

    set npm_config_wcjs_runtime="electron"
    set npm_config_wcjs_runtime_version=electronVersion
    set npm_config_wcjs_arch="ia32"

I then run `npm install` from `electron-boilerplate/app` directory (package.json already has wcjs-player dependency). The installation goes fine. However, during start of the application, I get the following errors:

    WARNING in ./app/~/wcjs-player/~/wcjs-renderer/~/webchimera.js/~/bindings/bindings.js
    Critical dependencies:
    76:22-40 the request of a dependency is an expression
    76:43-53 the request of a dependency is an expression
     @ ./app/~/wcjs-player/~/wcjs-renderer/~/webchimera.js/~/bindings/bindings.js 76:22-40 76:43-53
    ...
    WARNING in ./app/~/wcjs-player/~/wcjs-renderer/~/webchimera.js/~/bindings/package.json
    Module parse failed: C:\Users\dragan\Documents\TeraLogics\hydra\app\node_modules\wcjs-player\node_modules\wcjs-renderer\node_modules\webchimera.js\node_modules\bindings\package.json Line 2: Unexpected token :
    You may need an appropriate loader to handle this file type.
    | {
    |   "name": "bindings",
    |   "description": "Helper module for loading your native module's .node file",
    |   "keywords": [
     @ ./app/~/wcjs-player/~/wcjs-renderer/~/webchimera.js/~/bindings ^\.\/.*$
    ...
    ERROR in ./app/~/wcjs-player/~/request/~/tough-cookie/package.json
    Module parse failed: C:\Users\dragan\Documents\TeraLogics\hydra\app\node_modules\wcjs-player\node_modules\request\node_modules\tough-cookie\package.json Line 2: Unexpected token :
    You may need an appropriate loader to handle this file type.
    | {
    |   "author": {
    |     "name": "Jeremy Stashewsky",
    |     "email": "jstashewsky@salesforce.com"
     @ ./app/~/wcjs-player/~/request/~/tough-cookie/lib/cookie.js 38:14-40

Did I not properly install the dependency?

**Comment by black-snow** [comment]
Did you get it running in a vanilla node app? / In a "vanilla electron" app?

**Comment by ardoramor** [comment]
Ok, I got it working finally. I think I was just new to webpack. I configured externals in webpack configuration as:

    externals: {
         "wcjs-player": "commonjs wcjs-player"
    }

That prevents the inclusion of wcjs-player node module into webpack and my stuff works. This issue can be closed now. Thanks!
