### ISSUE TITLE
Build 32 Bit with in 64 bit Machine?

### ISSUE THREAD

**Issue by tezlopchan** [szwacz/electron-boilerplate#111]
From the document I have installed nvm and have 2 node version one in 32 bit and one in 64 bit.. I change the node to 32 version and then run the command `npm run release` and when i try to install the new .exe file it stills says not support in 32 bit machine [Windows 8 32 bit]

**Comment by carlosperate** [comment]
Can you check if the electron prebuilt installed by node is the 32 bit version?
