### ISSUE TITLE
Can't release the app

### ISSUE THREAD

**Issue by Altiano** [szwacz/electron-boilerplate#114]
I just run `npm run release` and this error show:

```
Invalid command: Unicode
Error in script "D:\Projects\Web\Node\Electron\ResponsiveLayoutGen\tmp\installer.nsi" on line 32 -- aborting creation process

[21:10:03] Installer ready! D:\Projects\Web\Node\Electron\ResponsiveLayoutGen\releases\responsive-layout-gen_0.1.0.exe
[21:10:03] Finished 'release' after 20 s
```

It says that the installer ready but the `release` folder is empty

**Comment by black-snow** [comment]
Please check what line 32 is for you.
How come the directory is `tmp`?

Line 32 from resources installer.nsi would be `Unicode true`, I doubt that's the issue.

**Comment by coclav** [comment]
@Altiano are you using NSIS 3.0b3 ?
got this error when i was using NSIS 2.50

**Comment by pkunze** [comment]
Had the same problem with NSIS 2.50  
Installing NSIS 3.0.b3 as @coclav suggested solved the issue for me. Thanks a lot!

**Comment by szwacz** [comment]
Readme says already that NSIS v3 is required, so I'm afraid there is nothing more I can do ;)
