### ISSUE TITLE
[suggestion] add Livereload.js or Live.js in development mode

### ISSUE THREAD

**Issue by dariuszsikorski** [szwacz/electron-boilerplate#115]
**[edit]** I just have noticed it's a duplicate of: https://github.com/szwacz/electron-boilerplate/issues/21

During the development process gulp is watching app file changes and recompile them in real time, but after every change the browser has to be reloaded with ctrl+r keys to see this changes.

Including https://github.com/livereload/livereload-js or http://livejs.com/ could improve this process.

Although live-scripts require app served through http protocol, so it would require running up application through web server.

**Comment by szwacz** [comment]
Yes, will try to take a look at live relead soon.

**Comment by Reggino** [comment]
I ran into the same issue too. I finally added this line to `background.js`:
```
require('electron-reload')(__dirname);
```

See https://github.com/yan-foto/electron-reload . It's a bit crude, but gets the job done...

**Comment by mykone** [comment]
Hello @Reggino, where you able to get your reload working? I tried that technique, but it doesn't work for me.

**Comment by szwacz** [comment]
After battles with trying to integrate live reload to this project I must say this probably won't happen for now, for reasons I described here: https://github.com/szwacz/electron-boilerplate/pull/147#issuecomment-210664041

There is quite nice looking solution which you might like: https://github.com/Quramy/electron-connect (didn't try it in action though), but its integrations is so simple I don't think there is much gain in providing it here, everyone can do it on their own.
