### ISSUE TITLE
release stops on network drive

### ISSUE THREAD

**Issue by gbaumgart** [szwacz/electron-boilerplate#117]
Hi,
when running this on a network drive, it just stops after less got finished:

![image](https://cloud.githubusercontent.com/assets/1205100/12751929/36d031f6-c9c0-11e5-8223-6db67d52bddf.png)

What could that be ?

**Comment by black-snow** [comment]
Could be anything. Have you tried running it on a *local* drive?

**Comment by gbaumgart** [comment]
sure, works fine on local. it seems that the copy task in build.js never returns

**Comment by gbaumgart** [comment]
yeah definitely gulp got stuck and the copy tasks never finishes (has all defaults). Not sure its gulp or fs-jetpack (seems buggy too).

**Comment by gbaumgart** [comment]
removing the copy task in build made it work. No idea, i will just replace the fs-jetpack copyAsync function with something else. I gonna close this now.

**Comment by black-snow** [comment]
Ain't the *copy task* required in order to move the stuff from `app` to `build` and thus to actually run the correct stuff? Of course you could edit the whole thing so that it just runs on `app/`.

I'd be great if you could dig a little deeper and identify what's causing this exactely.

**Comment by gbaumgart** [comment]
sure, 
i do return now a new Q(); instead of the copyAsync result:

```
var copyTask = function () {
    projectDir.copyAsync('app', destDir.path(), {
        overwrite: true,
        matching: paths.copyFromAppDir
    });
    return Q();
};

```

now it works, fixes it for me. That's probably also not the best idea.. i know. 

the result of projectDir.copyAsync is always {state:pending}, both remote and local. 

However, just to let you know. I am going to make my own template soon, but with grunt and much less of the boiler stuff. 

thank you!

**Comment by gbaumgart** [comment]
I reopen the issue because gulp/fs-jetpack release is really lunatic, unpredictable. Sometimes things work, sometime it gets stuck (gulp clean) or it just doesn't give a damn. 

So if you're interested to know your tool actually working in real world-scenarios (big apps!), please do a simple run  in windows (vmware) but on a samba folder(not shared folder!, linux). Also add at least 800MB of files to it (i extended release_windows to copy folders into tmp). 


I am now fighting since days with your tool to get all stable and it seems really tough job. I start hating Node.js more and more... 

However, the actual goal of mine is to create a kind of windows build-machine and avoid copying the source files at any cost (for some reasons). It has to work from a Samba drive. 

If this is out of scope for you close it but I can tell you, your tool is definitely not stable when it comes to smb-drives(!) Also, if you think it works, restart the vmware, and try again. results differ.

And yes, I took care about the right permissions, correct installation ;-)

thanks

**Comment by szwacz** [comment]
@gbaumgart about fs-jetpack, thanks for the report, I'll try to reproduce your problems.

If you have 800 megs of assets then for sure copying them for every start doesn't make sense. What kind of assets are those? Graphics?

**Comment by carlosperate** [comment]
As a quick note, don't be so quick to blame it all on fs-jetpack, while it might be partially or fully responsible for your issues, I've had tons of problems in the past with samba stability when transferring large amounts of data.

**Comment by gbaumgart** [comment]
hi,
just to let you know regarding fs-jetpack trouble: i moved today my heavy copy-tasks out of the boiler-plate, over to grunt-copy tasks and surprisingly I have no more random 4048/4049 (permission/unknown errors through dir.copyAsync) or memory allocation crashes (came with big files). Those crashes came as said on a network drive (running from windows on a ubuntu-smb drive). Well, just saying.

You can close this here (moved now also to my own template).

**Comment by syads321** [comment]
i experienced this issues when tryng to run in windows 8 64 bit of my laptop, but run succesfully  in 32 bit of win 7 of my PC.
Any reason of this issues ? 
Thanks.

**Comment by gbaumgart** [comment]
make sure it's not an anonymous connection to your SMB server. I am using "Bitvise SSH Server" for windows which allows you to setup a network drive together with the login. since then I've no problems anymore but I also moved to grunt for the copy tasks.
