### ISSUE TITLE
some improvements

### ISSUE THREAD

**Issue by gbaumgart** [szwacz/electron-boilerplate#118]
hi,
here a number things which make it more usable:

1. Create the tmp folder with a platform prefix
2. Option to not delete the tmp folder. At time of prototyping you really don't want wait for the installer, then actually install the application and then start debugging. That needs another gulp task to start against the temp folder.
4. Support electron-prebuilt to be installed via npm -g. Of course, you will have to determine this global install path yourself per platform. However, that allows you to use the same folder between windows/linux on a network drive. With big apps, this saves copying too much stuff around and avoids multiple installs of the same thing, which becomes really annoying fast.
5. And those gulp-watchers, please make them optional. Very annoying too.

Ok, makes only sense if you wanna have it more than just a template. 

greets,
g

**Comment by szwacz** [comment]
First I want to be sure I understand your use case. So what you're trying to do is use one place on network drive to develop the application from there on different operating systems? But you mean actually writing new lines of code on this network drive or just testing it this way?

**Comment by gbaumgart** [comment]
yes, and I got it working so far. I've got too much files (1000+ in PHP/JS and what not). Of course I'd like to do the "npm start" against my files without copying them around. Especially doing new electron-code: I'd like to play with from different operating systems from within the temp-Folder (almost live version) with npm release --debug or similar.

Anyway, very possible this is out of scope for you but if people trying to do similar (which more likely is happening), it can take days to get it there. Btw, today fs-jetpack did just fine today, really weird (maybe its indeed a samba/vm problem only).

thanks,

**Comment by black-snow** [comment]
I don't think it is *likely to happen* that many people use this boilerplate for projects w/ 1k+ files (Jesus ...) or at least they'll know how to get around. You shouldn't blame the boilerplate for that it doesn't suit your needs. IMHO you should rather blame your choice of tools. There's no need to use watchers. Just deactivate them, what's the issue?

**Comment by gbaumgart** [comment]
yeah Ronald, are you ok? Nobody blamed anyone. Normalerweise wenn Du nix beizutragen hast, einfach Fresse halten! Aus Deiner kommt nur Muell

**Comment by black-snow** [comment]
@gbaumgart Sehr kritikfähig, Respekt.

**Comment by szwacz** [comment]
Relax gentleman! Go get yourself some beer :)

@gbaumgart your usecase is very interesting, because this is JUST how I wanted to work on electron (actually node-webkit back then) app when I started my adventures on this field, but failed miserably with this approach. This boilerplate is established the way it is because I just couldn't get nice developer experience on shared folder (also my lack of knowledge might had been major contributor).

Right now I work just with VMs and git: Write some code, test it, push to git repo, switch to VM, git pull, test on VM, repeat.

Maybe second attempt to shared network project isn't a bad idea. Will think about it in free time, and are interested in all your experience if you want to share more of it with us.

About heavy assets: This one is tricky. Have you tried doing some symlinks and not copy the assets?

**Comment by gbaumgart** [comment]
Hi,

regarding git ping-pong: yeah, thats what i meant; it just consumes a hell of time and is pretty much error-prone, at least with that 20+ git sub-modules I have. 

However, if you implement all the points in my initial post, you'll have it working on a SMB drive, no more duplicated folders /installations. I am pretty happy now with and it works from within all OS (mac/windows).

experience:

- don't use Virtual-Machine Shared Folders. it will fail copying (gulp release) the underlying node_modules folder (somewhere in fs-jetpack/node_modules/.bin). No idea why. I use the regular Samba on Ubuntu; just open the permissions max. as possible. You can adjust SAMBA with webmin pretty easy. I can't remember but I changed something about locks.

- You can fully automate the gulp release task from Ubuntu on Windows by setting up a SSH server in the windows-box with Bitvise-SSH server and some more grunt tasks (ssh) on your project. Takes a little time fiddling but it worth every penny. I added also some quick & general tests via grunt to check that the build is actually working.  

Then about assets: Symlinks wont work on a SMB drive anyways nicely. I would need also too many of them and I have bad experience with them.
