### ISSUE TITLE
npm deprecated warnings

### ISSUE THREAD

**Issue by beriberikix** [szwacz/electron-boilerplate#119]
I received the following deprecated warnings when running `npm install`:

* `npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.`
* `npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.`
* `npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.`

Seems to work fine but figured it was worth tracking.

**Comment by szwacz** [comment]
It's a gulp's dependency, not direct dependency of this project. But since it's gulp it should be resolved quite quiclky.

**Comment by szwacz** [comment]
I have no idea how long those deprecations will be with us, but this is nothing I can do something about.
