### ISSUE TITLE
Vanilla install: 'Error in script' when building release

### ISSUE THREAD

**Issue by sclearion** [szwacz/electron-boilerplate#120]
I am getting this error when i run `npm run release` on **Windows 10**. Out of 10 builds on 2 will randomly pass and I will get an installable exe. The rest throw this error

`Error in script "C:\Users\workpc2\Documents\MyProjects\apptest\tmp\installer.nsi" on line 103`

Line 103 contents (I changed nothing at all???):
`File /r "${src}\*"`

- electron-boilerplate version: 0.36.0
- NSIS version: 3.0b3
- Node version: 5.3.0
- Windows 10

Things done to try to remedy:
- uninstall / reinstall node + nsis + electron
- checked file permissions
- check files for BOM/encoding errors
- disabled tmp folder wiping; in case resources getting wiped before they are read

**Comment by szwacz** [comment]
Unfortunately wasn't able to reproduce. On what path on hard disk you've putted the repo folder?

**Comment by black-snow** [comment]
@sclearion how come your `installer.nsi` is in `...\tmp` instead of `...\resources\windows`?

**Comment by sclearion** [comment]
Thats where it gets copied to, the /tmp folder. Grunt is creating it and deleting it afterwards. I havent changed a thing

**Comment by sclearion** [comment]
@szwacz the path is C:\Users\workpc2\Documents\MyProjects\apptest. which i renamed from 'electron-boilerplate'

**Comment by szwacz** [comment]
The .nsi file has some {{data_fields}} to be filled with real data, tha't why it's copied from resources to tmp.

Ok, so the project directory is in your user folder. No surprise here, same as on my VM.

Do you have access to any other instance of windows 10 machine to have sample size bigger than one?

**Comment by sclearion** [comment]
No I do not at the moment. I have noticed that when I have the folder open in Atom, the folder also open in windows explorer and a shell open to the same folder that is does not work. Could this be a file permission/lock issue?

**Comment by black-snow** [comment]
If you could zip your project and upload it somewhere I could run it on another win10 machine.

` File /r "${src}\*"` is from the tmp-dir's `installer.nsi`? How does line `12` look? Has the placeholder been replaced properly?

I, too, have the directory open in explorer + editor + cmd (at least) - that shouldn't be an issue :)

**Comment by sclearion** [comment]
Ok. Im on my ubuntu box now. Ill get on my windows and send them

**Comment by matikbird** [comment]
szwacz don't close issues if they weren't solved.
I do have this problem too:
Building installer with NSIS... (...)
Processing config: C:\Program Files (x86)\NSIS\nsisconf.nsh
**File: failed opening file: "C:\Users\Notebook\.....\resources\app.asar**
**Error in script: "C:/Users/Notebook/.../tmp/installer.nsi" on line 103 -- aborting creation process**
