### ISSUE TITLE
windows_state.json sometimes corrupt

### ISSUE THREAD

**Issue by gbaumgart** [szwacz/electron-boilerplate#126]
sometimes this file seems corrupt and is filled with null bytes. in return you can't start the application anymore till this file is deleted. Please add try/catch when reading that file. whilst at it, could you please add the state for the developer-console[open/closed] ? 

thanks

**Comment by szwacz** [comment]
How often this json corruption happens?

**Comment by szwacz** [comment]
Can you reproduce it or is it totally random?

**Comment by gbaumgart** [comment]
It's too rare, happens once in week or so (we use the app daily). Another thing I noticed that sometimes - same rare - when you close the app but it's still in background but for that will post another issue. I feel that both issues are somehow related but I am not sure. Sorry, it's all i got now. I think simplest is to check for valid json before writing it out.

**Comment by szwacz** [comment]
There you go: https://github.com/szwacz/electron-boilerplate/commit/60bd2865825c0796c84dffed8cbe62ec21716a93

Remembering devtools state is also good idea, will do it in near future.

**Comment by gbaumgart** [comment]
great, that's awesome support, as always. 
thanks again.
ps: you can close this

**Comment by szwacz** [comment]
No problem. Will close after making devtools feature as well.

**Comment by gbaumgart** [comment]
there is another little bug with the window-state: if you move the window on multi-monitors, and unplug the one which had the app as last, and then restart the app: the app will be started at coordinates which dont exists anymore (unplugged screen). I am aware this might be difficult to fix since there is not an easy way to determine and check actual hardware screens, I will investigate possible fixes now and let you know.

**Comment by gbaumgart** [comment]
this seems legit, didn't test but it seems to check the positions: https://github.com/mawie81/electron-window-state/blob/master/index.js

**Comment by szwacz** [comment]
@gbaumgart how about just check if coords are within the visible area and if not reset the window to default settings? Should be pretty easy to do and gets job done.

**Comment by gbaumgart** [comment]
sounds good, just not sure about how to get the visible area at all. I was studying the electron docs up & down but i can't find anything related; or you've got a pointer already?

**Comment by szwacz** [comment]
Don't know how OS treats the desktop size when you have more than one display plugged in. Is it just one plane with bigger width or height? If so then simple check like this will do the job.
```js
// pseudocode
if (window.x < 0 || 
  window.y < 0 || 
  window.x + window.width > screen.width ||
  window.y + window.height > screen.height) {
  restoreDefaults();
}
```

**Comment by szwacz** [comment]
Refactored window state manager: https://github.com/szwacz/electron-boilerplate/blob/master/app/helpers/window.js Now can deal with unplugged displays. Tested only on Mac. If someone can test it on Windows I'll be grateful.

**Comment by gbaumgart** [comment]
awesome, thanks Jacob. will do the testing straight away tom.
