### ISSUE TITLE
Broken watching behavior on OS X (at least).

### ISSUE THREAD

**Issue by DylanLukes** [szwacz/electron-boilerplate#128]
It seems like it's pretty common for bundle-watch to just fail to run. Sometimes it won't run at all, sometimes it takes an absurd amount of time to finish, sometimes it runs a few times but then any amount of file modifications will cause it to not work. 

See here for an example: http://imgur.com/E5A0Bzi

I've worked with gulp plenty, but I always ran into bizarre issues and race conditions with anything related to `gulp.watch`. I strongly suggest explicitly changing it to use `gulp-watch`, which is built on `chokidar` and has substantially less issues (especially on OS X or when using a file editor that keeps open file handles and doesn't fully flush or open/close with every edit).

Also it looks like `vinyl-fs` is removing `watch` (which is what this boilerplate uses) so this is probably going to have to happen soon anyways. On the other hand, `rollup` is pursuing incremental builds (and rebuilds) as a high priority target. Switching over to not use the `watch` included by `gulp` from `vinyl-fs` and using `node-watch` would probably solve these problems. *I'm going to see if it's an easy change and submit a pull request if it is.*

Note: `gulp` uses `vinyl-fs ^0.3.0`... `vinyl-fs` is currently at `2.4.1`... So it's also that it's using an ancient version.

I hate to say it but gulp is the weakest link in this boilerplate. Everything else works great...

```js

var runBuild = function () {
    var deferred = Q.defer();

    var build = childProcess.spawn(utils.spawnablePath(gulpPath), [
        'build',
        '--env=' + utils.getEnvName(),
        '--color'
    ], {
        stdio: 'inherit'
    });

    build.on('close', function (code) {
        deferred.resolve();
    });

    return deferred.promise;
};

var runGulpWatch = function () {
    watch = childProcess.spawn(utils.spawnablePath(gulpPath), [
        'watch',
        '--env=' + utils.getEnvName(),
        '--color'
    ], {
        stdio: 'inherit'
    });

    watch.on('close', function (code) {
        // Gulp watch exits when error occured during build.
        // Just respawn it then.
        runGulpWatch();
    });
};

// ...

runBuild()
.then(function () {
    runGulpWatch();
    runApp();
});
```

**Comment by szwacz** [comment]
I have few issues with gulp as well, and waiting (for about a year now?) for gulp v4 to resolve those issues. That being said gulp-way of constructing and running tasks is the best approach I've seen so far.

About using gulp-watch: all contributions are welcome!

Open question: What are the alternatives to gulp right now? Haven't been using grunt for ages. How is that ecosystem doing? Are there any new, hot task runners I've missed on hacker news? ;)

**Comment by szwacz** [comment]
The watch now uses gulp-watch. Hope it will work better!
