### ISSUE TITLE
disable asar packaging

### ISSUE THREAD

**Issue by qubicle** [szwacz/electron-boilerplate#129]
Is there a way to disable asar packaging when building a release?
Thanks!

**Comment by szwacz** [comment]
Yes, just comment function `packageBuiltApp` in release script for your platform :)

**Comment by qubicle** [comment]
if i remove the line, the build app is not working anymore. tested with mac OS X.

Uncaught Exception:
Error: Unable to find a valid app
    at Object.<anonymous> (/Applications/Stashcat Desktop Client.app/Contents/Resources/atom.asar/browser/lib/init.js:117:9)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:151:18)
    at node.js:1005:3

**Comment by szwacz** [comment]
Ahh, sorry. I was recalling it from my memory. You need to copy the app into same directory where the asar file ended. So you need to alter `packageBuiltApp` so it just copies raw files, without actually packaging them.

**Comment by matikbird** [comment]
Can you elaborate more on that, @szwacz 

I'm a bit confused.. Really don't know what to do.

I guess from this:
```
var packageBuiltApp = function () {
    var deferred = Q.defer();

    asar.createPackageWithOptions(projectDir.path('build'), readyAppDir.path('resources/app.asar'), {
        dot: true
    }, function () {
        deferred.resolve();
    });

    return deferred.promise;
};

```
I do this:```

var packageBuiltApp = function () {
    return projectDir.path('build');
};
```
