### ISSUE TITLE
How to include libraries such as jQuery or bootstrap?

### ISSUE THREAD

**Issue by sunsgs** [szwacz/electron-boilerplate#130]
I Am wondering how to include thirdy parts libraries.

**Comment by black-snow** [comment]
There's packages on npm. Or if

**Comment by szwacz** [comment]
The simplest way for jquery and bootstrap would be just to copy them to `app/vendor` directory and then embed <script> tags into https://github.com/szwacz/electron-boilerplate/blob/master/app/app.html you can see it's done there for some scripts already.
