### ISSUE TITLE
Unable to copy dot files

### ISSUE THREAD

**Issue by aag035** [szwacz/electron-boilerplate#132]
I'm using one of the modules (exceljs) which has dot files in it's node_modules/lib folder. When I try npm run release, this dot file doesn't get bundled in app.asar file and my app throws error. Any way to achieve this and successfully copy dot file to asar?

**Comment by szwacz** [comment]
I've pushed patch to fs-jetpack library. Please do `npm update` and it should work after that.

**Comment by aag035** [comment]
Thanks. After update, I was able to copy hidden files to build folder. Asar module was failing to copy too.  Suggestion : You can change the call from asar.createPackage to asar.createPackageWithOptions here https://github.com/szwacz/electron-boilerplate/blob/master/tasks/release/windows.js and pass {dot : true} while calling, so that asar knows to package hidden files too.

**Comment by szwacz** [comment]
Thanks for the hint. Now asar supports dotfiles packaging.
