### ISSUE TITLE
Windows icon is not set at Program Files/appName/appName.exe

### ISSUE THREAD

**Issue by tyv** [szwacz/electron-boilerplate#134]
Here is how it looks, old Electron icon is used: http://screencast.com/t/RBc6kT8iNC
But everywhere around: start menu, taskbar etc... normal icon is used

**Comment by black-snow** [comment]
Which Windows version are you on? Which boilerplate version? Which NSIS version?

Can you check if it's an rcedit issue? See https://github.com/szwacz/electron-boilerplate/blob/master/tasks/release/windows.js#L52

**Comment by tyv** [comment]
windows 7, 32bit
boilerplate is https://github.com/szwacz/electron-boilerplate/commit/4e1333bb2e79fd18476742e7f658a2519e5fa7bc
NSIS is 3.0b3

I will try to merge boilerplate master to my repo and then update you with comment. 
About rcedit, I have same string in config. Will check whats happening there.

**Comment by black-snow** [comment]
Thanks for the update.

It should be easy to check if it's an rcedit-related issue. Create a clean node project, npm install rcedit, copy any exe to the project, copy some icon to the project, create a script with:

```javascript
var rcedit = require('rcedit');
rcedit('path-to-the.exe', {
    'icon': 'path-to-some-icon',
    'version-string': {
        'ProductName': 'whatever'
    }
  }, function (err) {
        console.log(err)
  });
```

Run the script and see if the icon changed. If I'm not missing anything this sould work.
If it's not changing the icon* you should post that issue on *rcedit's* tracker.

*And not failing, throwing any errors

**Comment by tyv** [comment]
ok, will do.
one more important thing is I've had to update to `"electron-prebuilt": "^0.37.2"`

**Comment by carlosperate** [comment]
Keep in mind that Windows is not very good a refreshing their icons. If you have installed/used the application with the default icon first, and then added it, it might not show up or refresh right away.

**Comment by tyv** [comment]
@carlosperate huh, good point. will check this too.

**Comment by black-snow** [comment]
Good hint. Right-click -> Props -> Details might show the right icon.

**Comment by tyv** [comment]
Answer: atom/node-rcedit#12
