### ISSUE TITLE
Single Run

### ISSUE THREAD

**Issue by blainesch** [szwacz/electron-boilerplate#135]
I'm trying to run the tests once so I can set this up with CI. Any suggestions?

I can setup a `test` gulp task that removes the `watch` but now it won't close once it's done.

~~~ javascript
gulp.task('test', ['build'], function () {
    childProcess.spawn(electron, ['./build'], {
        stdio: 'inherit'
    })
    .on('close', function () {
        process.exit();
    });
});
~~~

**Comment by szwacz** [comment]
Hmm, interesting idea. To make it work Jasmine have to give us some way of registering callback function when all tests are done. And depending on the test outcome exit the process form javascript with proper code.

Also for it to make sense all failed test errors should be printed to terminal console I believe.
