### ISSUE TITLE
signing app for App Store

### ISSUE THREAD

**Issue by tyv** [szwacz/electron-boilerplate#141]
signing app for Apple App Store requires this sandbox declarations: http://electron.atom.io/docs/v0.35.0/tutorial/mac-app-store-submission-guide/#sign-your-app

is there a proper way to include this in build or amending build script is the only way?

**Comment by szwacz** [comment]
There is a pull request exactly on this topic now going on: https://github.com/szwacz/electron-boilerplate/pull/122

**Comment by szwacz** [comment]
The PR has been merged.
