### ISSUE TITLE
How set the node_env?

### ISSUE THREAD

**Issue by Riuujin** [szwacz/electron-boilerplate#146]
I am using this boilerplate and react, now by default react is in development mode. To change this I need to set the node_env to 'production' (example: `process.env.NODE_ENV = 'production';`). What would be the best way to do this?

**Comment by szwacz** [comment]
In https://github.com/szwacz/electron-boilerplate/blob/master/app/background.js adding line:
```js
process.env.NODE_ENV = env.name;
```
should do the job. This boilerplate has concept of environments. It's also described a little in that file.

**Comment by Riuujin** [comment]
Ah thank you, didn't see that.
