### ISSUE TITLE
Context menu not work.

### ISSUE THREAD

**Issue by misteral** [szwacz/electron-boilerplate#148]
Context menu not work on Mac OS X.

**Comment by szwacz** [comment]
Electron by default gives you no context menu, so not that it isn't working, it isn't implemented.
This project implements simple 'cut/copy/paste' context menu for text inputs. I believe I can make also 'copy' possible when some text on page is selected.

Something besides that?

**Comment by misteral** [comment]
O-h, thanks! 
> I believe I can make also 'copy' possible when some text on page is selected.
Should be very good !

**Comment by blainesch** [comment]
> I believe I can make also 'copy' possible when some text on page is selected.

What are the steps required for this? I can see additional shortcuts like ctrl+a/ctrl+e being important as well.

**Comment by carlosperate** [comment]
Copy on text selection would be quite welcomed!

**Comment by szwacz** [comment]
There you have it: https://github.com/szwacz/electron-boilerplate/commit/10a9dd868ce0c9728278f22f83a45f0c95be8e03

Also now standard hotkeys like `ctrl+c` are working by default: https://github.com/szwacz/electron-boilerplate/commit/4f9d761db07d647dedb15aeb0ba12fee21f15589

**Comment by szwacz** [comment]
Oops, forgot one import: https://github.com/szwacz/electron-boilerplate/commit/575f46cfa58e69d6878c414c9f579e7e059eefa7
