### ISSUE TITLE
Raspberry Pi Three / Resin

### ISSUE THREAD

**Issue by cnbecom** [szwacz/electron-boilerplate#154]
I am trying to just build this as a starting point for my own application on a Raspberry Pi 3 via Resin.io

I am able to push to Docker (for Resin) and build. However, when I attempt to launch the application on the device, I get this error:

 @ start /usr/src/app
25.04.16 11:40:36 [-0400] > gulp start
25.04.16 11:40:36 [-0400]
25.04.16 11:40:47 [-0400] [15:40:47] Using gulpfile /usr/src/app/gulpfile.js
25.04.16 11:40:47 [-0400] [15:40:47] Starting 'clean'...
25.04.16 11:40:47 [-0400] [15:40:47] Starting 'watch'...
25.04.16 11:40:47 [-0400] [15:40:47] Finished 'watch' after 88 ms
25.04.16 11:40:47 [-0400] [15:40:47] Finished 'clean' after 174 ms
25.04.16 11:40:47 [-0400] [15:40:47] Starting 'bundle'...
25.04.16 11:40:47 [-0400] [15:40:47] Starting 'less'...
25.04.16 11:40:47 [-0400] [15:40:47] Starting 'copy'...
25.04.16 11:40:47 [-0400] [15:40:47] Starting 'finalize'...
25.04.16 11:40:47 [-0400] [15:40:47] Finished 'finalize' after 9.9 ms
25.04.16 11:40:47 [-0400] [15:40:47] Finished 'bundle' after 639 ms
25.04.16 11:40:48 [-0400] [15:40:48] Finished 'less' after 929 ms
25.04.16 11:40:51 [-0400] [15:40:51] Finished 'copy' after 4.45 s
25.04.16 11:40:51 [-0400] [15:40:51] Starting 'build'...
25.04.16 11:40:51 [-0400] [15:40:51] Finished 'build' after 72 μs
25.04.16 11:40:51 [-0400] [15:40:51] Starting 'start'...
25.04.16 11:40:51 [-0400] [15:40:51] Finished 'start' after 104 ms
25.04.16 11:40:52 [-0400] /usr/src/app/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

Any ideas? I appreciate any help as I am relatively new to Electron / Resin and working Raspberry Pi

**Comment by blainesch** [comment]
@cnbecom that sounds like an electron issue, not this boilerplate specifically.

Can you try running the electron provided boilerplate? It's more of a bare-minimum one:
https://github.com/electron/electron-quick-start

**Comment by cnbecom** [comment]
it actually doesn't. I do get a similar error as well

25.04.16 13:53:42 [-0400] > electron-quick-start@1.0.0 start /usr/src/app
25.04.16 13:53:42 [-0400] > electron main.js
25.04.16 13:53:42 [-0400]
25.04.16 13:53:43 [-0400] /usr/src/app/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
25.04.16 13:53:43 [-0400]
25.04.16 13:53:43 [-0400] npm ERR! electron-quick-start@1.0.0 start: `electron main.js`
25.04.16 13:53:43 [-0400] npm ERR! Exit status 127
25.04.16 13:53:43 [-0400] npm ERR!
25.04.16 13:53:43 [-0400] npm ERR! Failed at the electron-quick-start@1.0.0 start script.
25.04.16 13:53:43 [-0400] npm ERR! This is most likely a problem with the electron-quick-start package,
25.04.16 13:53:43 [-0400] npm ERR! not with npm itself.
25.04.16 13:53:43 [-0400] npm ERR! Tell the author that this fails on your system:
25.04.16 13:53:43 [-0400] npm ERR! electron main.js
25.04.16 13:53:43 [-0400] npm ERR! You can get their info via:
25.04.16 13:53:43 [-0400] npm ERR! npm owner ls electron-quick-start
25.04.16 13:53:43 [-0400] npm ERR! There is likely additional logging output above.
25.04.16 13:53:43 [-0400] npm ERR! System Linux 4.1.18
25.04.16 13:53:43 [-0400] npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
25.04.16 13:53:43 [-0400] npm ERR! cwd /usr/src/app
25.04.16 13:53:43 [-0400] npm ERR! node -v v0.10.22
25.04.16 13:53:43 [-0400] npm ERR! npm -v 1.3.14
25.04.16 13:53:43 [-0400] npm ERR! code ELIFECYCLE
25.04.16 13:53:43 [-0400] npm ERR!
25.04.16 13:53:43 [-0400] npm ERR! Additional logging details can be found in:
25.04.16 13:53:43 [-0400] npm ERR! /usr/src/app/npm-debug.log
25.04.16 13:53:43 [-0400] npm ERR! not ok code 0
