### ISSUE TITLE
Can't change setup-banner.bmp

### ISSUE THREAD

**Issue by d0nk3y** [szwacz/electron-boilerplate#155]
I'm using the installer setup that's part of electron-boilerplate, but I'm unable to modify setup-banner.bmp.  If I leave it alone and generate an installer, it works fine and the image shows up on the left hand side of the installer dialog.  However, if I make a change of any sort to the image, it no longer appears on the dialog.  It just leaves a big gray space.  I'm sure it's not a problem with me changing the size of the image or something like that because I've tried opening it and saving it again without resizing or touching a single pixel.  Any idea what's going on?  I'm stumped!

**Comment by szwacz** [comment]
Had similar problem, probably BMP implementation of NSIS plugin or whatever is somehow lacking. Trick which worked for me was to save the BMP with MS Paint :)

**Comment by blainesch** [comment]
Is  there a mac port of mspaint? :P

**Comment by szwacz** [comment]
I don't have windows machine either. Using VM for testing and stuff: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/mac/

**Comment by d0nk3y** [comment]
Wow!  How crappy!  ;)  That fixed it though.  Many thanks!
