### ISSUE TITLE
How to run gulp command in my application.

### ISSUE THREAD

**Issue by kenzouno1** [szwacz/electron-boilerplate#156]
I'm installed module gulp and run test task alert string "Hello world".
After release to exe file i'm run app but response a error message "Local gulp not found".
How to i can use gulp in my application?

my app.js file

import gulp from 'gulp';
function runCmd(cmd) {
	console.log('Running command '+cmd);
	var exec = require('child_process').exec;
	var child = exec(cmd);
	child.stdout.on('data', function(data) {
	    console.log(data);

	});
	child.stderr.on('data', function(data) {
	    console.log(data);
	});
}
document.addEventListener('DOMContentLoaded', function () {
    document.getElementById('greet').innerHTML = greet();
    document.getElementById('platform-info').innerHTML = os.platform();
    document.getElementById('env-name').innerHTML = env.name;
    runCmd('gulp');
});

and app/package.json

 "dependencies": {
    "fs-jetpack": "^0.7.0",
    "gulp": "^3.9.1"
  },

**Comment by szwacz** [comment]
Why would you use gulp in your application? This tool is designed e.g. to compile your application, not to use it inside that application.

**Comment by kenzouno1** [comment]
Yep.I'm not a nodejs developers (i'm learn gulp in google not nodejs) and i know this this is stupid question and my english is very bad.
i use this tool because it is very easy to use. but i can't find gulp module in my application after release

**Comment by iamjohnlong** [comment]
@kenzouno1 you may need the gulp cli installed and added to your deps https://github.com/gulpjs/gulp-cli

maybe he is building an app to run gulp commands through a GUI?

**Comment by kenzouno1** [comment]
@iamjohnlong Yep.Because i have starter kit for html and wordpress.I want use it for my friends in company.But they do not know how to use the command line.
My idea is use electron build a GUI application.This app will write a json file path to a project and css,js file.After run command build sass,js lint etc...with a button.I just learn gulp a few days and i'm not a Nodejs developers and my english very bad so somewhat difficult to learn electron.

After two days search i found my problem is deficient cwd in child_process.
Code to run command now.
`	var exec = require('child_process').exec;
	var child = exec(command,{
		env: {"ATOM_SHELL_INTERNAL_RUN_AS_NODE":1},
		cwd:app.getAppPath()
	});
	child.stdout.on('data', function(data) {
	    console.log(data);
	});
	child.stderr.on('data', function(data) {
	    console.log(data);
	});`
Currently it is not an error message but gulp task not running.
here is list file in app.getAppPath();
`"C:\Program Files\Electron Boilerplate\resources\app.asar/app.html"
1
:
"C:\Program Files\Electron Boilerplate\resources\app.asar/app.js"
2
:
"C:\Program Files\Electron Boilerplate\resources\app.asar/app.js.map"
3
:
"C:\Program Files\Electron Boilerplate\resources\app.asar/background.js"
4
:
"C:\Program Files\Electron Boilerplate\resources\app.asar/background.js.map"
5
:
"C:\Program Files\Electron Boilerplate\resources\app.asar/gulpfile.js"
6
:
"C:\Program Files\Electron Boilerplate\resources\app.asar/helpers/context_menu.js"
7
:
"C:\Program Files\Electron Boilerplate\resources\app.asar/helpers/dev_menu_template.js"
8
:
"C:\Program Files\Electron Boilerplate\resources\app.asar/helpers/edit_menu_template.js"
9
:
"C:\Program Files\Electron Boilerplate\resources\app.asar/helpers/external_links.js"
10
:
"C:\Program Files\Electron Boilerplate\resources\app.asar/helpers/window.js"`
