### ISSUE TITLE
Unable to run install-native script

### ISSUE THREAD

**Issue by sr-verve-alwin** [szwacz/electron-boilerplate#157]
I could not run install-native script. I get the following error when I try to run:
npm run install-native -- sqlite3

```
npm ERR! Error: ENOENT, open '/home/alwin/WORK/Whitemail/electron-boilerplate/node_modules/install-native/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-49-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run-script" "install-native" "--" "sqlite3"
npm ERR! cwd /home/alwin/WORK/Whitemail/electron-boilerplate
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/alwin/WORK/Whitemail/electron-boilerplate/node_modules/install-native/package.json
npm ERR! code ENOENT
npm ERR! errno 34

```

**Comment by sr-verve-alwin** [comment]
Oops.

i found the issue. The problem is in the syntax given in the docs.
In the doc(README.MD) the command to install native module is given as
`npm run install-native -- name_of_native_module`
This is wrong. There is a space between '--' and name_of_native_module
The correct command would be
`npm run install-native --name_of_native_module`

**Comment by sr-verve-alwin** [comment]
I am sorry to reopen the issue. But it looks like removing the space worked only halfway. It ran the script and installed electron-rebuild. But then it ended up with this error
`Module name not specified! Correct usage is "npm run install-native -- name_of_native_module" (remember about space after "--"`

So if I put space, it does not even start. Omitting the space will trigger another error from within the script.

**Comment by szwacz** [comment]
Space for sure is required: https://docs.npmjs.com/cli/run-script
I don't know what might be wrong, but think it might be problem of your machine:
```
ENOENT, open '/home/alwin/WORK/Whitemail/electron-boilerplate/node_modules/install-native/package.json'
```

install-native is just a file in `tasks/`folder in this repo, and for some reason npm tries to resolve it as a module.

Are you using OSX or linux?

**Comment by sr-verve-alwin** [comment]
I am using linux (ubuntu 14.0 lts 32 bit).

I am also wondering why it tried to load it as a module when it is simply a script. 

Stranger still, if I run
`npm run install-native`
without any args, then the script starts and ends with no module specified error. The space between '--' and module name is triggering the error on my machine. Like you said it looks like a machine related issue. I do not have this problem on a windows machine.

**Comment by szwacz** [comment]
I've never tried this feature on linux, so it might be platform-specyfic as well.

**Comment by szwacz** [comment]
Tried to native install on Ubuntu 64bit VM and it worked ok. Do you have access to any other linux machine to make sure this problem isn't just misconfiguration of one machine?

**Comment by szwacz** [comment]
Well it doesn't work anyway, but this is because of https://github.com/electron/electron-rebuild/issues/66
But for sure I don't see the same error as you.

**Comment by crazy-max** [comment]
Yes same thing for me with electron-rebuild 1.1.3 linked to `1.0.2` moved to `iojs-1.0.2`

**Comment by alwintom** [comment]
@szwacz 
I do not have access to another linux machine. But everything works on Windows. So I guess its specific to my machine.
