### ISSUE TITLE
Add Bower to app ?

### ISSUE THREAD

**Issue by crazy-max** [szwacz/electron-boilerplate#158]
Hi,

I have included bower to this awesome boilerplate.
I can make a pull request but is it relevant to include bower in this boilerplate ?

**Comment by blainesch** [comment]
I feel like bower makes it easy to include scripts via a `script` tag. You can include most of the scripts via npm and `require` or `import` them without the need for a `script` tag. What do you think?

**Comment by szwacz** [comment]
As a rule of thumb I try to keep this project as small as possible, and leave many easy to make decisions to end users. Addition of Bower is no brainer, so everyone who needs it can easily do it on his/her own.

Also Bower is after its peak popularity. Personally as a rule of thumb, I don't use it in new projects (just my way, don't want to start flame war here ;).

**Comment by crazy-max** [comment]
Seems legit, thanks for your point of view!
