### ISSUE TITLE
tests broken on windows

### ISSUE THREAD

**Issue by leshow** [szwacz/electron-boilerplate#159]
recently pulled and my tests are failing to run now

```
Error: Could not resolve ./c:/Users  estelectron-lobbyappfrontendlibasInterface.spec.js from c:\Users\test\electron0lobby\app.spec.js.autogenerated
```

I believe it has something to do with generate_spec_import.js

my autogenerated contains files like:

```
import "./c:/Users\test\electron-lobby\app\frontend\lib\asInterface.spec.js
```

notice how the slash direction alternates.

**Comment by szwacz** [comment]
Hmm, can you do `npm list fs-jetpack` and make sure you have version 0.9 installed?

**Comment by leshow** [comment]
yes, i do

```
fs-jetpack@0.9.0
```

if I go back to `commit ef82d5d55064d0a089c5bdd9bdb50723afa240c9` it works

**Comment by szwacz** [comment]
Definitley I had problem with that on Windows, and fixed it with this line: https://github.com/szwacz/electron-boilerplate/blob/master/tasks/build/generate_spec_imports.js#L21
Are you sure your line looks the same?

**Comment by leshow** [comment]
I do have that line, yes. However it the last \ in deep folders doesn't get replaced (my folder structure has another nested dir on top of yours)

replacing that line with this:
```
return 'import "./' + path.split('\\').join('/') + '";';
```

however, works.

**Comment by szwacz** [comment]
@leshow I'm not sure I follow. Could you paste here an example of path which fails?

**Comment by leshow** [comment]
I have pasted a path in the post where I commended on the jetpack version.
```
import "./frontend/lib\asInterface.spec.js"
```

is an example of one of my paths in the spec.autogenerated.js before I made the aforementioned change.

**Comment by szwacz** [comment]
Oh god, I forgot how string replace works. Now it should be ok: https://github.com/szwacz/electron-boilerplate/commit/fcc2327c5580ee406c50e5cb2888a049666cdf27

**Comment by leshow** [comment]
thanks
