### ISSUE TITLE
Do you have any interest in ES6 version of electron boiler-plate?

### ISSUE THREAD

**Issue by adriatic** [szwacz/electron-boilerplate#160]
Hi Jakub

I looked around for a long time trying to find electron boilerplate and in my opinion you wind easily. So, I wanted to tell you that we (group of [Aurelia](aurelia.io) community members, organized as Aurelia-UI-Toolkits / Aurelia-Tools) plan to adopt it as the base for all of our Electron based projects.

I wonder whether you would care to be an "advisor" to our team in our early days with Electron?

Regards

Nikolaj Ivancic

**Comment by szwacz** [comment]
Thank you for your kind words. Unfortunately I don't have enough time to do all things I should be doing, not to mention taking participation in more projects :).
Wish you all the best with your project.
