### ISSUE TITLE
Debugging the boilerplate code in visualstudio code

### ISSUE THREAD

**Issue by rohit-lakhanpal** [szwacz/electron-boilerplate#161]
Not sure if this is the correct forum to ask this question, but is there a way to run the app using visual studio code? I like the ability of easily debugging my electron code with visual studio code. 

So far I've added a launch.json file and added a runtimeExecutable as well as specified the program.
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/app/background.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": "${workspaceRoot}/node_modules/electron-prebuilt/dist/electron.exe",
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "externalConsole": false,
            "sourceMaps": false,
            "outDir": null
        },
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": false,
            "sourceMaps": false,
            "outDir": null,
            "localRoot": "${workspaceRoot}",
            "remoteRoot": null
        }
    ]
}

```

**Comment by JimmyBoh** [comment]
I was able to get that working, check out [my `launch.json` here](https://github.com/JimmyBoh/super-conductor/blob/master/.vscode/launch.json).

**Comment by rohit-lakhanpal** [comment]
Dang it! Does not seem to be working for me when I use the "Debug - Npm Start" from your launch.json options. Does not throw any errors but the electron window does not open. Am I missing something?? 

Ran the npm install before I tried to debug (in case you were wondering).

Here's a zip of the boilerplate with your launch.json.

I really appreciate your help. :)

[electron-boilerplate-master.zip](https://github.com/szwacz/electron-boilerplate/files/285986/electron-boilerplate-master.zip)

**Comment by JimmyBoh** [comment]
@rohit-lakhanpal Do you know which version of the boilerplate you are using? The version I have was from late February 2016, and it looks like things have changed quite a bit ([mine](https://github.com/JimmyBoh/super-conductor/blob/master/tasks/start.js) vs [current](https://github.com/szwacz/electron-boilerplate/blob/master/tasks/start.js)).

**Comment by rohit-lakhanpal** [comment]
Any luck Jimmy? I'm hoping to have this resolved by July so that I can use it on my next project.

**Comment by JimmyBoh** [comment]
I haven't tried yet. Hopefully this weekend I can finally get it set up and started!

![PCkcS10XqAoBa](https://camo.githubusercontent.com/4668af37d45c16fc61f814aad9c5a54baa7fb3b7/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f50436b635331305871416f42612f67697068792e676966>)

**Comment by rohit-lakhanpal** [comment]
I got this working using a launch.json & a task.json (for my preLaunchTask)

My launch.json is as follows:
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/build/background.js",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": "build",
            "runtimeExecutable": "${workspaceRoot}/node_modules/electron-prebuilt/dist/electron.exe",
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "externalConsole": false,
            "sourceMaps": false,
            "outDir": null
        },
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": false,
            "sourceMaps": false,
            "outDir": null,
            "localRoot": "${workspaceRoot}",
            "remoteRoot": null
        }
    ]
}`

And my task,json is as follows:
`{
    "version": "0.1.0",
    "command": "gulp",
    "isShellCommand": true,
    "args": ["build"],
    "showOutput": "always",
    "tasks": [
        {
            "taskName": "build",
            "isBuildCommand": true
        }
    ]
}`

Thanks for your help tho. :)

**Comment by rohit-lakhanpal** [comment]
@szwacz can you mark this issue as resolved? Think my solution works.
