### ISSUE TITLE
[Discussion] CLI Version for easier boilerplate updates

### ISSUE THREAD

**Issue by JimmyBoh** [szwacz/electron-boilerplate#162]
I'm loving the boilerplate, excellent work @szwacz! The only downside with any "clone-and-rename boilerplate" is that pulling in updated versions is usually kinda a pain. Has there been an effort/consideration into making a CLI tool that achieves the same result?

I know that flexibility is always important, so having the ability to modify gulp tasks, add new ones, etc is important, which makes a standalone tool difficult. Maybe this is something Yeoman could handle? Does someone have a method/setup that minimize the upgrade issues? Please share!

**Comment by JimmyBoh** [comment]
I did see [this on SO](http://stackoverflow.com/a/18500003/1654818), so yeoman might be a good approach (with two repos, one for the boilerplate, another for the generator that spits out the boilerplate).

**Comment by leshow** [comment]
I've got a fairly large project based off of this boilerplate personally I think you're better off with cloning and then deleting the files you don't need, along with maintaining a branch that is the upstream version of this boilerplate so you can merge back in any changes.

I have been keeping my project up to date with this boilerplate for over a year, and that process works very well.

**Comment by szwacz** [comment]
Thanks for your kind words.

I'm not a yeoman user so can't bring any valuable input to this discussion. But for sure will try out and link in readme any cool third party project which builds on top of this boilerplate :)

**Comment by JimmyBoh** [comment]
@leshow That's a really good idea, making a dedicate branch to being the unmodified boilerplate, then simply merging them when a new update comes out. Thanks for sharing!

**Comment by JimmyBoh** [comment]
Maybe this might work? https://github.com/addyosmani/generator-boilerplate
