### ISSUE TITLE
How do you access values from the config files?

### ISSUE THREAD

**Issue by scotttrinh** [szwacz/electron-boilerplate#163]
The documentation mentions the config files, but I can't quite seem to figure out how to access the values, either at compile time, or at runtime. Am I missing something obvious?

**Comment by szwacz** [comment]
There is 'accessor' module: https://github.com/szwacz/electron-boilerplate/blob/master/app/env.js
Wherever you import this module you can use values defined in config file: https://github.com/szwacz/electron-boilerplate/blob/master/app/app.js#L23
