### ISSUE TITLE
ES6 node modules throwing "SyntaxError: Unexpected token export"

### ISSUE THREAD

**Issue by cleverplatypus** [szwacz/electron-boilerplate#164]
Hi, 
Everything working out of the box, great job.

However, I have a few ES6 modules that make the app throw 

```
SyntaxError: Unexpected token export
```
Looks like roll-up is not taking care of modules. 
Am I missing anything?

Cheers

**Comment by szwacz** [comment]
Is there a chance of any code snippet? :)
