### ISSUE TITLE
install-native arguments lost

### ISSUE THREAD

**Issue by t3mulligan** [szwacz/electron-boilerplate#166]
I am on ubuntu 16.04. My issue is as follows.
I want to build sqlite3 from source, using sqlcipher. Per sqlite3 docs, the following works fine outside of electron-boilerplate:
npm install sqlite3 --save --build-from-source --sqlite_libname=sqlcipher --sqlite=/usr/local --verbose

However, I cannot find a good way to do the same thing with the install-native script. I tried:
npm run install-native -- sqlite3 --build-from-source --sqlite_libname=sqlcipher --sqlite=/usr/local --verbose
as well as:
npm run install-native -- sqlite3  --sqlite_libname=sqlcipher --sqlite=/usr/local --verbose
But am not having any luck. I was able to hack it to properly finish the native-install script by putting an if statement and passing in the arguments only when the module name is sqlite3, lol..  The problem is, /app/package.json starts /tasks/rebuild_native_modules which rebuilds sqlite3 from source, without my arguments. I checked out the docs for electron-rebuild but didn't have any luck in figuring this out. Hopefully I'm just overlooking something, but I've tried everything I can think of.  Thanks!

**Comment by szwacz** [comment]
Please try it with this patch: https://github.com/szwacz/electron-boilerplate/commit/4c32397c05f1982ce1e5435ec886c074c4abd4cf

**Comment by t3mulligan** [comment]
Awesome. Worked perfectly. Thanks so much!!
