### ISSUE TITLE
App works when running `npm start`, but hangs when running `npm test`

### ISSUE THREAD

**Issue by Aerlinger** [szwacz/electron-boilerplate#167]
When running `npm test` the tests and electron-boilerplate application hang indefinitely. The electron icon shows up in my dock, but cannot be interacted with or closed unless I do a `kill -9`. I have a fresh install of electron-boilerplate (built from commit `fcc2327`) and no files have been changed. 

Here is the output I see:

![image](https://cloud.githubusercontent.com/assets/604138/15665192/79cb9aee-26d7-11e6-9640-70a77cb5f6be.png)

And here is a sample of what I see when running `ps aux | grep electron` before force-killing the application (I deliberately killed the test process after it hung):

```
Aerlinger       12130   0.0  0.2  2764684  16948 s002  S     2:19am   0:00.19 .../electron-boilerplate/node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper --type=gpu-process --channel=12129.0.829256119 --no-sandbox --supports-dual-gpus=true --gpu-driver-bug-workarounds=14,16,30,35,48,49,50,54,56,64,65,70,73 --gpu-vendor-id=0x10de --gpu-device-id=0x0fd5 --gpu-driver-vendor --gpu-driver-version
Aerlinger       12129   0.0  0.5  3423440  41452 s002  S     2:19am   0:00.80 .../electron-boilerplate/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron .../electron-boilerplate/node_modules/electron-mocha/index.js build --renderer
Aerlinger       12128   0.0  0.1  3070024  10384 s002  S     2:19am   0:00.08 node .../electron-boilerplate/node_modules/.bin/electron .../electron-boilerplate/node_modules/electron-mocha/index.js build --renderer
```

Environment:
Mac OSX El Capitan
node 6.2.0
npm 3.8.9
All project files are on a local drive

**Comment by scotttrinh** [comment]
Did you update to electron-prebuilt@1.2.0 by any chance? See this issue in `electron-mocha`:

https://github.com/jprichardson/electron-mocha/issues/66

**Comment by szwacz** [comment]
Release of Electron 1.2.1 fixed the issue.
