### ISSUE TITLE
Environment variables in test environment reading wrong package.json

### ISSUE THREAD

**Issue by scotttrinh** [szwacz/electron-boilerplate#168]
I added a quick `console.log` to my env.js to see why it wasn't picking up my environment variables in my test runs (it *is* working for `npm start`), and I get this path from `app.getAppPath()`: 

```bash
~/projects/desktop-uploader2/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app.asar/package.json
```

I'm sure this is something I'm doing wrong in the setup, but I can't quite figure it out. Any tips?

**Comment by szwacz** [comment]
(face palm) It won't work after the project switched to electron-mocha. Will deliver fix shortly.

**Comment by scotttrinh** [comment]
Aww man, I was hoping it was something I could easily fix. :) In the meantime, if anyone else runs into this issue, I'm working around it by putting my test values as the `else` in a ternary. Like:

```js
const APP_ID = env ? env.APP_ID : 'TEST_APP_ID';
```

**Comment by leshow** [comment]
this issue also breaks any tests that rely on app.getAppPath(), I worked around it by explicitly calling setPath in my beforeEach()

**Comment by szwacz** [comment]
For now did dirty hack: https://github.com/szwacz/electron-boilerplate/blob/master/app/env.js
I'm not pleased with this solution and will try to make test build process slicker.

@leshow can you give an example of use case where getAppPath is needed in tests?

**Comment by leshow** [comment]
I test the app path because my app path is set dynamically from a config file. 

Also if you have any functionality that reads/writes files to the app path, it's nice to have it covered by tests.

**Comment by scotttrinh** [comment]
@szwacz any reason we don't just read directly from the `env_*.json` file in all cases instead of writing them to `package.json`? That doesn't fix @leshow's issue, but it should clean up the logic in `env.js`, no? I'd be happy to put a PR together for that.

Also, this is totally just my opinion, but @leshow: do you think you could get away with mocking/spying instead of actually writing to the filesystem in your tests? Or maybe you're just checking that some call you're making in the code is calling the correct directory when it's trying to write? If so, I would think that `getAppPath` is giving you the "correct" path if the function under test is using the same function to build its path?

**Comment by leshow** [comment]
@scotttrinh Maybe, I hadn't really thought of that. I have a filesystem interface that reads/writes keys to a config.json in the app dir, my tests check that the interface works correctly. In previous versions (before electron-mocha) the app path would be set automatically to 'appname-test', so all of the tests worked properly and were contained in that tests dir.

**Comment by szwacz** [comment]
@scotttrinh was thinking of just reading jsons, but this solution isn't much simpler. You need to ship the json file with distributable application. The best option would be to just inline the variables into env.js file. But haven't done reserch on this area yet.

@leshow aren't we confusing here `app.getAppPath()` and `app.getPath('appData')`. App data is the path where you should store your config files, and electron-mocha gives you temporary one (what is even better for tests).
