### ISSUE TITLE
How do I make this boilerplate responsive?

### ISSUE THREAD

**Issue by mamarilmanson** [szwacz/electron-boilerplate#169]
I've tried to integrate bootstrap without success... I tried require() from the getbootstrap website and the conventional <link> and <script> tag... 

or are there any other way of making a responsive electron app? Thanks...

**Comment by szwacz** [comment]
CSS part of electron app (hence this boilerplate) is completely the same as in any other website so the same techniques can be used. The easiest way would be probably to load bootstrap via npm to your project: https://www.npmjs.com/package/bootstrap and then add to `index.html` standard declaration `<link href="node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet">`

**Comment by mamarilmanson** [comment]
oh... ok... I'll try... thanks... :)
