### ISSUE TITLE
exposing modules to the global namespace

### ISSUE THREAD

**Issue by leshow** [szwacz/electron-boilerplate#17]
I'm trying to expose a module imported in app.js:

```
import * as asInterface from './fontend/lib/asInterface';
```

in my app.html i have:

```
requirejs(['app'], function(app) {
window.app = app;
});
```

however app here is undefined, i imagine because app.js doesn't have a return value.

How do I modify the gulp task or project so that I can export an es6 module i've written to the global namespace?

**Comment by szwacz** [comment]
I don't see direct way to do it, but should be easy with:
```js
import * as asInterface from './fontend/lib/asInterface';
_.extend(window, asInterface);
```
BTW, what you are trying to do is probably a code smell ;)

**Comment by leshow** [comment]
I understand, it's due to actionscript's externalinterface for executing javascript code and this is the only option I've got.

Thank you for your time, quick follow up question, with the esperanto gulp task can you write full es6 syntax? I had an arrow function in app.js that failed to build. is esperanto only for es6 modules?

**Comment by szwacz** [comment]
Esperanto does only modules. You might want to replace it with Babel to have all of ES6.
