### ISSUE TITLE
[Discussion] Typescript capable?

### ISSUE THREAD

**Issue by JimmyBoh** [szwacz/electron-boilerplate#170]
Has anyone been able to use TypeScript within the boilerplate? I started using it for a client project and was amazed at how awesome it has been (that and Angular 2 is terrible in regular JS). 

I'd really like to use it directly within this boilerplate, but my initial tests with [`rollup-plugin-typescript`](https://github.com/rollup/rollup-plugin-typescript) were not successful (something about failing to load `null` paths). If I can't get it working, then I figured I would just create the base library/app and the desktop version in different repositories (and the app framework would just be a dependency of the desktop UI).

Thoughts?

**Comment by woooha** [comment]
I have add a basicly Angular 2 support for this project in https://github.com/woooha/electron-boilerplate .

Hope this could help you ~

**Comment by pkunze** [comment]
I'd like to know @szwacz's opinion in this. Other than the gulp task and filenames, everything could stay as it is, since typescript is a superset of js, which basically means, you wouldn't have to change the codebase (besides compilation)... Typescript support would be kindo of optional since you can write regular JS in TypeScript.

**Comment by OwenBrotherwood** [comment]
@JimmyBoh Can you check if an "asar": false helps with null paths?
https://github.com/szwacz/electron-boilerplate/issues/228

**Comment by szwacz** [comment]
@pkunze I don't think I can bring something valuable to this conversation :) Never used TypeScript myself. But... build process here is just a rollup config, so rollup plugin for typescript should do fine. If there are problems with compiling typescript, those are most certainly bugs withing rollup or rollup plugins (which still exist, because it's very a young ecosystem).

**Comment by JimmyBoh** [comment]
@OwenBrotherwood For now I am working on other projects, but I will return to my Electron apps later in the winter. I will be sure to let everyone know here how it goes!

**Comment by msroberts** [comment]
I got this working: https://github.com/szwacz/electron-boilerplate/compare/master...msroberts:typescript

Tests still don't work though.

**Comment by iwasrobbed** [comment]
Could just use https://github.com/electron/electron-compile instead

**Comment by szwacz** [comment]
New face-lifted boilerplate uses webpack instead of rollup and gulp. TypeScript integration should now be much easier.

**Comment by oparisy** [comment]
Indeed I have been able to port the sample application provided with `electron-boilerplate` to TypeScript without too much difficulties.

Test suites pass (`unit` and `e2e`), and `npm run start` / `npm run release` work.

Most adjustments I had to do were type precisions/casts (as could be expected), and minor `import` syntax adjustments.

The only place where I deviated from the existing code was `import env from "env"`, which I had to replace by `const env = require("env")`.

Now @szwacz I would like to share this. I consider two options: either creating an `electron-boilerplate-typescript` repo, and clearly stating on its `readme` that it is a derivative of your work; or submitting to you a PR for a `typescript` branch. I'm afraid the second option will make this work harder to find, though.

What are your thoughts on this?

Regards,
Olivier.

**Comment by black-snow** [comment]
Unless szwacz want to add an optional ts support I'd recommend a fork. Branches are, indeed, almost invisible on github.
Thanks for your efforts!

**Comment by oparisy** [comment]
@black-snow thanks for your comment, which raises an interesting point: some of the modifications I had to do (to package.json or the webpack config as an example) are needed for TypeScript support, but are compatible (ignored) with a JavaScript code base.

Should it be deemed desirable for this project to officially offer some TypeScript support, I could then do the following:
  * post a PR for JS-compatible adjustments,
  * fork once the PR is accepted to provide an example of a TS code base.

Would that be acceptable?

Regards,
Olivier.

**Comment by oparisy** [comment]
Following the discussion above, I built the #296 pull request providing TypeScript compilation and packaging support. 

The point of this PR is that the only modification remaining for a TypeScript developer to perform on `electron-boilerplate` is to change `build/webpack.app.config.js` to point to his TypeScript "entry" code.

Existing `npm` tasks show no regression on the existing Javascript "Hello World" application. Please have a look at the PR and its description for further details.

I demonstrated the use of those TypeScript capabilities by porting the "Hello World" sample app provided with `electron-boilerplate` fully to TypeScript, and ensuring that all `npm` tasks above still work as expected on this new code base.

I am providing this demonstration port at [oparisy/electron-boilerplate-typescript](https://github.com/oparisy/electron-boilerplate-typescript).

Regards,
Olivier.
