### ISSUE TITLE
Code sign for Windows

### ISSUE THREAD

**Issue by sdbarrington** [szwacz/electron-boilerplate#173]
HI, thanks so much for this! Is there a way to code sign the app build and installer for windows?

**Comment by makkesk8** [comment]
I signed both the installer and the app build using gulp.
**Note:** this was done a long time ago and I was using node-webkit at the time, however the process should be the same.

```
gulp.task('sign:build', function() {
  return shelljs.exec('"./assets-windows/signtool.exe" sign /v /d {NAME_OF_APP_HERE} /f "{PFX_CERT_HERE}" /p {PASSWORD_OF_CERT_HERE} /tr "{TIMESTAMP_SERVER_URL_HERE}" "{APP_HERE.EXE}"');
});

gulp.task('sign:installer', function() {
  return shelljs.exec('"./assets-windows/signtool.exe" sign /v /d {NAME_OF_APP_HERE} /f "{PFX_CERT_HERE}" /p {PASSWORD_OF_CERT_HERE} /tr "{TIMESTAMP_SERVER_URL_HERE}" "{INSTALLER_HERE.EXE}"');
});
```

To sign you just execute each at the appropriate place. For instance, When we have just built the exe and its about to be packed into the installer, We execute the ```sign:build``` task. And once its been packed, we execute the ```sign:installer``` task. 

**Note:** This works only for windows and I assume you have signtool already.

**Comment by develar** [comment]
Obsolete since electron-boilerplate uses electron-builder.
