### ISSUE TITLE
Sign running app

### ISSUE THREAD

**Issue by matiastucci** [szwacz/electron-boilerplate#177]
I'm implementing the `autoUpdater` module but when I run the app doing `npm start` I get: `Error: Could not get code signature for running application`.

I know I can sign the app for a release but is there a way to sign the **running** version?

Thanks!

**Comment by black-snow** [comment]
Not sure I'm getting you. Whether or not the app is running, if it's signed it's signed.
Please tell us exactely what you did, what you expected and what happened actually. Also your OS etc.

**Comment by matiastucci** [comment]
I want to sign the app, in order to use `autoUpdater`. I know I can do `npm run release -- --sign A123456789` but that's going to sign the release app. What I would like (I'm not sure if it's possible) is to sign the app I run locally for development (doing `npm start`). I'm on OS X.

**Comment by black-snow** [comment]
Sadly I don't have any experience with debugging the `autoUpdater` on Mac OS X (yet). But you should get support at Squirrel's page (you are using squirrel, right?).

**Comment by matiastucci** [comment]
ok, I'll. Thanks!

**Comment by pfrazee** [comment]
@matiastucci how did you end up resolving this? I'm experiencing the same issue

**Comment by matiastucci** [comment]
@pfrazee I didn't 😞 I commented the `import` of `autoUpdater`

**Comment by pfrazee** [comment]
@matiastucci My theories are, either:

 1. I'll need to sign some assets that are used in development, and I haven't found out which ones yet.
 2. The auto-updater will just fail in the development build.

I expect the latter to be the case. I wrapped the `setFeedURL` call in a try/catch, and I'm finishing up the updater code. I'll let you know if my release version works.

**Comment by matiastucci** [comment]
@pfrazee ok, cool. Thanks and good luck!
