### ISSUE TITLE
Cannot find module 'fs-jetpack' from render process when loadURL external

### ISSUE THREAD

**Issue by matiastucci** [szwacz/electron-boilerplate#179]
In `background.js:33` If instead of doing: `mainWindow.loadURL('file://' + __dirname + '/app.html');`
I do `mainWindow.loadURL('http://some-url.com');`

from DevTool's console I can't do: `var jetpack = require('fs-jetpack')`. I get `Cannot find module 'fs-jetpack'`.

I'm not sure if that's an error or if it's "ok" to be happening. Any ideas?

Thanks!

**Comment by black-snow** [comment]
Works fine for me. Did you actually `require('fs-jetpack')`?

```javascript
const jetpack = require('fs-jetpack')
console.log(jetpack.cwd('.').path())
```

**Comment by blainesch** [comment]
I also can't find the module when loading an external url. I tried http/https and tried ensuring a few options were defaulting correctly.

~~~diff
diff --git a/app/background.js b/app/background.js
index a0702c8..e9dc6bc 100644
--- a/app/background.js
+++ b/app/background.js
@@ -30,7 +30,11 @@ app.on('ready', function () {
         height: 600
     });

-    mainWindow.loadURL('file://' + __dirname + '/app.html');
+    mainWindow.loadURL('https://google.com', {
+        nodeIntegration: true,
+        webSecurity: false,
+        allowRunningInsecureContent: true,
+    });

     if (env.name !== 'production') {
         mainWindow.openDevTools();
~~~

This might be more of an electron issue then the boilerplate.

**Comment by szwacz** [comment]
Indeed this doesn't work. You can require built-in modules like `fs` though, so this is not security constraint. Looks like an Electron bug. Nothing I can do about it.

**Comment by matiastucci** [comment]
ok, I'm not crazy then. Thanks!

**Comment by black-snow** [comment]
Oh, I didn't see that. @matiastucci have you filed a bug report?
