### ISSUE TITLE
Grunt task to minify code on release

### ISSUE THREAD

**Issue by lordminor** [szwacz/electron-boilerplate#182]
Hi!

Is possible to minify the files (js, css) via release? How can I add a task to do it? because to make the installer all the files are copy into a temporary folder and then packed into .asar file, and compiled into the nsi installer... I need to minify the javascript before pack to asar.

Thanks in advance!

**Comment by black-snow** [comment]
You could either add another task (gulp btw) or add you own subroutines to `tasks/build/build.js`.
I didn't go through the code but you should check if it's not being done already somewhere :)

**Comment by blainesch** [comment]
I'm unsure why you'd want to minify it. Electron boilerplate without any additional code is 42mb, and you have to download it all at once, so adding one more mb isn't going to add much more overhead, and it'll be much easier to debug unminified code.

**Comment by tysenmoore-xse** [comment]
Would be useful to obfuscate your code.

**Comment by szwacz** [comment]
You would need to edit this file: https://github.com/szwacz/electron-boilerplate/blob/master/tasks/build/bundle.js#L40 and add uglifier there. BTW, if you want to protect your code not generating sourceMaps (or not shipping them with bundle) would be probably also a good idea.
