### ISSUE TITLE
windows-7-32

### ISSUE THREAD

**Issue by gbaumgart** [szwacz/electron-boilerplate#184]
hi, 

i build the first time on windows-10 - x64 with visual studio - 2015, and an older fork of yours : when running the exe on windows-7-32, its complaining that its not compatible. 

Is there are a way or trick to make it work on both or do i really need to build for both ? building on windows - 7 works on both...
any idea ?

**Comment by gbaumgart** [comment]
problem is : that we are now forced by the node-js developers to update to node.js 4.4.7 which opens a set of new problems: no support for vs2012, etc...
g

**Comment by szwacz** [comment]
You mean you want to build 32bit on 64bit system? If so it's described in readme. If that trick doesn't work you can also try https://github.com/szwacz/electron-boilerplate/issues/30

**Comment by gbaumgart** [comment]
thanks Jakub, gonna try that.
