### ISSUE TITLE
excluding some files from deletion in build folder

### ISSUE THREAD

**Issue by jorfermo** [szwacz/electron-boilerplate#193]
How can I exclude some files from deletion after every npm start in build folder?

I have settings file there that I'd like to keep among runs

Thanks!

**Comment by szwacz** [comment]
Knowing your exact motivation will help here. Do you want to save on build time or something different?

**Comment by jorfermo** [comment]
I'm using nconf to save some application settings. Those settings are saved in __dirname + something

After every rebuild those settings are lost. That's why I'm asking how to avoid that file to be erased after every npm start.

**Comment by szwacz** [comment]
Are you sure you need to keep data next to your JS files? It's bad practice. There are special places for data: http://electron.atom.io/docs/api/app/#appgetpathname

**Comment by jorfermo** [comment]
wow! It really makes sense, I didn't know about it. I'll give it a try.

Thanks for the hint!
