### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by black-snow** [szwacz/electron-boilerplate#198]
I'm falling into the *"module version mistmatch"* -pit quite often.

```
App threw an error during load
Error: Module version mismatch. Expected 49, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:167:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:167:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    ...
```

Usually happens after `cd`'ing into `app` and `npm install`. Can we avoid this somehow?

Quick fix could be not to `cd` into `app` but to manually add the new dependency to `app/package.json` and do a `npm install` from top level.

I don't know why this happens exactly. *Afaik* this error pops up when you `npm i` a dependency and then run it with another node version but that shouldn't be the case here. Or is it? (for electron using a different node version then `npm i` does?)

Or am I just too stupid to do this right? ;)

After deleting both `node_modules` folders and `npm install` my app starts up again just fine. Also happens on `npm test` from time to time.

**Comment by blainesch** [comment]
The correct solution might be to pin the node version with a `.nvmrc` file. We could use the same node version as electron, which of course changes. I'm usually against pinning such a specific version, but this might be a good exception. Currently it's `6.3.0`

**Comment by black-snow** [comment]
*Afaik* we already pinned the electron version (1.3.3 currently, too lazy to look it up) so pinning a node version might not be too bad at all. But I gotta say that I don't know much about any (other) implications that might bring along.

**Comment by blainesch** [comment]
I do it on my project that started from this boilerplate, although they have greatly diverged, I never ran into any issues.

**Comment by szwacz** [comment]
I assume we're talking only about native modules here. Right?
This should be handled by electron builder via `"postinstall": "install-app-deps",`, but as you noticed only with `npm install` launched from root folder.

Maybe you may try adding this to `app/package.json`?
```
"postinstall": "cd .. && install-app-deps",
```

**Comment by szwacz** [comment]
Or rather:
```
"postinstall": "cd .. && node_modules/.bin/install-app-deps"
```

**Comment by blainesch** [comment]
That would require doing another `npm install` which already fixes the issue though, right?

**Comment by szwacz** [comment]
Gosh! It's always something...
You're right, `postinstall` doesn't start for `npm install some_package`. So I'm out of ideas for now.

**Comment by black-snow** [comment]
Why doesn't postinstall fire on `npm i`? o.Ó

**Comment by szwacz** [comment]
Was kind of surprising for me as well, but it actually makes sense. `postinstall` is hook for when 'the package' has been installed (in this context 'the package' means boilerplate), **not** when some dependency of 'the package' has been installed.

I'm afraid this problem doensn't have neat solution for now. There is no suitable npm hook.

@black-snow But the example you're giving about `cd app` and `npm install` should be mitigated by the postinstall line I wrote in one of previous posts.

**Comment by tysenmoore-xse** [comment]
I'm not sure of this is the same problem but using the 1.3.0+ of the `electron-prebuilt` will trigger this problem.  v49 of the ABI is not even available publicly at this point.  They are aware of the problem.

**Comment by develar** [comment]
Electron-builder should provide special script to install new npm dependency. Or somehow inject proper configuration for npm. PR welcome.

**Comment by black-snow** [comment]
Sadly calling `node_modules/.bin/install-app-deps` manually after installing a new dependency didn't help.

**Comment by develar** [comment]
> Sadly calling node_modules/.bin/install-app-deps manually after installing a new dependency didn't help.

Because `install-app-deps` calls `install`, but not `rebuild`. And npm doesn't detect that module must be rebuild because configuration was changed.

Something like https://github.com/electron-userland/electron-builder/issues/683#issuecomment-241488783 should be added, as already stated.

**Comment by black-snow** [comment]
`nodeGypRebuild` shoul fix this. Closing the issue.

**Comment by szwacz** [comment]
I've added extra paragraph in readme to bring some attention to the problem: https://github.com/szwacz/electron-boilerplate/commit/6d9801d54474a89ccfbb82f70251edfd877550d5

**Comment by develar** [comment]
@szwacz electron-builder 8+ doesn't rebuild dev deps anymore. Only and only production dependencies will be rebuild. It doesn't matter for electron-bolilerplate — because you use two-package.json structure (it is not required anymore since electron-builder 8). Please see https://github.com/electron-userland/electron-builder/issues/906 

I don't understand "`npm install name_of_npm_module` to rebuild the module for Electron." Why? If user will invoke this command from terminal, it will be built for node version, not for electron. Right?

**Comment by szwacz** [comment]
@develar Ha! Interesting news. I'll definitely play with one package.json architecture in incoming weeks. As always thanks for keeping me informed! Electron-builder becomes really awesome piece of engineering :)

> I don't understand "npm install name_of_npm_module to rebuild the module for Electron." Why? If user will invoke this command from terminal, it will be built for node version, not for electron. Right?

Right! And this is not what I wanted this sentence to say (I constructed this sentence wierdly, will rewrite it). What I wanted to say is that when you want to install fresh module `npm install some-native-module` and want to use it in electron you can't just after installing start the app because the new module wasn't rebuild yet. In order to be rebuild  you need to launch `npm run postinstall` what is a hook to `install-app-deps`. Right?

**Comment by develar** [comment]
> you need to launch npm run postinstall what is a hook to install-app-deps. Right?

Yes. But in this case, I think, it will be better to call `install-app-deps` directly. To reduce magic level and make things a little bit clear.

**Comment by szwacz** [comment]
Right, but it requires `electron-builder` to be installed globally, what I don't want to demand from the users ot the boilerplate (local installation will do just fine).

**Comment by develar** [comment]
`./node_modules/.bin/install-app-deps` can be used. Ok, up to you :)
