### ISSUE TITLE
7zip dependency not available on OSX

### ISSUE THREAD

**Issue by RichLewis007** [szwacz/electron-boilerplate#203]
See warnings when running npm install on a Mac:

npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-win:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-win@1.0.0
npm WARN optional Skipping failed optional dependency /7zip-bin/7zip-bin-linux:
npm WARN notsup Not compatible with your operating system or architecture: 7zip-bin-linux@1.0.2

**Comment by black-snow** [comment]
Probably because it's not needed. Just an optional dep. [See](https://github.com/electron-userland/electron-builder/blob/8f55a2d268f5a72e0b63790bb922a79ea87f6cd4/README.md)

Or is something broken on your machine?

**Comment by develar** [comment]
It is ok. 7zip-bin-win/7zip-bin-linux optional deps because your are on mac :)

**Comment by RichLewis007** [comment]
ok thanks!
