### ISSUE TITLE
Node_modules folder excluded on npm run release

### ISSUE THREAD

**Issue by AmGarera** [szwacz/electron-boilerplate#206]
As the title says when running `npm run release` everything bundles correctly without error minus the dependencies from node not being bundled in the resources folder, is there a step i'm missing to have them automatically put there?

**Comment by blainesch** [comment]
That logic is over here:
https://github.com/szwacz/electron-boilerplate/blob/f0d0b17bac2b80c68bd3b4f92037262e661806c1/tasks/bundle.js#L7-L18

**Comment by AmGarera** [comment]
Right so in theory it should pull the npm dependencies from the package.json because i'm requiring it

**Comment by szwacz** [comment]
The names of modules which @blainesch hilighted are **not** bundled (that's exactly why those are declared there). In older versions of boilerplate the node_modules folder has to be copied via gulp task. In newest version node_modules is already in app folder (which is the source folder for packager) so doesn't need to be copied around.
