### ISSUE TITLE
exec the .exe Error: cannot find module 'fs-jetpack'

### ISSUE THREAD

**Issue by zhangmingze** [szwacz/electron-boilerplate#207]
I had try cd app && npm install, but didn't work.

**Comment by black-snow** [comment]
Please describe your issue. What did you try to do? What did you expect? What happened?

**Comment by szwacz** [comment]
After doing `npm run release` do you have in `dist/win/your_app/node_modules` folder with that name?

**Comment by zhangmingze** [comment]
@szwacz  After doing ```npm run release``` the ```dist``` folder include ```win-unpacked``` and ```Electron Boilerplate Setup 0.0.0.exe```, does it normal?
It seems that pack failed?

**Comment by szwacz** [comment]
The release process looks ok. I was recalling the path from my memory and I remembered it wrong. I wanted for you to check in `dist/win-unpacked/` but I forgot the assets are compressed into `.asar` file so the files aren't visible anyway.

Do you have this issue on fresh clone of boilerplate or in your longer-maintained application?

**Comment by zhangmingze** [comment]
I have this issue on fresh clone of your boilerplate.
I have been used the earlier version of this boilerplate in my application, and I want to use this latest version. The earlier boilerplate worked fine.

**Comment by szwacz** [comment]
I did fresh clone of the project and after `npm install` and `npm run release` everything runs fine. So still can't reproduce. Do you have other machine you can test this on?
