### ISSUE TITLE
[help wanted] testing spec files in /app

### ISSUE THREAD

**Issue by fridgerator** [szwacz/electron-boilerplate#209]
Is it possible to run `*.spec.js` files from with the `app` folder in 4.0 ?

I have front-end logic in the `src` folder, and backend (electron) logic in the `app` folder.

Some of my backend logic is `require`ing node modules (i.e.: `var sqlite3 = require('sqlite3')`), and I would like to unit test these files.

Is this easily possible currently or do I need to come up with my own solution?  Would it be a good practice to stub all `require` calls?

**Comment by szwacz** [comment]
Hi, this should work out of the box if you just add/change `app` folder to those in which spec files are searched for: https://github.com/szwacz/electron-boilerplate/blob/master/tasks/build_tests.js#L26
