### ISSUE TITLE
remove resources/osx

### ISSUE THREAD

**Issue by develar** [szwacz/electron-boilerplate#212]
electron-builder 7.10.3+ uses the same default DMG background as electron-boilerplate — except that no "Electron Boilerplate" label. https://github.com/electron-userland/electron-builder/blob/master/templates/dmg/background.tiff

I suggest:
- remove dir `resources/osx`
- remove `build.dmg` from `package.json`.
- remove `build.mac` from `package.json`

**Comment by szwacz** [comment]
Thanks @develar for letting me know. I can't remove `resources/osx` yet because of `icon.icns` file. Do you have (or heared of) any success in generating icns and ico file via code in build scripts? That would indeed be great simplification.

**Comment by develar** [comment]
Current `icon.icns` is not required any more as well — default electron icon will be used (and warning will be issued, so, user will be aware). It is why I ask/suggest to remove `build.dmg` from `package.json` — no need to complicate config — resources directory is already set to `resources`. So, user just put `background.tiff` and `icon.icns` to `resources`.

> Do you have (or heared of) any success in generating icns and ico file via code in build scripts? 

We already generate icon set for Linux from `icns`. And often it causes problem (because used native `iconutil` is not reliable (latest version of electron-builder uses Apple tool on macOS, so, it is only Linux issue) and pure nodejs implementation is not complete). https://github.com/sonnyp/icns.js/issues/3

Well, we can generate `ico` from `icns`, but I don't think it is worth to do — often it is easy for user to generate both (e.g. using `iConvert Icons` or `AppIcon Generator` apps.

**Comment by szwacz** [comment]
Thanks @develar I followed your advice.

Also renamed the folder `resources` to `build` to make reading electron-builder docs simpler.
