### ISSUE TITLE
Uncaught Error: Cannot find module

### ISSUE THREAD

**Issue by philipptrenz** [szwacz/electron-boilerplate#214]
Hi there, 

I'm trying to use node-opencv with node 6.5.0, Chromium 53.0.2785.113, and Electron 1.4.3.
After getting everything compiled, I tried to get it running (require('opencv')) but the console says:

`module.js:455 Uncaught Error: Cannot find module '/home/philipp/git/smartmirror/node_modules/opencv/build/opencv/v6.0.0/Release/electron-v1.4-linux-x64/opencv.node'
Module._resolveFilename @ module.js:455
Module._resolveFilename @ reset-search-paths.js:35
Module._load @ module.js:403
Module.require @ module.js:483
require @ internal/module.js:20
(anonymous function) @ bindings.js:4
Module._compile @ module.js:556
require.extensions.(anonymous function) @ require-hook.js:17
Module.load @ module.js:473
tryModuleLoad @ module.js:432
Module._load @ module.js:424
Module.require @ module.js:483
require @ internal/module.js:20
(anonymous function) @ opencv.js:6
Module._compile @ module.js:556
require.extensions.(anonymous function) @ require-hook.js:17
Module.load @ module.js:473
tryModuleLoad @ module.js:432
Module._load @ module.js:424
Module.require @ module.js:483
require @ internal/module.js:20
(anonymous function) @ renderer.js [sm]:24
Module._compile @ module.js:556
require.extensions.(anonymous function) @ require-hook.js:17
Module.load @ module.js:473
tryModuleLoad @ module.js:432
Module._load @ module.js:424
Module.require @ module.js:483
require @ internal/module.js:20
(anonymous function) @ index.html:inline_3.js:3`

I'm not sure where to start searching for an solution. Any suggestions?

**Comment by black-snow** [comment]
How does your `package.json` look? Can you find the module in the build folder? Dev mode or release?

**Comment by philipptrenz** [comment]
it's within "dependencies" at my package.json
binaries seem to be "node_modules/opencv/opencv/v6.0.0/Release/node-v48-linux-x64/opencv.node" also in "node_modules/opencv/Release/opencv.node", is that right?

**Comment by szwacz** [comment]
@philipptrenz have you resolved this? If not, are you sure [electron-rebuild](https://github.com/electron/electron-rebuild) had chance to rebuild the code you've installed?

**Comment by philipptrenz** [comment]
Hi, I wasn't aware how to rebuild modules for node for the use in electron, I even wasn't aware there's a difference. I found a way around this issue, so I'll close this. I've not tested if rebuilding would fix this issue, if someone comes across this here, feel free to contact me!

**Comment by chriswininger** [comment]
@philipptrenz What was your workaround? Running into the same issue.

**Comment by chriswininger** [comment]
Ah, tried that electron-rebuild suggestion and followed the instruction at the link https://github.com/electron/electron-rebuild, that fixed it for me. Thanks szwacz. I was not familiar with this tool.

**Comment by gonzaonisimchuk** [comment]
Hi @philipptrenz , how do you fix the problem?

**Comment by philipptrenz** [comment]
Hey,

I found another framework which supports the functionality I need. But take a look at https://github.com/electron/electron-rebuild/ it fixed some issues I had with several dependencies, maybe this will fix it.
