### ISSUE TITLE
Electron-chromedriver

### ISSUE THREAD

**Issue by luccascorrea** [szwacz/electron-boilerplate#216]
Hi, I tried running `npm install` after cloning the repo and I get the following error:

		npm ERR! Darwin 15.4.0
		npm ERR! argv "/usr/local/Cellar/node/5.6.0/bin/node" "/usr/local/bin/npm" "install"
		npm ERR! node v6.8.0
		npm ERR! npm  v3.10.8
		npm ERR! code ELIFECYCLE

		npm ERR! electron-chromedriver@1.4.0 install: `node ./download-chromedriver.js`
		npm ERR! Exit status 1
		npm ERR! 
		npm ERR! Failed at the electron-chromedriver@1.4.0 install script 'node ./download-chromedriver.js'.
		npm ERR! Make sure you have the latest version of node.js and npm installed.
		npm ERR! If you do, this is most likely a problem with the electron-chromedriver package,
		npm ERR! not with npm itself.
		npm ERR! Tell the author that this fails on your system:
		npm ERR!     node ./download-chromedriver.js
		npm ERR! You can get information on how to open an issue for this project with:
		npm ERR!     npm bugs electron-chromedriver
		npm ERR! Or if that isn't available, you can get their info via:
		npm ERR!     npm owner ls electron-chromedriver
		npm ERR! There is likely additional logging output above.

Am I doing something wrong?

**Comment by szwacz** [comment]
You're definitely not doing something wrong. But I have OSX as well, just tried fresh installation and everything worked fine. What's your node version?

**Comment by black-snow** [comment]
Rather sounds like an issue with `eletron-chromedriver` (1.4.0).
