### ISSUE TITLE
can not listen the install/uninstall event

### ISSUE THREAD

**Issue by zhangmingze** [szwacz/electron-boilerplate#219]
```
node: 6.3.1
npm:3.10.3
electron:1.4.4
win10
```
Blow is the code, it didn't work when install the .exe on win10
```
const handleStartupEvent = function () {
  if (process.platform !== 'win32') {
    return false;
  }
  var squirrelCommand = process.argv[1];
  switch (squirrelCommand) {
    case '--squirrel-install':
      ...
      return true;
    case '--squirrel-updated':
      ...
      return true;
    case '--squirrel-uninstall':
      app.quit();
      return true;
    case '--squirrel-obsolete':
      app.quit();
      return true;
  }
}

if (handleStartupEvent()) {
  return;
}
```

**Comment by black-snow** [comment]
"it didn't work" isn't much of an error report. Please show us all the required code parts and tell us what you expected, what you did and what actually happened.
Have you correctly set the _feedUrl_? Do you [correctly handle the events](https://github.com/electron/windows-installer#handling-squirrel-events)?

**Comment by zhangmingze** [comment]
@black-snow I am sorry.Thank you for the ```electron-squirrel-startup``` module

**Comment by black-snow** [comment]
You're welcome
