### ISSUE TITLE
"define is not defined"

### ISSUE THREAD

**Issue by emrerocky** [szwacz/electron-boilerplate#22]
I have a separate js file to control the menu of my app.  Inside the app folder, the file is fine, but when I run npm start, the file in the build folder has a random "define(function () {" added to it, which causes an error and for the file to be ignored.  Is this a bug, or am I doing something wrong?

**Comment by szwacz** [comment]
This define function means that your file has been converted to AMD module (AMD is one of they ways modules in JavaScript can work with each other). In file https://github.com/szwacz/electron-boilerplate/blob/master/tasks/build.js there is code:
```js
var paths = {
    jsCodeToTranspile: [
        'app/**/*.js',
        '!app/main.js',
        '!app/spec.js',
        '!app/node_modules/**',
        '!app/bower_components/**',
        '!app/vendor/**'
    ],
    copyFromAppDir: [
        './main.js',
        './spec.js',
        './node_modules/**',
        './bower_components/**',
        './vendor/**',
        './**/*.html'
    ],
}
```

`jsCodeToTranspile` - those files are converted to AMD modules  
`copyFromAppDir` - those files will be copied without making any changes to them  

This is quite dirty, but the best I came up with. Your menu file should be excluded in `jsCodeToTranspile` with exclamation mark at the front like you see different files doing it there. And at the same time should be included in `copyFromAppDir` section.

Hope that helped.
