### ISSUE TITLE
[enhancement] Upgrade to latest electron version

### ISSUE THREAD

**Issue by black-snow** [szwacz/electron-boilerplate#224]
We should at least have a latest branch w/ electron 1.4.6+ - there've been a couple bug fixes and new features I'd like to have in my apps.

Will work on this & use this ticket to keep track of any issues that occur.

**Comment by szwacz** [comment]
ok, leaving it to you @black-snow ;) But this doesn't sound like a big change. You mean just bump the version of electron dependency or something more?

**Comment by OwenBrotherwood** [comment]
https://github.com/szwacz/electron-boilerplate/issues/232

**Comment by szwacz** [comment]
Done.

**Comment by black-snow** [comment]
Gr8. Didn't experience any issues so far.
