### ISSUE TITLE
How to package with an app icon for linux?

### ISSUE THREAD

**Issue by jwir3** [szwacz/electron-boilerplate#229]
(This is also a [question on stackoverflow](http://stackoverflow.com/questions/40496548/how-can-i-specify-an-app-icon-for-an-electron-app-on-ubuntu-16-04)).
 
I have an electron app, [arbitrator](http://github.com/jwir3/arbitrator). It uses [electron-boilerplate](https://github.com/szwacz/electron-boilerplate) as a base. Within that electron application, I have an icon specified in `resources/icons/512x512.png`. When I run the application using `npm start`, the icon shows up on the Gnome Unity bar.

If, however, I run `npm run release`, and then run `cd dist/linux && ./Arbitrator`, the application runs, but the icon doesn't show up in the Unity bar (just the default icon). Further, if I run the `./Arbitrator` command from the source repository working directory, then it finds the `resources/icons/512x512.png` file and shows it in the unity bar.

Is there a way I can make sure that the icon is shown for the app, regardless of how it's run (it seems to be referencing the path for the icon locally, rather than using the `asar` file for resources).

**Comment by black-snow** [comment]
Taking a quick look at[ electron builder's options](https://github.com/electron-userland/electron-builder/wiki/Options#LinuxBuildOptions) I don't see an icon-option for linux at all.
Guess you should rather post this issue there.

**Comment by jwir3** [comment]
@black-snow Ah... this appears to be electron-userland/electron-builder#498.
