### ISSUE TITLE
Why two package.json?

### ISSUE THREAD

**Issue by f15gdsy** [szwacz/electron-boilerplate#23]
Hi, thanks for the awesome template for me to kickstart electron development!
I have a question that why do you use two package.json, one for development, one for distribution, as package.json already has devDependencies for us to declare development dependencies?

Thanks :)

**Comment by szwacz** [comment]
Hi, I know this is controversial decision but it makde few problems easier to solve, or entirely go away. Now I can recall from my memory two of them, maybe there was more.
1. When you package the app there is no need to add up to size of the app with your dev dependencies, this way those are always not included.
2. If you use native npm modules (which have to be compiled before) in your app those have to be compiled agains electron runtime, not against the node version you have installed on your computer. Thanks to two package.json files this is also easy.

If you can neatly solve this problems and have only one package.json at the same time I'm all years :)

**Comment by f15gdsy** [comment]
Thanks for your reply!
