### ISSUE TITLE
error when "npm run release"

### ISSUE THREAD

**Issue by MasterHK** [szwacz/electron-boilerplate#231]
[npm-debug.log](https://gist.github.com/MasterHK/b96189237013b0b328f9e0bea21b0c98) file

**Comment by MasterHK** [comment]
it's started to error from today!
it was correct but now... :)

**Comment by szwacz** [comment]
Is it vanilla boilerplate or with your own modifications? If the latter does it happen on vanilla boilerplate as well?

**Comment by MasterHK** [comment]
sorry the problem was a [badsector](https://en.wikipedia.org/wiki/Bad_sector) in my hard drive...
everything is working just fine... :)
