### ISSUE TITLE
build.app-category-type is deprecated and not supported

### ISSUE THREAD

**Issue by OwenBrotherwood** [szwacz/electron-boilerplate#232]
`    "app-category-type": "your.app.category.type",
`
https://github.com/szwacz/electron-boilerplate/blob/179a8f4c65c5c8849bac7ac46525931498d2a18c/package.json#L4 will cause problems in the future if the dependancies are changed to new versions.

Use the following key in due course.
`    "app-category": "developer-tools",
`

---

```
Error: build.app-category-type is deprecated and not supported — please use build.mac.category instead
    at Packager.checkMetadata (C:\Users\owen\Source\Repos\ob\microbit-drill\node_modules\electron-builder\src\packager.ts:211:15)
    at C:\Users\owen\Source\Repos\ob\microbit-drill\node_modules\electron-builder\src\packager.ts:93:10
    at next (native)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

```
```

  "devDependencies": {
    "chai": "^3.5.0",
    "electron": "1.4.7",
    "electron-builder": "^8.6.0",
    "electron-mocha": "^3.1.1",
    "fs-jetpack": "^0.10.2",
    "gulp": "^3.9.1",
    "gulp-batch": "^1.0.5",
    "gulp-less": "^3.3.0",
    "gulp-plumber": "^1.1.0",
    "gulp-util": "^3.0.7",
    "gulp-watch": "^4.3.10",
    "istanbul": "^0.4.5",
    "mocha": "^3.1.2",
    "rollup": "^0.36.3",
    "rollup-plugin-istanbul": "^1.1.0",
    "source-map-support": "^0.4.6",
    "spectron": "^3.4.0",
    "yargs": "^6.4.0"
  }

```

**Comment by black-snow** [comment]
When I look at the latest https://github.com/electron-userland/electron-builder/wiki/Options I don't see any `app-category`. Seems like it's been dropped in favour of one `category` per build target.

**Comment by OwenBrotherwood** [comment]
At the moment, my CI's are passing with the fix @ https://owenbrotherwood.github.io/microbit-drill/
https://github.com/OwenBrotherwood/microbit-drill/blob/e4031658bdc9d2782e1456d5d791f6d5f4ee0a0e/package.json#L9 is the "general" category.
I will try and drop it down into the mac area with a commit "now"

**Comment by OwenBrotherwood** [comment]
Both placements seem to pass 
Here is the placement in the current build
https://github.com/OwenBrotherwood/microbit-drill/blob/dbd794bfad193d09651de15eccaf736e2c369125/package.json#L21

Conclussion?  build.app-category-type is deprecated and not supported 
And the placement of app-category does not as yet seem to cause problems, in general or specific build os.
I would suggest keeping in general area of build until more information is available  if the dependancies are changed to new versions.

**Comment by szwacz** [comment]
[According to the docs](https://github.com/electron-userland/electron-builder/wiki/Options#MacOptions) there is no more global "category", you have two independent places where category can be defined - one for mac and one for linux (probably because those are different concepts on both platforms).

I've just removed category key from package json https://github.com/szwacz/electron-boilerplate/blob/master/package.json#L2 and left specifiying this option to the people.
