### ISSUE TITLE
reading in ./app/package.json

### ISSUE THREAD

**Issue by OwenBrotherwood** [szwacz/electron-boilerplate#234]
Hi
I am scratching my head: is there an easy way to read in ./app/package.json?

On npm run, var packageJson = jetpack.read('package.json', 'json'); gives ./package.json
var packageJson = jetpack.cwd(SOMETHING).read('package.json', 'json'); could be an option

Or is some module like ./src/env.js for ./app/package.json necessary?

Br Owen

**Comment by black-snow** [comment]
See https://github.com/szwacz/electron-boilerplate/blob/master/src/app.js

**Comment by OwenBrotherwood** [comment]
var localPackageJson = jetpack.cwd(app.getAppPath()).read('package.json');
seems to give electron when using npm test
npm start seems ok
npm run release seems ok

"I work the problem thru"

```
LOCAL{
  "name": "electron",
  "productName": "Electron",
  "main": "main.js"
}

```

```
import jetpack from 'fs-jetpack'; 

var app = remote.app;
var net = remote.net;

var localPackageJson = jetpack.cwd(app.getAppPath()).read('package.json');
console.log("LOCAL"+localPackageJson);

```

**Comment by OwenBrotherwood** [comment]
Issue is "closed" ie to read the app/package.json, use something like:

```
import jetpack from 'fs-jetpack'; 

var app = remote.app;
var net = remote.net;

var localPackageJson = jetpack.cwd(app.getAppPath()).read('package.json');
console.log("LOCAL"+localPackageJson);

```
However, if one uses npm test and have some very amatuer tests, then "something" causes a problem.
I will work thru the problem.

---
./src/microbit-drill-electron/microbit-drill-electron.js

The highlighted lines do not seem to be used in my very basic test:

https://github.com/microbit-drill/microbit-drill-electron/blob/aaef62b9b194fce42024d95363d1df88244922b4/src/microbit_drill_electron/microbit_drill_electron.js#L9-L10

The function referred to is:

https://github.com/microbit-drill/microbit-drill-electron/blob/aaef62b9b194fce42024d95363d1df88244922b4/src/microbit_drill_electron/microbit_drill_electron.js#L111-L115

And the test is:

https://github.com/microbit-drill/microbit-drill-electron/blob/aaef62b9b194fce42024d95363d1df88244922b4/src/microbit_drill_electron/microbit_drill_electron.spec.js#L12-L24

**Comment by OwenBrotherwood** [comment]
I try and copy the idea behind env.js for a "general solution" and then solve my own problem with tests

https://github.com/microbit-drill/microbit-drill-electron/blob/a084ab97c840efb6386a8555e2e886473a4c5f1d/src/apppackagejson.js

**Comment by OwenBrotherwood** [comment]
https://github.com/microbit-drill/microbit-drill-electron/tree/master/src apppackagejson.js "works" 
ie I altered my code and my npm run test works for my problem test.

At some stage, I will try and make apppackagejson.js to be as elegant as env.js, at the moment it means I have had to add another .gitignore for apppackagejson.js
