### ISSUE TITLE
app.getPath('userData') can give problems with a "productName" that contains "unlawful" characters for a file path

### ISSUE THREAD

**Issue by OwenBrotherwood** [szwacz/electron-boilerplate#236]
app.getPath('userData') seems to return a path based on "productName"

In the case of electron-boilerplate, the "productName" ("Electron Boilerplate") does not give problems, however if "productName" contains "other characters", like ":", the underlying call to write causes an error.

Hmm, "the issue"? 
- "productName" does not seem to be a requirement in package.json, if it is not present, app.getPath('userData') returns a path based on "name": I have to find out what governs the choice of app.getPath('userData').
- "name" could be a better choice for app.getPath('userData') as it always has to be present.
- the error from the underlying write could be better, it does not seem to be handling "other characters" well.

---

Error with console.log and try/catch added to code.
```
app.getPath('userData'):C:\Users\owen\AppData\Roaming\micro:bit drill ePTX (development)
saveState:stateStoreFile:window-state-main.json
saveState:Error: EEXIST: file already exists, mkdir 'C:\Users\owen\AppData\Roaming'

```
windows.js
app.getPath('userData'):
https://github.com/szwacz/electron-boilerplate/blob/6d9801d54474a89ccfbb82f70251edfd877550d5/src/helpers/window.js#L11
write:
https://github.com/szwacz/electron-boilerplate/blob/6d9801d54474a89ccfbb82f70251edfd877550d5/src/helpers/window.js#L73

https://github.com/szwacz/electron-boilerplate/blob/6d9801d54474a89ccfbb82f70251edfd877550d5/app/package.json#L3

Docs for package.json: packageName does not seem to be required.
https://docs.npmjs.com/files/package.json

**Comment by OwenBrotherwood** [comment]
I made an issue @ electron that may be correct in it's analysis of "the issue"
https://github.com/electron/electron/issues/8073

It may mean that some code is needed in electron-boilerplate to avoid bad paths.

**Comment by black-snow** [comment]
Hi,

thanks for your issue. I don't see how this relates to the boilerplate. `app.getPath()` happens inside electron only.
It should be clear that the product name cannot contain all too fancy characters.

**Comment by OwenBrotherwood** [comment]
Fancy characters where once national characters :) https://en.wikipedia.org/wiki/Polish_alphabet 

I continue with looking for what a "productName" must not contain but I doubt there are restrictions as it should be possible to create a product with a name that contains what is normally acceptable, even ":".

I will monitor the electron issue and add a note "here", even if this issue is closed to give a "heads up" that the problem is or is not still something to be aware of.

I may make an extra comment on https://github.com/szwacz/fs-jetpack/issues/32 if I find a piece of code to protect the usage of fs-jetpack when presented with illegal characters for the OS filesystem

**Comment by black-snow** [comment]
To me *fancy* are characters like `:;/\^$~+#` etc. ;)
For the productName is used for paths you probably shouldn't use any characters that cause trouble in any of the OS's filesystems you target. 
I don't think fs-jetpack should bother either. It should be clear that you cannot use paths that your fs doesn't support.
However, thanks for your efforts. :)

**Comment by szwacz** [comment]
Actually I'm surprised by this decission by electron team as much as you are (I thought this is the whole purpose to have both, `name` and `productName`). That being said electron team is locked to this decision. We're talking __serious__ migration headache for everyone to move all data from one directory to the other for all existing electron apps which will be updated/autoupdated.

I don't think elecrton-boilerplate should try to fix this behaviour, because I have a hunch this will lead to more confused than pleased users.

BTW, just so you know there is also option to set electron paths: http://electron.atom.io/docs/all/#appsetpathname-path so you can adjust the name by hand.

**Comment by OwenBrotherwood** [comment]
thanks szwacz, I added the setpathname-path code in background.js, and and assigned the path to be 'appData' with the /app/package.json . name value

(now I just need to find a lowlevel concation of two paths, appData and name, that does not involve just +"\"+ :)

**Comment by black-snow** [comment]
@OwenBrotherwood `path.join` https://nodejs.org/api/path.html#path_path_join_paths

**Comment by OwenBrotherwood** [comment]
I made a one-liner in background.js
https://github.com/microbit-drill/microbit-drill-epxt/blob/09c1bf523f5841d01b3af9658ce8cc35a66fa834/src/background.js#L20

The final version of keeping my test users informed of new releases via github release is also in background.js if you ever need some github centric update that does not use app.js but is kept in the background with helpers

https://github.com/microbit-drill/microbit-drill-epxt/blob/09c1bf523f5841d01b3af9658ce8cc35a66fa834/src/background.js#L7
