### ISSUE TITLE
Files are not copied

### ISSUE THREAD

**Issue by torakiki** [szwacz/electron-boilerplate#237]
Hi, I'm very new to the js ecosystem and perhaps my questions are obvious but I'm having hard time figuring how the Gulp tasks are supposed to work.
From the readme I'd expect that everything I put in my `src` dir is in the end copied into `app`, but if I put a new .js file in my `src` and run `npm run build` the file dosn't appear in the `app` dir, nor does the provided hello_world.js... and I couldn't find in the tasks scripts where this is supposed to happen so my first question is, what am I suppose to do to have a fully synced/working `app` folder?
Second, probably related to the first one.. when I start the application, is the `watch` supposed to keep in sync the whole `app` directory or just `background.js` and `app.js` ?

**Comment by black-snow** [comment]
Quick answer: scripts will be bundled into app.js/background.js where you import them. They won't be copied 1:1 by default. If you need to have a separate file you'll have to add that to the task. Watch should keep everything in sync but I might be wrong. Guess you should just give it a try. Also note that the main/background source can't be kept in sync while the app is running ;)

**Comment by Schultzer** [comment]
@torakiki I think you might be looking for the bundle task in [`build_app.js`](https://github.com/szwacz/electron-boilerplate/blob/master/tasks/build_app.js#L16-L21).

**Comment by black-snow** [comment]
Now I have time for a longer answer.

By default all the scripts that you import/require in your code will be bundled either into `app.js` or into `background.js`. You should take a look at the created `app/background.js` - it's probably not the same as `src/background.js`.

What I do if I really need to bypass the black magic is this:
Open `tasks/build_app.js`, add a new line to the `bundle` task, e. g.:

```javascript
gulp.task('bundle', function () {
    return Promise.all([
        bundle(srcDir.path('background.js'), destDir.path('background.js')),
        bundle(srcDir.path('app.js'), destDir.path('app.js')),
        bundle(srcDir.path('settings.js'), destDir.path('settings.js')), // <<-- the new line
    ]);
});
```

(As long as you don't have too many cycles this should be fine :D)

**Comment by torakiki** [comment]
oh I see now, the `app.js` in app is different from the one in src, so those two are entry points and the `rollup` thingy fetches and copies whatever is needed going down the dependency tree of those two entry points, correct? That's what I was missing, I didn't noticed they are different and I was expecting a 1:1 copy.
Thanks

**Comment by black-snow** [comment]
@torakiki Do you think that this is something we should add to the REAMDE / wiki?

**Comment by torakiki** [comment]
Not sure, it wasn't clear to me at the beginning after reading the README but as I said I'm out of my comfort zone so maybe it's not a lack in the docs.

**Comment by szwacz** [comment]
I've added extra explanation to readme: https://github.com/szwacz/electron-boilerplate/commit/1801aa5cab3157628852d5d40316c4d93d260f12

@torakiki Was that the missing part for you?

**Comment by torakiki** [comment]
Yes, that was it, very clear now
