### ISSUE TITLE
Same project for Mac and Windows

### ISSUE THREAD

**Issue by rajild** [szwacz/electron-boilerplate#24]
Do I need separate project for Mac and Windows?

I am running virtual windows on Mac.  I did following on MAC:

git clone https://github.com/szwacz/electron-boilerplate.git
cd electron-boilerplate
npm install
npm start

everything is fine.  Can run, release.

The same application is not running from windows  (i am using same project that i used to run from mac).  Then I prepare another project for windows and it is running fine.

So,  now i have 2 separate projects.  one for MAC and another for Windows.  Is it really required?  Isn't it possible to release both platform build (Mac and Windows) from single project  (that i am executing from MAC).

**Comment by szwacz** [comment]
I was thinking about it a little and this is hard problem to solve. When you type `npm install` while being on windows electron for Windowsem is downloaded. Now when you switch to OSX you should delete everything from `node_modules` and run `npm install` again, to compile wverything for OSX. And this needs to be done with every OS switch.

For sure you can try to solve this problem for your project, but I imagine the solution would bo so hacky that not appropreate to be incorporated in this project.
