### ISSUE TITLE
App path changed

### ISSUE THREAD

**Issue by black-snow** [szwacz/electron-boilerplate#240]
Just leaving this here for documentation. We had a major version change and this ain't no big deal.

I guess due to switching to the 1-package.json-structure the appPath has changed. Previously I could correctly get the path to some image in `app/images` with:

```javascript
import {app} from 'electron'
import jetpack from 'fs-jetpack'

//...

let appPath = app.getAppPath()
let appFS = jetpack.cwd(appPath)
let imgPath = appFS.path('images', 'icon.png')
```

This pointed to `/path/to/my/project/app/images/icon.png` - now it's pointing to `/path/to/my/project/images/icon.png`.

@szwacz Dunno if we should mind.

**Comment by szwacz** [comment]
Thanks @black-snow added reference to this ticket to release notes https://github.com/szwacz/electron-boilerplate/releases/tag/5.0.0
