### ISSUE TITLE
[Travis] Error: ENOENT: no such file or directory, open node_modules/electron/path.txt

### ISSUE THREAD

**Issue by yannbertrand** [szwacz/electron-boilerplate#243]
I've copied the electron-boilerplate to [my own repo](https://github.com/yannbertrand/youtube-dl-gui). I've then removed the demo tests from it.

[Travis build](https://travis-ci.org/yannbertrand/youtube-dl-gui/jobs/186995404) throws this error:

```
fs.js:557

  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/travis/build/YannBertrand/youtube-dl-gui/node_modules/electron/path.txt'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.<anonymous> (/home/travis/build/YannBertrand/youtube-dl-gui/node_modules/electron/index.js:4:42)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

Is there something I am doing wrong?

**Comment by Schultzer** [comment]
This is not related to the boilerplate.

`Error: ENOENT: no such file or directory, open '/home/travis/build/YannBertrand/youtube-dl-gui/node_modules/electron/path.txt'`

Try to backtrace what you done in the your codebase

Happy New Year 🎉 🍾

**Comment by szwacz** [comment]
@yannbertrand Is this still a problem? 

I'm not fully getting what you did. You,ve deleted demo tests and wrote your own and that where this error happens? Because I believe you need to have some tests to use Travis :) (unless you're using it for multiplatform build)

**Comment by yannbertrand** [comment]
I didn't even create my tests. The thing is that `npm test` is not throwing any error locally even if there is nothing to test (it returns `0 passing (10ms)`).

Travis build which is running `./scripts/travis-build.sh` throws the error above. I have no idea what this path.txt file is 😞

**Comment by szwacz** [comment]
path.txt is some file used internally by electron-prebuilt, there is a lot of issues regarding this file https://github.com/electron-userland/electron-prebuilt/search?q=path.txt&type=Issues&utf8=%E2%9C%93 maybe checking those will help you solve the problem.

**Comment by yannbertrand** [comment]
Tanks for your help 😄

**Comment by yannbertrand** [comment]
It magically started working today.

I'm pretty sure this is related to a [silly `npm install`](https://github.com/electron-userland/electron-prebuilt/issues/76). By default, `electron-boilerplate` asks Travis to cache the `node_modules` folder but if you run into this issue, you'd probably want to deactivate this (see cache in `travis.yml`).
