### ISSUE TITLE
Possibility to detect if app is already installed

### ISSUE THREAD

**Issue by kyvaith** [szwacz/electron-boilerplate#244]
Is it possible to write an override to default NSIS install script, with will detect if app is already installed (in particular version), and if so run it from HDD instead of installing it again? I think most users will install it over and over, instead of launching installed app from desktop shortcut, just because provided exe (installer) works for few seconds installing it and runs app all the time.

Please help, I couldn't find myself out in  NSIS script dialect.

**Comment by black-snow** [comment]
Have you [checked](http://nsis.sourceforge.net/Auto-uninstall_old_before_installing_new) [the](https://nsis-dev.github.io/NSIS-Forums/html/t-268050.html) [interwebs](http://stackoverflow.com/questions/488717/detecting-if-a-program-is-already-installed-with-nsis)?
