### ISSUE TITLE
packaged electron app fails to include dependencies 

### ISSUE THREAD

**Issue by yilunyu** [szwacz/electron-boilerplate#246]
Running npm run release generates a dist folder and I can run the .app file inside. However, bootstrap, jquery and other dependencies in my project are not loaded. I get the following error: 
electron-boilerplate/dist/mac/Electron%20Boile…ate.app/Contents/Resources/app.asar/vendor/bootstrap/css/bootstrap.min.css Failed to load resource: net::ERR_FILE_NOT_FOUND

My package.json looks like this: 

{
  "name": "electron-boilerplate",
  "productName": "Electron Boilerplate",
  "description": "Starter for your Electron application",
  "version": "0.0.0",
  "author": "Mr. Gumby <mr.gumby@example.com>",
  "copyright": "© 2016, Gumby inc.",
  "homepage": "http://example.com",
  "license": "MIT",
  "main": "app/background.js",
  "build": {
    "appId": "com.example.electron-boilerplate",
    "files": [
      "app/**/*",
      "node_modules/**/*",
      "package.json"
    ]
  },
  "postinstall":"install-app-deps",
  "scripts": {
    "postinstall": "install-app-deps",
    "build": "gulp build",
    "prerelease": "gulp build --env=production",
    "release": "build",
    "start": "gulp start",
    "pretest": "gulp build-unit --env=test",
    "test": "electron-mocha app/specs.js.autogenerated --renderer --require source-map-support/register",
    "coverage": "npm test -- -R scripts/istanbul-reporter",
    "pree2e": "gulp build-e2e --env=test",
    "e2e": "mocha app/e2e.js.autogenerated --require source-map-support/register",
    "install": "electron-rebuild"
  },
  "dependencies": {
    "fs-jetpack": "^0.10.2",
    "serialport": "^4.0.7"
  },
  "devDependencies": {
    "chai": "^3.5.0",
    "electron": "^1.4.7",
    "electron-builder": "^8.6.0",
    "electron-mocha": "^3.0.0",
    "electron-rebuild": "^1.5.5",
    "gulp": "^3.9.0",
    "gulp-batch": "^1.0.5",
    "gulp-less": "^3.0.3",
    "gulp-plumber": "^1.1.0",
    "gulp-util": "^3.0.6",
    "gulp-watch": "^4.3.5",
    "istanbul": "^0.4.3",
    "minimist": "^1.2.0",
    "mocha": "^3.0.2",
    "rollup": "^0.36.3",
    "rollup-plugin-istanbul": "^1.1.0",
    "source-map-support": "^0.4.2",
    "spectron": "^3.3.0"
  }
}

My guess is that I need to add some more stuff to package.json. Can someone tell me why this is happening?

**Comment by szwacz** [comment]
And `dependencies` section of your package.json doesn't have packages you've mentioned. I'd advice to add those there.

**Comment by black-snow** [comment]
@yilunyu Be sure to actually save your dependencies `$ npm install package-to-install --save` :)

**Comment by yilunyu** [comment]
I got it thanks so much

**Comment by alexdevero** [comment]
@black-snow your advice saved me. Thank you very much!
