### ISSUE TITLE
extra folder

### ISSUE THREAD

**Issue by xinxiang** [szwacz/electron-boilerplate#247]
Thanks for this great tool. It gets all my work done, except that I need to ship an extra folder containing data and executable files along the app folder. If I put the folder under app, it will be packaged in app.asar. When I run the executables I will get ... resources\app.asar\bin\mycmd" The system cannot find the path specified.
How do I get the extra folder packaged and when installed outside the app.asar on the user's computer like this? Thanks a lot.
```
...\resources\
myfolder\**\*
app.asar
electron.asar
```

**Comment by black-snow** [comment]
Hi,

did you take at look at the [build options](https://github.com/electron-userland/electron-builder/wiki/Options)?

**Comment by xinxiang** [comment]
Yes, extraFiles got what I wanted. Thanks a lot. Should have come here to post the question earlier.
