### ISSUE TITLE
Distribute Cordova project Desktop App prepared using electron

### ISSUE THREAD

**Issue by rajild** [szwacz/electron-boilerplate#25]
Hello;

I'm new to electron and boilerplate.  Earlier i was using nw.js to prepare desktop app of cordova based project.   I am using browser platform as source to prepare desktop app.

I downloaded electron-boilerplate project and run it successfully on my mac.  Now everytime I build / change my project files,   i have to copy this files to electron-boilerplate directory and then have to run it.  Is there any shortcut to do so?  What is the best way to prepare build of my project?  please note that my source directory is different then electron-boilerplate directory.  I am using electron-boilerplate to prepare desktop apps build only.

**Comment by szwacz** [comment]
You can automate the whole process with build scripts which does all those tasks for you. You can look inside folder `tasks` in this project to see how it's done here, this project also copies files around (but internally ofcourse).
