### ISSUE TITLE
Using electron-packager to build for win32 - how to pass params to packager?

### ISSUE THREAD

**Issue by roberttolton** [szwacz/electron-boilerplate#251]
Hi there,

So after reading a few articles on the interwebs, it should be possible to build for Windows on macOS as long as you have `wine` installed. But, I'm struggling to see where in this boilerplate that the project is actually handed off to `electron-packager`? There's no `cli` statement or `packager()` or anything.

Am I missing something? I can't even see where it knows to put things in the `dist` folder..!

**Comment by szwacz** [comment]
This project is using [electron-builder](https://github.com/electron-userland/electron-builder), which I believed was using underneath electron-packager but this is not the case anymore. Anyway here is their documentation on multi platform build: https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build
