### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by xinxiang** [szwacz/electron-boilerplate#253]
Thanks for this great tool. I have got my app packed except one problem after installation: the desktop shortcut icon on Windows. It looks fuzzy. If I do Change Icon, using the same icon file, but at a different location, the icon looks much sharper. I tried one single 256x256 image for build/icon.ico, as well as multiple resolution images for build/icon.ico. Any clue how to improve the icon? Thanks.

**Comment by black-snow** [comment]
Hi @xinxiang 

you should report this issue here: [electron-builder](https://github.com/electron-userland/electron-builder)
We use `electron-builder` for pretty much the whole build process.

Cheers

**Comment by xinxiang** [comment]
Hi @black-snow,

Thanks. The problem is still in my icons. I made another set of icons with different settings, this time the icons look bearable.

Best
