### ISSUE TITLE
Breakpoint works in app but not src

### ISSUE THREAD

**Issue by faultylee** [szwacz/electron-boilerplate#254]
Hi, I'm actually a newbie in electron currently trying out your boilerplate. I've managed to understand the app and background codes, but no much on the bundle/sourcemap part. I do have experience when debugging C# code in Visual Studio. 

For this, I'm using VSCode and node debugger. Current if I set a breakpoint in `src\background.js`, it shows red, but it will not break. If I set it in `app\background.js`, it's also red and it breaks. I couldn't find any clue on why the one in `src` doesn't work. According to https://github.com/Microsoft/vscode-node-debug/issues/127 it's caused by sourcemaps, but source map file generated seems fine. 

Any clue as to what might go wrong or should I create an issue at https://github.com/Microsoft/vscode-node-debug

This is my launch.json
```json
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "cwd": "${workspaceRoot}",
            "preLaunchTask": "build",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
            "runtimeArgs": [
                ".",
                "--enable-logging",
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "sourceMaps": true,
            "outFiles": [
                "${workspaceRoot}/app/**/*.js"
            ]
        },
```

Thanks

**Comment by szwacz** [comment]
Hello, as for my knowledge chrome dev tools debugger is working as expected with sourcemaps. I've never used VSCode, however it might be impossible to debug renderer process in VSCode as this (rather old) post is saying: http://stackoverflow.com/questions/31429394/debugging-electron-atom-script-with-visual-studio-code

**Comment by faultylee** [comment]
@szwacz Thanks for the reply, if sourcemaps is fine, then I'll look deeper into the debugger and VSCode itself.
