### ISSUE TITLE
Import vs. Const Syntax

### ISSUE THREAD

**Issue by tiptronic** [szwacz/electron-boilerplate#255]
<snipped out the rest, because it works as soon as I close the devtools>

**I'm new to electron, so please forgive me, if I ask something stupid**

Is there a certain reason, why you import dependencies like this:

`import { app, BrowserWindow, screen } from 'electron';`

while in the electron documentaion they load everything like this:

`const { app, BrowserWindow, screen} = require('electron')`

...or is it just because of legacy syntax?

**Comment by black-snow** [comment]
@tiptronic 
`import` is the ES6-way of importing modules (see [MDN](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Statements/import)) whereas `require` is the CommonJS-way of doing so.
Also see [this](http://stackoverflow.com/questions/31354559/using-node-js-require-vs-es6-import-export).

There are many more explanations on the web.

**Comment by tiptronic** [comment]
@black-snow Thx for the hint - I was just asking if I missed something critical...

thx for your reply. Much appreciated!

**Comment by black-snow** [comment]
You're welcome :)
