### ISSUE TITLE
Consider separate electron-builder.json

### ISSUE THREAD

**Issue by black-snow** [szwacz/electron-boilerplate#258]
As of electron-builder 11.4 the build configuration doesn't have to be inside `package.json` anymore.
If `build` is not in `package.json` and the config file isn't given via an extra option it will fallback to `electron-builder.yml`, `electron-builder.json` or `electron-builder.json5`.

I embrace this change for I do not want to pollute my package.json with all the build details and I can simply drop the electron-builder.* when building.
I'd like us to change our default to a separate build config file. I'm gonna use `electron-builder.json5` for I can have comments in json5 but I have no strong feelings about the format.

**Comment by develar** [comment]
>  I'm gonna use electron-builder.json5 for I can have comments in json5 but I have no strong feelings about the format.

Under the hood all formats parsed by yaml parser. i.e. `json` file also supports json5 format. But `json5` is better to clearly state that it is json5.

**Comment by black-snow** [comment]
@develar So the file ending is (technically) irrelevant?

**Comment by develar** [comment]
@black-snow Yes. I hope https://youtrack.jetbrains.com/issue/WEB-12776 will be fixed soon, correct file extension is important (because IDE can detect in this case proper file type).

**Comment by black-snow** [comment]
We should upgrade to `electron-builder@18.0.0` to have correct json5 support.
