### ISSUE TITLE
electron-compile

### ISSUE THREAD

**Issue by black-snow** [szwacz/electron-boilerplate#262]
@szwacz have you seen [this](https://github.com/electron/electron-compile)?
Any feelings about this? Haven't tried it, yet.

**Comment by szwacz** [comment]
So please do try it and say how it went :)

My feelings is that this is one of those tools "sper easy to establish simple app, lots of pain if you need something more customized later on".

Also this is quite huge dependency, all those precomiplers for css, typescript, cofeescript, gosh! I know worrying about having 500 dependencies in your project is very passe in 2017, but mentally I'm a cranky old guy, so I do worry ;)

I feel like joining electron-compile is joining new build ecosystem with all its consequences, e.g. babel could fix some bug, but you still need to wait for babel's version bump in electron-compilers, so if the lib will start to be poorly mantained in the future you have a problem.

**Comment by black-snow** [comment]
I fully agree. *IMHO* electron apps are pretty huge already - I wonder how much bigger they gonna be with electron-compile.
I'll give it a shot and report back.

**Comment by black-snow** [comment]
Sadly I don't have had time for this. Closing this for now.
