### ISSUE TITLE
I can create windows installer on OS X, contrary to `README.md`

### ISSUE THREAD

**Issue by tingletech** [szwacz/electron-boilerplate#264]
`README.md` says "You can create Windows installer only when running on Windows, the same is true for Linux and macOS. So to generate all three installers you need all three operating systems."

yet, on OS X, I am able to go `./node_modules/.bin/build -w` and in `dist` I get something that my colleagues on windows are able to install and test (they say it works).

My Linux users just use the command line tools, so I have not tested `./node_modules/.bin/build -l`

So, I am just lucky (like maybe I have no complex dependencies that install shared libraries) and it just happens to work?  Why do you say I need windows to create the windows installer?

**Comment by black-snow** [comment]
@tingletech Actually electron-builder supports building for different platforms. You can also build win installers on linux using wine. I guess our docs are just a little outdated.

**Comment by szwacz** [comment]
Yes, the docs are a bit outdated, but this is more tricky topic.
As you can red in first paragraph of electron-builder docs on the topic: "Don't expect that you can build app for all platforms on one platform". ;)
https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

I've edited this readme part.
