### ISSUE TITLE
Project can not find dependencies

### ISSUE THREAD

**Issue by fangxiang1** [szwacz/electron-boilerplate#267]
Pouchdb can not package into app.asar

![image](https://cloud.githubusercontent.com/assets/19523659/25691991/063eeb84-30d2-11e7-9825-cfbfa4cae138.png)
![image](https://cloud.githubusercontent.com/assets/19523659/25691999/1e0768d6-30d2-11e7-95bd-ad097f104466.png)

**Comment by black-snow** [comment]
I don't even get to install pouchdb on my windows machine xD
Need to install a lot of other stuff first - will report back when I had time for that

**Comment by fangxiang1** [comment]
ok , thx

**Comment by szwacz** [comment]
Just to rule out the simplest things first, [googling didn't help?](https://www.google.pl/search?q=pouchdb+electron+builder&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=xBYMWaabNoWu8wegkIygBg#q=pouchdb+electron)

**Comment by fangxiang1** [comment]
@szwacz nope, I think dependencies are not packaged.
e.g:  i have included ``download``, but the ``download`` are not packaged.

![image](https://cloud.githubusercontent.com/assets/19523659/25737845/7e15a92e-31ac-11e7-83f8-e08fe0e8510f.png)
![image](https://cloud.githubusercontent.com/assets/19523659/25737853/8b5800aa-31ac-11e7-9260-ae8dd460216f.png)

**Comment by black-snow** [comment]
What's the second image supposed to show?

**Comment by fangxiang1** [comment]
Now, I added the ``download `` and ``pouchdb``in the dependencies.  
When implementing ``npm run release``, ``Rebuilding native production dependencies for darwin: x64``.   
I thought the package was successful, but when running the program  

``
**A JavaScript error occurred in the main process**  

Uncaught Exception:
Error: ENOENT, ._download@6.0.0@download not found in /Users/macbook/Documents/git/pos/SparkPos--GP--SSPOS/dist/mac/Sparkpos.app/Contents/Resources/app.asar
    at notFoundError (ELECTRON_ASAR.js:115:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:514:9)
    at Object.Module._extensions..js (module.js:579:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /Users/macbook/Documents/git仓库/pos/SparkPos--GP--SSPOS/dist/mac/Sparkpos.app/Contents/Resources/app.asar/app/main.js:17:18
    at Object.<anonymous> (/Users/macbook/Documents/git/pos/SparkPos--GP--SSPOS/dist/mac/Sparkpos.app/Contents/Resources/app.asar/app/main.js:221:2)``

**Comment by fangxiang1** [comment]
@szwacz @black-snow thx,  
I have solved the problem.

**Comment by black-snow** [comment]
@fangxiang1 How did you solve it? Just so others can profit from your fix.

**Comment by fangxiang1** [comment]
Most of our developers are using ``cnpm``instead of "npm", its a 3rd party open command, but``cnpm ``has a lot of unpredictable mistakes, I  just uninstalled node.js and npm, then its soved. 
 
@black-snow Thank you very much, I am constantly learning！。

**Comment by black-snow** [comment]
Thanks for sharing.
