### ISSUE TITLE
How to create packages for other platforms

### ISSUE THREAD

**Issue by javeedrahman** [szwacz/electron-boilerplate#268]
Hi Guys,
I have start using boilerplate, my platform was Linux Ubuntu. i want to create a packages and distribution file for all platforms.

when i run --> npm run release i can get the linux AppImage and packages.

But i have given options for windows to load but i didn't get any luck.

"build": {
    "appId": "com.example.electron-boilerplate",
    "category": "com.example.cate",
    "win": {
      "target": ["zip"],
      "signingHashAlgorithms": ["sha256"],
      "icon":"build/icon.ico"
    },
    "files": [
      "app/**/*",
      "node_modules/**/*",
      "package.json"
    ],
    "publish": null
  },

**Comment by javeedrahman** [comment]
Hi @black-snow i am using this, but i am using this boilerplate. want to create packages for other platforms. i am in ubuntu, i have installed wine and mono.

**Comment by black-snow** [comment]
@javeedrahman Hi :) 
Have you read https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build? What's the output when packaging? Guess (if at all) this is rather an electron-builder issue.

**Comment by javeedrahman** [comment]
What's the output when packaging?
It's packaging only my native platform (ubuntu) i am expecting windows NSIS to be built in dist/ folder.

I have installed Wine and Mono,

**Comment by develar** [comment]
Electron-builder will soon offer solution to prebuilt native modules for Windows.

**Comment by black-snow** [comment]
@develar what kind of modules?

@javeedrahman Please file an issue @`electron-builder` and make sure you followed all the steps in the aforementioned link.

**Comment by develar** [comment]
> what kind of modules?

Native modules like keytar, sqlite3.

**Comment by javeedrahman** [comment]
@black-snow okay will confirm the link

**Comment by black-snow** [comment]
@javeedrahman what's the status?
Please close the issue if it's done.

**Comment by javeedrahman** [comment]
As i have go-through, it is best to build the app with the native OS so i am going with that, Hope electron builder multi-platform will work fine but i have not tried, hence closing this issues
