### ISSUE TITLE
NEDB database File is not loading after building in npm run release (Building).

### ISSUE THREAD

**Issue by javeedrahman** [szwacz/electron-boilerplate#271]
Hi Guys,
I am trying to connect NEDB with boilerplate. Its working fine in local (npm start), when i build using npm run release. its showing me the error. Here is the code how i connect.
```
var electron = require('electron');
const app = electron.remote.app;
var userData = app.getAppPath('userData');
db = new Datastore({ filename: userData+'/db/persons.db', autoload: true });
```
Its working when i run npm start. but after building the APP using npm run release
i am getting error in linux and MAC. its only on build.

![errorpath](https://cloud.githubusercontent.com/assets/3214829/26297145/45a44d70-3eef-11e7-942e-077c97ef78dd.png)

In boilerplate, may i know where is main process and render process.
I assume. src is main and app is render.

Thanks in advance.

**Comment by black-snow** [comment]
Hi, thanks for participating in the boilerplate.

> I assume. src is main and app is render.

Nope. Renderer is whatever you include in a browser window and main is whatever you include in your main script (`background.js` in the boilerplate - `package.json`'s `main` points to the file). You can even include the same file in renderer as well as in main. `src` contains stuff that needs to be transpiled. When building those transpiled things will be placed in `app`.

Could you please provide you build config? Also this sounds like an issue w/ `electron-builder`.

How come `/tmp/.mount_xyz/whatever` is your `userData` path? Are you using docker or linux subsystem on windows or something like that?

**Comment by javeedrahman** [comment]
Hi @black-snow Thank you for your valuable response.

This is my mistake. Its working fine now. I have used app.getAppPath() instead of app.getPath('userData')
```
var electron = require('electron');
const app = electron.remote.app;
var userData = app.getAppPath('userData');      <----------------------------- Here i made issues
db = new Datastore({ filename: userData+'/db/persons.db', autoload: true });
```
I have tested the build in MAC, LINUX UBUNTU and WINDOWS. working fine.

Thank You :)

**Comment by black-snow** [comment]
Glad I could help. Please close the issue if it's resolved.

Have a nice week!

**Comment by javeedrahman** [comment]
@black-snow Thank you :+1:
