### ISSUE TITLE
"npm run release" +  "portable exe" + inconsistent __dirname

### ISSUE THREAD

**Issue by distributev** [szwacz/electron-boilerplate#274]
Hello guys,

Do you have any suggestions? I am doing anything wrong here?

https://github.com/electron-userland/electron-builder/issues/1612

**Comment by black-snow** [comment]
Hi

Why do you open another issue here?

**Comment by distributev** [comment]
Sorry - I was not sure if it's an electron-boilerplate or electron-asar or electron-builder situation and who would be most appropriate to take a look at this. I saw people from this project take also good interest in how electron-builder works. Do you see a better approach or work around?

**Comment by black-snow** [comment]
We heavily rely on `electron-builder` thus we participate :)
I'd just say better open an issue where it belongs (i. e. `electron-builder`).

However, thanks for your feedback and for using this boilerplate.

**Comment by develar** [comment]
Close — handled on electron-builder side.
