### ISSUE TITLE
debug script

### ISSUE THREAD

**Issue by black-snow** [szwacz/electron-boilerplate#275]
How do you feel about another script entry in `package.json` called `debug`?

I already have a *dev* script in my main project that sets flags for the `debug` package. I just re-read [this](https://github.com/electron/electron/blob/master/docs/tutorial/debugging-main-process.md) and thought - "Wouldn't it be great to have a debug script that runs electron with `--inspect`?"

**Comment by szwacz** [comment]
Actually never used this feature myself. As I'm reading the docs this is only exposing an interface to which you can connect third party debugger, so adding proposed entry in package.json is not out of the box ready feature, just part of it. If we can provide something that just works with batteries included, then this topic is worth considering :)

**Comment by black-snow** [comment]
Alright. I'm just gonna add another task for my project then.
Thanks for the read.
