### ISSUE TITLE
removing devdeps to reduce bloat

### ISSUE THREAD

**Issue by mmclau14** [szwacz/electron-boilerplate#276]
just wondering if there is anything known about removing devdependencies from the bundle if the app will still work. specifically, it looks like this line
```

const generateExternalModulesList = () => {
  const appManifest = jetpack.read('./package.json', 'json');
  return [].concat(
    nodeBuiltInModules,
    electronBuiltInModules,
    Object.keys(appManifest.dependencies)
    // ,
    // Object.keys(appManifest.devDependencies)
  );
};
```
where i commented out the appMainfest.devDependencies

basically i am using typescript and webpack and it's bundling all of that goodness up inside of the app so i'm trying to bring my app size back down from 250mb+

if there is another way i should be accomplishing this please let me know

**Comment by black-snow** [comment]
What packager are you using? Built-in `electron-builder` shouldn't pack dev deps.

**Comment by mmclau14** [comment]
it's inside `bundle.js`

**Comment by szwacz** [comment]
Question: how did you connect webpack to existing build pipeline? (where did you put it in)

Rollup and Webpack are doing basically the same task, so if you have two in your project... I have no idea what the outcome will be ;)

How I intended it to work here...
1. Rollup bundles all code of which you're the author into JS files, BUT leaves all stuff from `node_modules` not bundled. Electron has working `require()` so there is no gain in bundling stuff from `node_modules` into one js file (only thing you gain that way is very long compilation time).
2. `electron-builder` is very sophisticated tool and while building distributable version of your app it will skip stuff declared in `devDependencies`. So this should be no issue.

The code part you brought up here is a strategy of not bundling `node_modules` by Rollup. If you use Webpack this part is irrelevant to you. Actually you should stop using rollup and use only webpack.

**Comment by black-snow** [comment]
There were some updates in `electron-builder` to address webpack stuff. Please update to the latest version.

Please close this issue if it's done.
