### ISSUE TITLE
How to change the OS ?

### ISSUE THREAD

**Issue by KennyBarraud** [szwacz/electron-boilerplate#282]
Hello !
I'm using recently Electron and this boilerplate.
The setup, i'm looking to create is for a Win32. However I don't know how to change the OS.
Could you explain it to me ?

**Comment by KennyBarraud** [comment]
Never mind ! I find how to do it ! Sorry :p

**Comment by black-snow** [comment]
Glad to hear that. Please close the issue if it's resolved.
