### ISSUE TITLE
The code reset and runs initial version when run npm start 

### ISSUE THREAD

**Issue by akhilsahu** [szwacz/electron-boilerplate#284]
The code reset and no changes are saved on running npm start. App runs with the initial set up provided at the time when no changes were done

**Comment by black-snow** [comment]
Sounds like you edited a generated file within `app` that gets overriden from `src`.

**Comment by akhilsahu** [comment]
The onclick does not work here. Any link or anchor tag or using javascript. It doesnt redirect to other page.

**Comment by black-snow** [comment]
What are you talking about? Please be specific.

**Comment by akhilsahu** [comment]
Like if you put a link on the page like the electron link on the initial application. when you click it should open on the same page as it is chromium rather it opens up on the default browser redirection

**Comment by black-snow** [comment]
Then don't include https://github.com/szwacz/electron-boilerplate/blob/master/src/helpers/external_links.js

**Comment by black-snow** [comment]
@akhilsahu Is your issue resolved?
