### ISSUE TITLE
Cannot find module 'minimatch' when run exe file in window 10

### ISSUE THREAD

**Issue by shareworlds** [szwacz/electron-boilerplate#285]
I use the command "npm run release" to package files, everything is fine. but when i click the exe file. it pop up error message. see below. 
Does anyone know what i missed?

My computer environment is:
node version: v8.2.1
npm version: 5.3.0
system: windows 10

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module 'minimatch'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (D:\Test\test11\electron-boilerplate\dist\win-unpacked\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Test\test11\electron-boilerplate\dist\win-unpacked\resources\app.asar\node_modules\fs-jetpack\lib\utils\matcher.js:3:19)
    at Object.<anonymous> (D:\Test\test11\electron-boilerplate\dist\win-unpacked\resources\app.asar\node_modules\fs-jetpack\lib\utils\matcher.js:87:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by black-snow** [comment]
Hi and thanks for your report.

Is minimatch installed?
Can you find minimatch in the unpacked build output?
Can you post your build configuration?

**Comment by shareworlds** [comment]
There are 3 folder with names in node_modules.
_minimatch@0.2.14@minimatch
_minimatch@2.0.10@minimatch
_minimatch@3.0.4@minimatch

But It can't be see in win-unpacked folder. there is not minimatch dll in unpakced folder.

**Comment by black-snow** [comment]
Do other dependencies work?
Please post your build config.

**Comment by shareworlds** [comment]
env_production.json

{
  "name": "production",
  "description": "Add here any environment specific stuff you like."
}

**Comment by shareworlds** [comment]
package.json

{
  "name": "electron-boilerplate",
  "productName": "Electron Boilerplate",
  "description": "Starter for your Electron application",
  "version": "0.0.0",
  "author": "Mr. Gumby <mr.gumby@example.com>",
  "copyright": "© 2017, Gumby inc.",
  "homepage": "http://example.com",
  "license": "MIT",
  "main": "app/background.js",
  "build": {
    "appId": "com.example.electron-boilerplate",
    "files": [
      "app/**/*",
      "node_modules/**/*",
      "package.json"
    ],
    "publish": null
  },
  "scripts": {
    "postinstall": "install-app-deps",
    "build": "gulp build",
    "prerelease": "gulp build --env=production",
    "release": "build",
    "start": "gulp start",
    "pretest": "gulp build-unit --env=test",
    "test": "electron-mocha app/specs.js.autogenerated --renderer --require source-map-support/register",
    "coverage": "npm test -- -R scripts/istanbul-reporter",
    "pree2e": "gulp build-e2e --env=test",
    "e2e": "mocha app/e2e.js.autogenerated --require source-map-support/register"
  },
  "dependencies": {
    "fs-jetpack": "^1.0.0"
  },
  "devDependencies": {
    "chai": "^4.1.0",
    "electron": "^1.6.11",
    "electron-builder": "^19.16.0",
    "electron-mocha": "^4.0.0",
    "gulp": "^3.9.1",
    "gulp-batch": "^1.0.5",
    "gulp-less": "^3.3.2",
    "gulp-plumber": "^1.1.0",
    "gulp-util": "^3.0.8",
    "gulp-watch": "^4.3.11",
    "istanbul": "^0.4.5",
    "minimist": "^1.2.0",
    "mocha": "^3.4.2",
    "rollup": "^0.45.2",
    "rollup-plugin-istanbul": "^1.1.0",
    "source-map-support": "^0.4.15",
    "spectron": "^3.7.2"
  }
}

**Comment by black-snow** [comment]
There's no `minimatch` in your dependencies ;)

**Comment by shareworlds** [comment]
this is demo i download from git, does it need to add "minmatch" in dependencies default?

**Comment by shareworlds** [comment]
Thank you your time.

**Comment by black-snow** [comment]
You seem to require `minimatch` somewhere. So yes, you'll have to add it to the deps.

`npm i --save minimatch` (or `--only=production` if required)

**Comment by szwacz** [comment]
Minimatch is an internal dependency of fs-jetpack, If you're using npm v5 I suspect that might me a culprit, it quite often installs malformed dependecy trees. If that is the case make sure you have the latest version of npm.

**Comment by iamwelk** [comment]
it's useless
