### ISSUE TITLE
ipcMain: Error

### ISSUE THREAD

**Issue by 7elevenseven** [szwacz/electron-boilerplate#286]
I get an Error while using ipcMain.

Error:
`Uncaught TypeError: Cannot read property 'on' of undefined`

Code:
`import { ipcMain } from 'electron';`

`ipcMain.on('status', function (event, arg) {
    event.sender.send('status-reply', message);
})`

**Comment by black-snow** [comment]
Where's your call to `ipcMain.on()`? Is it inside `app.ready`?

Seems like you import doesn't work. Please try with `const {ipcMain} = require('electron')`

**Comment by 7elevenseven** [comment]
@black-snow This changed nothing and its in a `$(document).on('click', '.class', function(event) {`

**Comment by black-snow** [comment]
How can `ipcMain` be in a DOM context? It's *main* thread only.
If you are in the renderer you'll have to use `ipcRenderer` https://electron.atom.io/docs/api/ipc-renderer/

Please post the whole thing.

**Comment by 7elevenseven** [comment]
I have `actionListener.js` inside I create a new window with a click on element, this is also my main thread. 
I add HTML-content dynamically, with ipc I will found out with element I've clicked.

`
const BrowserWindow = require('electron').remote.BrowserWindow
const path = require('path')
import { app } from 'electron';
const {ipcMain} = require('electron')
import env from '../env';

let message = "";
$(document).on('click', '.animalProfile', function(event) {
    /* let id = event.target.attributes[1].value;
    let name = event.target.attributes[2].value;
    let age = event.target.attributes[3].value;

    message = "animalProfile";*/

    const modalPath = path.join('file://', __dirname, './template/profile.html')
    let win = new BrowserWindow({ width: 600, height: 320 })
    win.on('close', function () { win = null })
    win.loadURL(modalPath)
    win.show()

    if (env.name === 'development') {
        win.openDevTools();
    }
});

ipcMain.on('status', function (event, arg) {
    event.sender.send('status-reply', message);
})
`

**Comment by black-snow** [comment]
What is the file that you pasted? `$(document)` this is probably jQuery, right? So it's renderer.

> I add HTML-content dynamically, with ipc I will found out with element I've clicked.

Where do you add html content to? Main has no window so it can't be main. Use ipcRenderer.

**Comment by 7elevenseven** [comment]
I've a main window, with a click on a nav-element I open a new window. I need infos of the main window in the new window. 
 
My `app.js` render the first window, also main window:
https://pastebin.com/NN7S0j0v

From the actionListener get the nav-element the click operation.

With load I add content dynamically. 
I've a profile wrapper with I load the dynamic content: 
https://pastebin.com/6ZTs6JGC

With the new window, I load a new javascript file `<script src="../js/profile/animal.js"></script>`
The ipcRenderer, also animal.js:
https://pastebin.com/VLjWprWF

**Comment by black-snow** [comment]
I fear you got that wrong. In an electron app you have one **main process** - that's the one process that's started when starting the application. That process is background-only. Each and every BrowserWindow you open is a new **renderer process**.
**ipcMain** can only be used in the main process.
**ipcRenderer** can only be used in renderers, i. e. BrowserWindow.

Also different ipcRenderer in different windows cannot talk to each other directly but the main process needs to act as a broker. You'll end up with a star schema with main in the center.

So when you have BrowserWindow **A** that opens BrowserWindow **B** and **B** needs to know stuff about **A** you'll have to pass stuff from **A** to **main** and from **main** to **B**.
Or you save your stuff to the session and share the session - that should be possible, too, I guess.

**Comment by 7elevenseven** [comment]
@black-snow Thanks a lot.

**Comment by black-snow** [comment]
You're welcome :)
