### ISSUE TITLE
Add eslint to boiler-plate

### ISSUE THREAD

**Issue by varunkumar** [szwacz/electron-boilerplate#287]
This project is very useful to get started with electron and preconfigured build tools. The only thing that I found to be missing for a new project was 'eslint' configurations. Please add support for ESLint with basic rules to the boilerplate.

**Comment by black-snow** [comment]
@varunkumar Hey there and thanks for the kind words.

I think szwacz aims to keep this boilerplate minimal. There are many different eslint presets and I think it'd be wrong if this boilerplate *softly enforces* one specific preset. It shouldn't be hard for people to read about eslint and to chose and copy a .eslint file. That's a 5 minute job.

Anyhow, @szwacz should give you a final answer ;)

(I feel like it'd be nice to have some kind of meta cli package like artisan for laravel or like some other boilerplates do have. Checking out the boilerplate each time is a little cumbersome.)

**Comment by szwacz** [comment]
@black-snow about eslint you read my mind :) There is now also [prettier](https://github.com/prettier/prettier). Also a lot of guys these days use TypeScript. So a lot of opinions and someone for sure won't be happy with my pick.

About CLI - Electron is just a special flavour of web development, so this is not new environment, use all CLIs available there (or I misunderstood the question). I'm old fashioned and still just check out repos, or update cherry-picked files by hand, so I don't know what difference actually CLI can provide (I'm waiting for someone to drop this knowledge on me ;).

As for the boilerplate - it starts to have some wrinkles, JS world moved along (especially in the webpack way) and this project stays still. I just don't feel like programming during summer, when outumn come I'll face-lift this code a bit.
