### ISSUE TITLE
Change window size in 'createWindow' not working

### ISSUE THREAD

**Issue by sibi-ravindran** [szwacz/electron-boilerplate#288]
Hi, I am trying to change the size of the main window by changing the width and height parameters in background.js as per the below code. 
```

  const mainWindow = createWindow('main', {
    width: 400,
    height: 400,
  });

```
However, this does not change the window size, any tips?

**Comment by black-snow** [comment]
Hi there and thanks for your report.

You must be doing something else wrong, then. Have you edited the right file? I sometimes catch me editing files inside `app` that get overriden from `src` - quite a pitfall.

**Comment by sibi-ravindran** [comment]
Yeah I have caught myself doing that too :)

But in this case, I am changing the code in src/background.js. However the window size does not change even if the 'width' parameter in the 'const mainWindow' is 1000 or 200.

**Comment by black-snow** [comment]
Are we talking about a window that's already open?

**Comment by szwacz** [comment]
Those dimensions are only used as defaults. After you open the app and then close it, the dimensions of the window has been saved to file https://github.com/szwacz/electron-boilerplate/blob/master/src/helpers/window.js#L11 and during next open of the app window size will be read from that file (so user can resize and reposition the window to his/her preferences).

I'm suspecting this is the only culprit of your problems :)
