### ISSUE TITLE
Cannot download winCodeSign, attempt #2: Error: EBUSY: resource busy or locked, open 'C:\Users\JGarza\AppData\Local\electron-builder\cache\winCodeSign\23f4-15ed19b3419-0.7z'

### ISSUE THREAD

**Issue by jgarza9788** [szwacz/electron-boilerplate#289]
![2017-09-30_0-07-00](https://user-images.githubusercontent.com/8079550/31043570-58ee1a60-a573-11e7-97dc-e1472d619240.png)

**Comment by szwacz** [comment]
electron builder (https://github.com/electron-userland/electron-builder) is throwin this error. And that might be related: https://github.com/electron-userland/electron-builder/issues/2009
Anyway, nothing I can do here.
