### ISSUE TITLE
add .bowerrc file?

### ISSUE THREAD

**Issue by subutux** [szwacz/electron-boilerplate#29]
would be nice to add a .bowerrc file, setting the working dir to app:
```json
{
  "cwd" : "app"
}
```

**Comment by bosonogi** [comment]
Since the boilerplate doesn't use bower, what I did was put the `bower.json` inside the `app` folder and execute bower commands there. Worked out fine.

**Comment by subutux** [comment]
That's one way of doing it, but I like keeping my workflow organized. I already execute npm from the main folder, why not bower? For a novice, this could be confusing. (as by me). Only by looking at the source of `tasks/build.js` I saw that it looked for the `bower_components` folder in the `app` directory. This simple file makes my life easier.

Just a thought to help others out.

**Comment by szwacz** [comment]
Haaah.... you just gave me hard nut to crack. I agree, this project should eather not mention bower at all, or support it fully. Since no bower components are used here I'm leaning towards no bower, and everyone who needs bower could easily add those files.

Thoughts? How many bower users actually are there? (I'm not one of them)

**Comment by carlosperate** [comment]
Perhaps I am biased, as I am not a bower user either, but as a boiler plate I would prefer it to be as light weight as possible and then each user can customise it as required.

**Comment by szwacz** [comment]
Ok, I've removed all mentions of Bower from this repository. This makes more sense. Everyone who uses Bower can add those things in 5 minutes.
@subutux I apologize that your request actually had opposite effect to what you intend :)
