### ISSUE TITLE
Angular files can't be found in the release app

### ISSUE THREAD

**Issue by GBora** [szwacz/electron-boilerplate#290]
I'm trying to build a application and for the moment I have as my dependencies angular 1.6 and ui.router, I've included them this way

```
<!doctype html>
<html ng-app="electron-quest">
<head>
  <meta charset="utf-8">
  <title>Electron Boilerplate</title>
  <link href="stylesheets/main.css" rel="stylesheet" type="text/css">
</head>
<body ng-controller="MainCtrl as mc">

  <ui-view></ui-view>

  <script src="app.js"></script>
  <script src="../node_modules/angular/angular.js"></script>
  <script src="../node_modules/@uirouter/angularjs/release/angular-ui-router.js"></script>
  <script src="../src/angular-app/app.main.js"></script>
  <script src="../src/angular-app/routes/app.routes.js"></script>
</body>
</html>
```

and I have them listed as dependencies in my package.json.

when I run in development mode with `npm start` it works but when I package it with `npm run release`  electron can't find the angular module I created specifically the app.main.js and app.routes.js files.

**Comment by black-snow** [comment]
Hi & thanks for your report.
Please post your build config. This is rather an issue with electron-builder / a misconfiguraiton.
