### ISSUE TITLE
Quick start commands dont work on linux with nodejs 9.1.0

### ISSUE THREAD

**Issue by folknor** [szwacz/electron-boilerplate#294]
Hi,

So, I recently wanted to make my first electron app just for fun, and I found your boilerplate on awesome-nodejs, so I figured I'd give it a go instead of starting from scratch.

I followed the instructions from README.md to the letter:
```
git clone https://github.com/szwacz/electron-boilerplate.git
cd electron-boilerplate
npm install
npm start
```

And nothing happens.

I tried adding `console.log("foobar");` to build/start.js, and nothing is printed to the terminal.

Here is the output of `npm start`:
```
folk@foo:~/Projects/electron-boilerplate$ npm start
folk@foo:~/Projects/electron-boilerplate$ 
```

Output of `npm install`:
```
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.1 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 987 packages in 18.7s
```

I feel like a complete moron. What is it I'm doing wrong?

**Comment by black-snow** [comment]
Hi and thanks for your report.

I haven't yet tested the boilerplate with node 9 but that shouldn't be an issue for electron ships its own.
Which electron version was installed? (Have a look at the lock-file or the console output.)
Which Linux derivate do you use / X or wayland?

**Comment by folknor** [comment]
```
$ cat package-lock.json | jq '.dependencies.electron'
{
  "version": "1.7.9",
  "resolved": "https://registry.npmjs.org/electron/-/electron-1.7.9.tgz",
  "integrity": "sha1-rdVOn4+D7QL2UZ7BATX2mLGTNs8=",
  "dev": true,
  "requires": {
    "@types/node": "7.0.46",
    "electron-download": "3.3.0",
    "extract-zip": "1.6.6"
  }
}
```

I use X with the nvidia blob driver. I can certainly spin up a VM with a fresh ISO and node 8 and test that if you want?

Or I can possibly nuke node9 and  ~/.npm and try with node8 if you want.

**Comment by black-snow** [comment]
I'm having some issues with one of the dependencies - can't event `npm install` right now.
I'd give node 8 a shot.

**Comment by folknor** [comment]
Unfortunately I get the same result after
1. rm -rf ~/.npm
2. sudo apt --purge remove nodejs
3. sudo sed -i 's/9.x/8.x/g' /etc/apt/sources.list.d/nodesource.list
4. sudo apt update && sudo apt install nodejs
5. rm -rf ~/Projects/electron-boilerplate

And then repeat the README instructions.

```
$ npm --version
5.5.1
```

```
$ nodejs --version
v8.9.1
```

**Comment by folknor** [comment]
I get exactly the same result (nothing happens) with https://github.com/sindresorhus/electron-boilerplate

**Comment by folknor** [comment]
I've tried a lot of things now, including (1) a completely fresh ISO of ubuntu in a virtual machine using node 8 and node 9, (2) nuking all the /usr/lib/node_modules and ~/.npm, (3) `npm cache verify` and `npm cache clean --force`, and I've tried (4) https://github.com/electron/electron-quick-start, and (5) installing electron globally with `npm install -g --verbose electron` and invoking it from the project folders with `./node_modules/.bin/electron .`, and a few other things.

Nothing works, and I either get:
1. No tty output + zero logging output anywhere
2. This stdout/err:
```
/home/folk/Projects/electron-boilerplate/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/home/folk/Projects/electron-boilerplate/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/folk/Projects/electron-boilerplate/node_modules/electron/cli.js:3:16)
    at Module._compile (module.js:641:30)
```
Just obviously with different messages depending on if I use your boilerplate, sindresorhus, or the electron-quick-start one.

Then, I tried the following:
1. `cd ~/Projects && rm -rf electron-boilerplate`
2. `git clone https://github.com/szwacz/electron-boilerplate`
3. `sudo apt install yarn`
4. `yarn --version` prints `1.3.2`
5. `cd electron-boilerplate`
6. `yarn install`
7. `yarn start`

And everything works perfectly, both on node 8.x and 9.1.

Here is the output of `yarn install` on node 9.1:
```
$ yarn install
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
warning electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0: 
[2/4] Fetching packages...
info 7zip-bin-mac@1.0.1: The platform "linux" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-win@2.1.1: The platform "linux" is incompatible with this module.
info "7zip-bin-win@2.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ electron-builder install-app-deps
electron-builder 19.45.4
No native production dependencies
Done in 38.11s.
```

**Comment by black-snow** [comment]
That's weird. But if you can't even run a bare electron when installed via npm this rather sounds like an electron or npm issue. Please open an issue there (and reference this issue). We'll leave it open until it's resolved.

**Comment by folknor** [comment]
Alright, I'll go one down the chain and report it to electron. Although I did already mention it in #atom-shell on freenode a few days ago, and noone has (1) answered me, or (2) said anything in the channel since. There are 40+ people who idle in the channel.

I also mentioned the fact that yarn "fixed" it for me, and noone has replied to that, and noone else has said anything in the channel since.

So maaaaybe I should report it directly to nodejs/npm.

**Comment by mikeyb** [comment]
Try using [nvm](https://github.com/creationix/nvm) with the `lts/carbon` version `nvm install lts/carbon`

Boilerplate works just fine under linux using non-distro npm for me

**Comment by black-snow** [comment]
So, anything new on this? Any links to share?

I'd vote to close this issue as it ain't seem to be boilerplate-related.

Cheers

**Comment by szwacz** [comment]
And closing.
