### ISSUE TITLE
Trayicon doesnt show up

### ISSUE THREAD

**Issue by hevilp** [szwacz/electron-boilerplate#297]
Hi,

normal run with "npm start" shows tray icon.
Compiling with npm run release and running then gives no trayicon.

```app.on("ready", () => {
  setApplicationMenu();

  const trayIcon = './resources/icons/trayicon.png';
  console.log(trayIcon);
  const nimage = nativeImage.createFromPath(trayIcon);
  const tray = new Tray(nimage);

const contextMenu = Menu.buildFromTemplate([
  {label: 'Quit', accelerator: 'Command+Q', selector: 'terminate:',}
]);
tray.setToolTip('CyberCalc');
tray.setContextMenu(contextMenu);

  const mainWindow = createWindow("main", {
    alwaysOnTop: true,
    frame: false,
    width: 755,
    height: 100
  });
  mainWindow.setMenu(null);

  mainWindow.loadURL(
    url.format({
      pathname: path.join(__dirname, "app.html"),
      protocol: "file:",
      slashes: true
    })
  );

  if (env.name === "development") {
    mainWindow.openDevTools();
  }
});```

**Comment by black-snow** [comment]
Have you checked the path to your icon is correct? `./resources/icons/trayicon.png`

P.S.: Use triple backticks (`) to wrap code blocks in markup.

**Comment by hevilp** [comment]
The path is correct, since it gets loaded with npm start. After building it is not shown up

**Comment by KatSick** [comment]
same for me

**Comment by themroberts** [comment]
Same issue for me. It appears that resources is only available for building and not the application. My workaround is creating a static directory in `/app`

Then add the following when creating the tray.
```const tray = new Tray(`${__dirname}/static/icons/512x512.png`);```

**Comment by VeithBuergerhoff** [comment]
This appears to be because of electron builder:

> Please note — build resources is not packed into the app. If you need to use some files, e.g. as tray icon, please include required files explicitly: "files": ["**/*", "build/icon.*"]

[Electron Builder Configuration](https://www.electron.build/configuration/configuration#MetadataDirectories-buildResources)
