### ISSUE TITLE
main.js net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by hevilp** [szwacz/electron-boilerplate#298]
Hi,

I moved my *.js files from the app folder to src folder and changed the static files in app folder to the right part. It runs all fine with "npm start".

When I create the executable with "npm run release" and install the app, it comes:

`GET file:///C:/Users/myuser/AppData/Local/Programs/APPNAME/resources/app.asar/src/main.js net::ERR_FILE_NOT_FOUND`

Before I moved the *.js to src it worked flawless.
What is wrong?

electron 1.8.2
electron-builder version=20.6.2

**Comment by hevilp** [comment]
Oh, I added
`"src/*",`

under package.json build / files and it is working :)

**Comment by szwacz** [comment]
For sure there is no `src/main.js` file in default boilerplate, so it looks like your own changes caused this issue.
