### ISSUE TITLE
Loading external website and preload script

### ISSUE THREAD

**Issue by ErraticFox** [szwacz/electron-boilerplate#299]
Hello, I'm wanting to load an external website and use the preload script on that.

I've cloned the repo in the readme and I've changed `mainWindow` to 
```js
  const mainWindow = createWindow("main", {
    width: 1000,
    height: 600,
    webPreferences: {
      nodeIntegration: false,
      preload: path.join(__dirname, 'app.js')
    }
  });
```
and `mainWindow.loadURL` to
```js
  mainWindow.loadURL(
    url.format({
      pathname: 'https://soundcloud.com'
    })
  );
```

though when I run the app it gives me the error the the apps console `Error: Couldn't find a style target. This probably means that the value for the 'insertInto' parameter is invalid.`

Since I haven't changed anything other than the listed, I know the preload script should work it does when you load it in a index.html file.

**Comment by black-snow** [comment]
sounds webpack-realted

**Comment by ErraticFox** [comment]
I was unaware at the time of asking this haha. I did figure it out, I needed to set `target: 'electron-renderer'` in webpack.config.js
