### ISSUE TITLE
32 bit builds?

### ISSUE THREAD

**Issue by tkambler** [szwacz/electron-boilerplate#30]
Is there anything special I need to know in order to create 32-bit builds using this project?

**Comment by szwacz** [comment]
Hahhh, right, so.....

This is one of pains of this probject. Right now whatever version `npm intall electron-prebuilt` decides to install this version is used to package the app. So the only way to use 32bit electron is to actually run it adn do `npm run release` on 32bit system.

Every ideas how to make it possible without turning whole codebase upside down are welcome!

**Comment by tkambler** [comment]
:+1: I'll get back to you.

**Comment by rubencodes** [comment]
I'm on a 32-bit Windows build and still had issues getting a 32-bit binary despite using 32-bit node. Had to follow [these instructions](https://github.com/szwacz/electron-boilerplate/commit/7cf141161732b6600ed85b3f705dc44297c82460) and set the `SET npm_config_arch=ia32` flag.
