### ISSUE TITLE
npm test & hello world clarification

### ISSUE THREAD

**Issue by espdesign** [szwacz/electron-boilerplate#301]
Is there anyway to be able to run the test. As well as not have the "hello world" text be in your main app.html?

**Comment by szwacz** [comment]
Welll, just delete the text? :)
I don't understand your problem. The tests written in the boilerplate are just to have some examples of tests and are intended to be deleted when you write first real tests.

**Comment by black-snow** [comment]
Maybe he's trying to ask whether it's possible to test other files, too? Or if you can test the same thing when the text is included from somewhere else or inserted dynamically?
