### ISSUE TITLE
expecting updated.

### ISSUE THREAD

**Issue by yanlee26** [szwacz/electron-boilerplate#311]
error /Users/yanli/Documents/zme/electron-boilerplate/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/yanli/Documents/zme/electron-boilerplate/node_modules/electron
Output:
Downloading tmp-21304-0-electron-v4.2.12-darwin-x64.zip
Error: GET https://github.com/electron/electron/releases/download/v4.2.12/electron-v4.2.12-darwin-x64.zip returned 500
/Users/yanli/Documents/zme/electron-boilerplate/node_modules/electron/install.js:49
  throw err
  ^

Error: GET https://github.com/electron/electron/releases/download/v4.2.12/electron-v4.2.12-darwin-x64.zip returned 500
    at Request.<anonymous> (/Users/yanli/Documents/zme/electron-boilerplate/node_modules/nugget/index.js:169:61)
    at Request.emit (events.js:321:20)
    at Request.onRequestResponse (/Users/yanli/Documents/zme/electron-boilerplate/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:321:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:610:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:479:22)

warning Error running install script for optional dependency: "/Users/yanli/Documents/zme/electron-boilerplate/node_modules/fsevents: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: /Users/yanli/Documents/zme/electron-boilerplate/node_modules/fsevents\nOutput:\ngyp info it worked if it ends with ok\ngyp info using node-gyp@6.1.0\ngyp info using node@13.8.0 | darwin | x64\ngyp info find Python using Python version 3.6.3 found at \"/Library/Frameworks/Python.framework/Versions/3.6/bin/python3\"\ngyp info spawn /Library/Frameworks/Python.framework/Versions/3.6/bin/python3\ngyp info spawn args [\ngyp info spawn args   '/Users/yanli/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'make',\ngyp info spawn args   '-I',\ngyp info spawn args   '/Users/yanli/Documents/zme/electron-boilerplate/node_modules/fsevents/build/config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/Users/yanli/.config/yarn/global/node_modules/node-gyp/addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/Users/yanli/Library/Caches/node-gyp/13.8.0/include/node/common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=/Users/yanli/Library/Caches/node-gyp/13.8.0',\ngyp info spawn args   '-Dnode_gyp_dir=/Users/yanli/.config/yarn/global/node_modules/node-gyp',\ngyp info spawn args   '-Dnode_lib_file=/Users/yanli/Library/Caches/node-gyp/13.8.0/<(target_arch)/node.lib',\ngyp info spawn args   '-Dmodule_root_dir=/Users/yanli/Documents/zme/electron-boilerplate/node_modules/fsevents',\ngyp info spawn args   '-Dnode_engine=v8',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'build',\ngyp info spawn args   '-Goutput_dir=.'\ngyp info spawn args ]\nNo receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.\nNo receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.\nNo receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.\n\n\n\ngyp: No Xcode or CLT version detected!\ngyp ERR! configure error \ngyp ERR! stack Error: `gyp` failed with exit code: 1\ngyp ERR! stack     at ChildProcess.onCpExit (/Users/yanli/.config/yarn/global/node_modules/node-gyp/lib/configure.js:351:16)\ngyp ERR! stack     at ChildProcess.emit (events.js:321:20)\ngyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)\ngyp ERR! System Darwin 19.3.0\ngyp ERR! command \"/usr/local/Cellar/node/13.8.0/bin/node\" \"/usr/local/bin/node-gyp\" \"rebuild\"\ngyp ERR! cwd /Users/yanli/Documents/zme/electron-boilerplate/node_modules/fsevents\ngyp ERR! node -v v13.8.0\ngyp ERR! node-gyp -v v6.1.0\ngyp ERR! not ok"
yanlideMacBook-Pro:electron-boilerplate yanli$ npm run 
 
yanlideMacBook-Pro:electron-boilerplate yanli$ yarn sta
rt
yarn run v1.1.0
warning You are using Node "13.8.0" which is not suppor
ted and may encounter bugs or unexpected behavior. Yarn
 supports the following semver range: "^4.8.0 || ^5.7.0
 || ^6.2.2 || ^8.0.0"
$ node build/start.js
/Users/yanli/Documents/zme/electron-boilerplate/node_mo
dules/electron/index.js:14
    throw new Error('Electron failed to install correct
ly, please delete node_modules/electron and try install
ing again')
    ^

Error: Electron failed to install correctly, please del
ete node_modules/electron and try installing again
    at getElectronPath (/Users/yanli/Documents/zme/elec
tron-boilerplate/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/Users/yanli/Documents/zme/e
lectron-boilerplate/node_modules/electron/index.js:18:1
8)
    at Module._compile (internal/modules/cjs/loader.js:
1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/yanli/Documents/zme/electron-boilerplate/build/start.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by szwacz** [comment]
As the error message tells, this is due to networking issues with github, not a problem within this project.
