### ISSUE TITLE
Release script broken

### ISSUE THREAD

**Issue by michaelpeterlee** [szwacz/electron-boilerplate#314]
On following the README.MD Quickstart, `npm run release` results in error:

-
 1 failing

  1) application launch
       "before each" hook: beforeEach for "shows hello world text on screen after launch":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\workspace\electron-boilerplate\temp\e2e.js)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)
-

Host: OSX 10.15.5, MacBook Pro (15-inch, 2019)

**Comment by szwacz** [comment]
This is not release error, just the fact that before release all tests are run, and end to end test has timed out. Does it happen only sometimes or always?

Also I don't know how you have OSX machine and `C:\workspace\electron-boilerplate\temp\e2e.js` path (windows) in error :)

**Comment by michaelpeterlee** [comment]
Sincere apologies, this is actually running in a Windows 10 VM on OSX host. 

We have enjoyed this project for a number of years and bypass the tests hence not seeing this before. This does not affect us directly as a result, but thought I'd present to you.

Let me know if you would like me to investigate further.

**Comment by szwacz** [comment]
Thank you for your commitment :) I was testing this e2e workflow on windows, so have no reason to think it has problems. On virtual machine things have the tendency to lag, so I hope that's the reason of timeout.

Unfortunately I don't have access to Windows machine right now, will close this issue and see if other people report the same problem.
