### ISSUE TITLE
set icon

### ISSUE THREAD

**Issue by hattatyazilim** [szwacz/electron-boilerplate#316]
`mainWindow.setIcon("./resources/icon.ico");` or  `mainWindow.setIcon(app.getAppPath()+'/resources/icon.ico'));`

When i deploy it does not work.

![Capture](https://user-images.githubusercontent.com/74716855/99843599-de48fc00-2b82-11eb-8361-5103a5a3938f.PNG)

**Comment by szwacz** [comment]
did you replace the ico file, of this happens with default ico in this repository?
