### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by jepperaskdk** [szwacz/electron-boilerplate#318]
Hi, cool template! 

For someone who just installed the boilerplate project, what am I to do with the package.json in root and in src? Am I supposed to delete the root one or? Thanks in advance!

**Comment by szwacz** [comment]
As far as I'm concerned there is no package.json in src folder of this repo :)

**Comment by jepperaskdk** [comment]
Ah, embarrassing - I added this to the wrong repo.
Sorry for that, have a nice day!
