### ISSUE TITLE
how am I supposed to put my javascript files into folders?

### ISSUE THREAD

**Issue by destan** [szwacz/electron-boilerplate#32]
I want to create a file `electron-boilerplate/app/anyfolder/constants.js` with content

```
module.exports = {
  a = 1,
  b = 2
}
```

Then use this file in `main.js` as follows:

```
var constants = require('./anyfolder/constants');
```

However I get 

```
Uncaught Exception:
ReferenceError: define is not defined
```

error because in build directory `constant.js`'s content is changed and starts with

```
define(['exports'], function (exports) {
```

What am I missing? Can't I use folders for javascripts to be used from `main.js`?

**Comment by destan** [comment]
Ok, figured it out. Need to exclude from js-transpiler in `tasks/build.js`

```
var paths = {
    jsCodeToTranspile: [
        'app/**/*.js',
        '!app/main.js',
        '!app/spec.js',
        '!app/node_modules/**',
        '!app/vendor/**',
        '!app/anyfolder/**'
    ],
    copyFromAppDir: [
        './main.js',
        './spec.js',
        './node_modules/**',
        './vendor/**',
        './**/*.html',
        './anyfolder/**'
    ],
}
```

**Comment by szwacz** [comment]
@destan This boilerplate is configured to require files through ES6 syntax. By using `module.exports` you will be constantly fighting the design ;)
I intended `require()` to be reserved for loading npm modules only.

**Comment by destan** [comment]
@szwacz so you suggest me using ES6 syntax in backend/main.js as well?

**Comment by szwacz** [comment]
Ah, right, problems are always more complicated than they appear.
ES6 syntaxt won't work in main process because there is no loader configured to load them, so I'd go with `module.exports` then, or add transpilation task so I can use ES6 syntax just for consistency with the rest of app.

BTW may I ask what type of logic you are adding to main process?

**Comment by destan** [comment]
> BTW may I ask what type of logic you are adding to main process?

Sure, I'd appreciate any suggestions. Suppose the desktop app uses a database, ORM, executes some business logic on user input before inserting them into db meanwhile makes external service calls etc. 

Such logic shouldn't be in front-end scripts in my opinion. That's why I am trying to modularize those in separate files and import into `main.js`.

To clarify a usage example:

1. User clicks a button on a `browserWindow`
2. Some information is send to `Main Process` from `Renderer Process`
3. In `Main Process`, incoming information is processed/used by business logic and persisted or send out via external service calls.

I think the codes on 3rd step should be on separate modules and be used on `Main Process`.

**Comment by szwacz** [comment]
Copy, paste of what I wrote as response to other issue:

I see because of this Electron's division to main and window scripts people start to think in terms of backend <-> frontend. I believe this is not the right mindset. Main script is just a manager for windows you want to open (you can open more than one, then everything changes and you need some communication and probably need some logic in main script). There is nothing you can't do in window context (AFAIK) what you can do in main context. Window context is browser and node.js combined, that's where the power really is.

**Comment by szwacz** [comment]
So if your application is one window only, I don't think you need any business logic in main script.

**Comment by destan** [comment]
Thanks @szwacz really appreciate your comments. I am coming from Java and Qt mindset hence my pov might be quite different than nodejs community's.

>  There is nothing you can't do in window context (AFAIK) 

well, there are some edge cases like clipboard manipulation. I've read that you need to do clipboard related stuff on main process due to some technical limitations.

Moreover, my app consists of multiple windows. Some of them are triggered via global shortcuts and some of them via system tray.

Windows share logic, validation, and persistence code so putting those codes to browser scripts seems to end up in code duplication and eventually spaghetti code.

That's why I try to duplicate Qt style structure where views (browser windows) are just views to collect user input and show user some info and all logic is executed by other classes (scripts on main process).

IMHO, being able to do anything in the browser windows doesn't necessarily mean that we should and we are better construct a layered architecture somehow.

Well, we will see if it works or cause more problems.

**Comment by szwacz** [comment]
Yep, in case of multiwindow application what you say definitely makes sense!
