### ISSUE TITLE
requirejs related question

### ISSUE THREAD

**Issue by tysenmoore-xse** [szwacz/electron-boilerplate#41]
First, thanks so much for the great bolilerplate, it has been great for a newbie of web programming to begin creating a cross platfore app with Electron.

I am working to add AngularJS and jQuery EasyUI support to the boilerplate.  For easyui support I was able to add without any special requirejs problems or dependencies--later I need to refactor that to also use requirejs.  However, I am adding AngularJS has brought about some questions with requirejs and I was hoping you could offer some suggestions.

I am now adding a requirejs.config statement to the boilerplate in the hopes of defining the correct requirejs layout/configuration for my app.  Where would you envision this going?  I have changed the boilerplate a bit in an attempt to getting just the requirejs dependencies working but I find some files get parsed but the define/function is not executed.

* I have no changes to **./app/main.js**
* I have modified the **./app/app.html** to be:
```
<!doctype html>
<html>
<head>
    <title>Electron Boilerplate</title>
</head>
<body >
    <h1>Hello World!</h1>
    <script data-main="require_config" src="vendor/require.js"></script>
</body>
</html>
```
* My new file, **./app/require_config.js** looks like:
```
console.log("REQUIRE_CONFIG.JS-------------"+requirejs.version);
requirejs.config({
	paths: {
    'myapp': './js/myapp'
  },
  // kick start application
  deps: ['./bootstrap']
});
```
* My new file, **boostrap.js** is meant to manually bootstrap AngularJS, etc.
```
 console.log("BOOTSTRAP.JS1-------------");
 define( ['myapp'], function (myapp) {
      'use strict';
     console.log("BOOTSTRAP.JS2+++++++++++++");
 });
```
* For an example, I have the bootstrap now have a dependency on a new file, **myapp.js**.  This file would create the AngularJS application file.
```
console.log("MYAPP.JS-------------");
define([], function () {
  'use strict';
  console.log("MYAPP.JS+++++++++++++");
});
```

NOTE: My modified code doesn't use your original app.js.  I am only trying to test/target requirejs.

After running this example I find:
```
[1262:0917/172739:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[1291:0917/172739:INFO:renderer_main.cc(200)] Renderer process started
[1295:0917/172739:INFO:renderer_main.cc(200)] Renderer process started
[1262:0917/172740:INFO:CONSOLE(4)] "REQUIRE_CONFIG.JS-------------2.1.20", source: file:///home/swdev/projects/build/require_config.js (4)
[1262:0917/172740:INFO:CONSOLE(4)] "BOOTSTRAP.JS1-------------", source: file:///home/swdev/projects/build/bootstrap.js (4)
```
The require_config.js and bootstrap.js are processed but the define/function is not executed.  Furthermore, the app,js is not parsed at all.  I have also removed the myapp dependency within bootloader.js to be `define( [], function () {` but this didn't work either.

Could the problem here be related to requirejs or something other interaction with node.js/babel/etc?  Any ideas or suggestions on what the problem might be and/or how you envision extending the requirejs infrastructure here would be much appreciated.  Thanks in advanced for the time.

**Comment by tysenmoore-xse** [comment]
I have spent a few days on this problem and after sending you this posting I may have found the problem.  I was hoping you could possibly help me with the reason why it fails to execute the code.

I read through some of your closed issues and saw mention of the *./tasks/build.js* jsCodeToTranspile and copyFromAppDir.  I realized the new modules were being transpiled.  So I added the files ('./require_config.js',  './js/myapp.js',  './bootstrap.js') to the copyFromAppDir and was presented with the expected output:
```
[1530:0917/174440:INFO:CONSOLE(1)] "REQUIRE_CONFIG.JS-------------2.1.20", source: file:///home/swdev/projects/build/require_config.js (1)
[1530:0917/174440:INFO:CONSOLE(1)] "BOOTSTRAP.JS1-------------", source: file:///home/swdev/projects/build/bootstrap.js (1)
[1530:0917/174440:INFO:CONSOLE(1)] "MYAPP.JS-------------", source: file:///home/swdev/projects/build/js/myapp.js (1)
[1530:0917/174440:INFO:CONSOLE(4)] "MYAPP.JS+++++++++++++", source: file:///home/swdev/projects/build/js/myapp.js (4)
[1530:0917/174440:INFO:CONSOLE(4)] "BOOTSTRAP.JS2+++++++++++++", source: file:///home/swdev/projects/build/bootstrap.js (4)
```
The problem was the failure was silent and gave no indication of a real failure, the code just did not execute.  Does this make sense to you that the requirejs files must not be transpiled?  Moving forward must all my requirejs modules avoid transpiling?  Any advice would be welcome.

**Comment by szwacz** [comment]
Hi, I don't think you grasped my intentions with this boilerplate. 

1. File `app.js` is ment to be used as starting point for your code, you can easily start write angular applicaiotn there.
2. Transpilation is the process which among other things translates modules written in ES6 syntax into Require.js format, so you shouldn't use require.js `define` structure, this structure is generated automatically for you from much nicer in use ES6 modules syntax.

But one thing that I see clearly thanks to issues filed here is that I made the whole thing too complicated. Must simplify it....

**Comment by carlosperate** [comment]
Doesn't the latest chromiun engine and Node 4.0 (which is now shipped with electron) support ES6?

**Comment by tysenmoore-xse** [comment]
Thanks for the fast response.  I do grasp the concept of the boilerplate.  I am using it to start writing my application.  My lack of understanding was how to further integrate and use requirejs within your design.  I am completely new to web application concepts (embedded programmer by trade)--I apologize for my ignorance.  I do appreciate the further clarification on the transpilation.  I think I better understand your intent and how I need to model my JS modules.  I will modify my sample code to be more ES6 compliant.  I appreciate your time and the time taken to develop and support the boilerplate.

**Comment by szwacz** [comment]
@carlosperate Node v4 has some support for ES6, but not for ES6 Modules, those are not even on the horizon yet (or are they?). So we're still cursed to use transpilers and module loaders for some time.

**Comment by szwacz** [comment]
@tysenmoore-xse chillax man :) 
The problem you have is very valuable clue to me, boilerplated are all about being easy to understand, and other people also had difficulties with customizing this transpilation process. At the same time I'd like to use ES6 Modules because this is the future.

This weekend will sit and figure out better way...

**Comment by szwacz** [comment]
The project stopped using require.js, and moved to bundles which are then included via ordinary <script> tag.

Hope now it will be easier to follow :)
