### ISSUE TITLE
Using requirejs and Babel in main process

### ISSUE THREAD

**Issue by jacwah** [szwacz/electron-boilerplate#42]
I'm a Electron and web tech beginner, and found this project very helpful as a starter kit. The app I'm developing can save and load a config file from disk. This has to be done from the main process, so I set up an IPC system.

Only the render process has access to requirejs as far as I can tell. If the main process would have access as well, it could be transpiled through Babel and use new ES6 features. It would also allow sharing code between the processes easier.

I currently have all main process code separated into `app/main/`, which is excluded from transpilation.

* Why isn't ES6 enabled for the main process?
* Should it be enabled?

_Related to #22_

**Comment by szwacz** [comment]
Hi, few changes just happen:
1. `main.js` has been renamed to `backgrond.js` and now you can use there ES6 modules.
2. This project no longer leverages Babel.
a) Babel was used only for es6 modules transpilation (now switched to rollup). 
b) Electron runs the lates chrome possible, so you already have a lot of ES6 features natively available.
c) Everyone who wants can install Babel on their own (I hope that will be quite easy, however gulp-babel probably woulnd't work and babal-core needs to be joined with rollup).
