### ISSUE TITLE
Cluster Terminates on Production Release Only

### ISSUE THREAD

**Issue by tysenmoore-xse** [szwacz/electron-boilerplate#48]
I have an application that creates a cluster [fork] and sends a message to it.  The app works fine for `development` build on Windows and Ubuntu.  I then create a release (`npm run release`) and things change.  If I run the application from the Windows start menu or doubl-click the file in Explorer the program runs but the cluster terminates immediately after going `online` with an exit code of 1.  If I run the same application again but from the command line it works without a problem--the cluster does not terminate.  The same thing happens in Ubuntu--fails from dash, works from the terminal.

I wasn't sure if you may have seen this or it is a symptom of the release process.  If not I can post something to the electron github.  As always, thanks for your time and any support.

**Comment by szwacz** [comment]
The only difference between development and production build that I can think of is that production build is packed with asar, there are steps like this in build script for every platform:
```js
var packageBuiltApp = function () {
    var deferred = Q.defer();

    asar.createPackage(projectDir.path('build'), readyAppDir.path('resources/app.asar'), function() {
        deferred.resolve();
    });

    return deferred.promise;
};
```
Try what happens when you skip this step.

**Comment by tysenmoore-xse** [comment]
Thanks for the suggestion!  I was struggling to have a better workflow to debug this problem.  For anyone interested, I found I had to change the `packageBuiltApp` to copy my build source, otherwise I had no source.  If I also comment our the `cleanupRuntime` wasn't getting the complete app.  My change was:

    var packageBuiltApp = function () {
        return projectDir.copyAsync(projectDir.path('build'), readyAppDir.path('resources/default_app'), { overwrite: true });
    };
 
When I avoided the `asar` I got the same results.  Now that I had source to more easily debug, instead of being in the `asar`, I think I found the problem.  I had a hunch that the terminal was the important factor since it worked no matter what with the terminal.  So I commented out the `console.log` from my cluster code it worked fine.  The cluster stayed alive.  It seems odd considering many cluster examples contain console.log messages--even the example on the [node documentation.](https://nodejs.org/api/cluster.html#cluster_cluster_worker)

Thanks so much for the support!

In case anyone cares,  I added this to the app.js:  (NOTE: the cluster.setupMaster was important for electron builds)

    var cluster = require('cluster');
    var path = require('path');

    var sdkWorker = null;

    console.log("startSdkWorker");

    // MUST use the setupMaster otherwise the default electron 
    // environment is used and will fail with:
    // ../node_modules/electron-prebuilt/dist/electron: bad option: --type=renderer
    // ...
    cluster.setupMaster({
      exec: path.join(__dirname, "sdk_worker.js"),
      //args: ['--use', 'https'],
      silent: false
    });

    sdkWorker = cluster.fork({});

    cluster.on('fork', function(worker) {
        console.log('WORKER: forked: ' + worker.process.pid);
    });

    cluster.on('online', function(worker) {
        console.log('WORKER: ' + worker.process.pid + ' is online');
    });

    cluster.on('exit', function(worker, code, signal) {

        var suicide = "";
        if (worker.suicide === true) {
            suicide = " [SUICIDE] ";
        }

        console.log('EXIT: WORKER: '+suicide+ worker.process.pid + ' died with code: ' + code + ', and signal: ' + signal);
        sdkWorker = null;
        //console.log('Starting a new worker');
        //this.sdkWorker = cluster.fork();
    });

    sdkWorker.on( 'message', function( msg ) {
        console.log("FROM SDK: "+msg.cmdId);
        } );

    // Init the lib and SDK platform
    sdkWorker.send( {cmdId:"init"} );

    // Do an initial enumeration of USB looking for the analyzer
    sdkWorker.send( {cmdId:"enumUsb"} );

    // Start the contant polling of the SDK
    sdkWorker.send( {cmdId:"startPoll"} );

The sdk_worker.js was simply:

    // Cluster support
    process.on('message', function(msg) {
        //console.log("FROM MASTER: "+msg.cmdId);
    });

With the `console.log` commented out it now goes `online` and does not follow with an `exit`.
