### ISSUE TITLE
Problem Launching from Ubuntu Unity

### ISSUE THREAD

**Issue by tysenmoore-xse** [szwacz/electron-boilerplate#49]
I had a situation where I could properly run the application from the terminal and double click the app in the nautilus window.  However, launching from the Ubuntu Unity would give me a failure.  After some looking it seems the `app.desktop` needs the following:

    Path=/opt/{{name}}/

If you'd prefer I could fork and use a pull request.  Seemed like a simple change so I didn't do the fork, etc.

**Comment by szwacz** [comment]
Sure, please add! I love pull requests :)
