### ISSUE TITLE
failed in app_npm_install task

### ISSUE THREAD

**Issue by plrthink** [szwacz/electron-boilerplate#5]
Hi, I am trying to build a windows app using this boilerplate, but I get some trouble in installing dependencies. Errors shows below:

    plrth_000@PLRTHINK-PC ~/Desktop/electron-boilerplate (master)
    $ npm install
    npm WARN package.json @ No repository field.
    npm WARN optional dep failed, continuing appdmg@0.3.1
    /
    > electron-prebuilt@0.26.1 postinstall c:\Users\plrth_000\Desktop\electron-boile
    rplate\node_modules\electron-prebuilt
    > node install.js

    /
    > @ postinstall c:\Users\plrth_000\Desktop\electron-boilerplate
    > node ./tasks/app_npm_install

    events.js:72
        throw er; // Unhandled 'error' event
              ^
    Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

    npm ERR! @ postinstall: `node ./tasks/app_npm_install`
    npm ERR! Exit status 8
    npm ERR!
    npm ERR! Failed at the @ postinstall script.
    npm ERR! This is most likely a problem with the  package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node ./tasks/app_npm_install
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls
    npm ERR! There is likely additional logging output above.
    npm ERR! System Windows_NT 6.2.9200
    npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodej
    s\\node_modules\\npm\\bin\\npm-cli.js" "install"
    npm ERR! cwd c:\Users\plrth_000\Desktop\electron-boilerplate
    npm ERR! node -v v0.10.36
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm ERR!
    npm ERR! Additional logging details can be found in:
    npm ERR!     c:\Users\plrth_000\Desktop\electron-boilerplate\npm-debug.log
    npm ERR! not ok code 0

I am running nodev0.10.36 on windows8.1.

**Comment by john-kelly** [comment]
Try `sudo npm install`
No promises

**Comment by szwacz** [comment]
Ah, bummer! Didn't check windows platform after changing that.
Can you tell me if it starts working when you in file `tasts/app_npm_install.js` change line 41
from:
```
var install = childProcess.spawn('npm', params, {
```
to:
```
var install = childProcess.spawn('npm.cmd', params, {
```

**Comment by plrthink** [comment]
@szwacz  I would give a try.

**Comment by plrthink** [comment]
@szwacz Yeah, it works. :beers:

**Comment by plrthink** [comment]
@szwacz I just created a PR for this and I am closing this issue.
