### ISSUE TITLE
Improve Windows uninstaller

### ISSUE THREAD

**Issue by idleberg** [szwacz/electron-boilerplate#54]
It's considered a bad idea to use `RMDir /r $INSTIR` as you did on [line 153](https://github.com/szwacz/electron-boilerplate/blob/master/resources/windows/installer.nsi#L153). Imagine what would happen, when a user (accidentally?) installs into `Program Files`. See this [StackOverflow](https://stackoverflow.com/questions/3259533/is-it-safe-to-do-rmdir-r-instdir-in-nsis) post and consider using these [macros](http://nsis.sourceforge.net/Uninstall_only_installed_files).

**Comment by szwacz** [comment]
I understand your concerns, but install process used here doesn't give you the ability to edit path where application files will end up (it's predetermined by developer). So I'm guessing this solution is safe here?

**Comment by idleberg** [comment]
Well, your right. I guess it's highly unlikely to happen, though still possible through command-line
