### ISSUE TITLE
NSIS, Windows and UTF-8

### ISSUE THREAD

**Issue by blackfyre** [szwacz/electron-boilerplate#60]
Currently the NSIS doesn't do well with Hungarian characters. Even after creating the script file for the NSIS the character encoding is great, but in the installer and later in the path the characters are messed up.
For example:
`TerĂĽlet szĂˇmolĂˇs` should be `Terület számolás`

I've found this little NSIS addon: http://nsis.sourceforge.net/Utf8Converter but I haven't got the faintest on how start using it... any help would be welcome :smile:

**Comment by szwacz** [comment]
You can google the file to see who elce already used it :)
https://github.com/sihorton/deskshell-showcase/tree/master/win-native-func/node_modules/deskshell-win-func

**Comment by idleberg** [comment]
@blackfyre You can use this command to convert ANSI files to Unicode, but since language files have to be included on compile time, that's of no help. You should either provide ANSI encoded languages files or compile your script using NSIS 3.0 (beta).
