### ISSUE TITLE
Generate new files

### ISSUE THREAD

**Issue by sergiuwd** [szwacz/electron-boilerplate#61]
Hi! I have created an app that replicates a database's tables to json files. I want to release this app as an executable. The problem is that after the script is compiled, I can't create the files. All the app files are inside the "app" folder. What should I do?

**Comment by szwacz** [comment]
Hey. I don't fully understand your explanation bit it sounds like you're writing files just next to source code, instead of to one of those locations: https://github.com/atom/electron/blob/master/docs/api/app.md#appgetpathname

**Comment by sergiuwd** [comment]
Hi! I've opened the issue from my mobile phone, and I was in a rush, so I could not be more specific.

Here is my code:
<pre>
toSync.forEach(function(elem) {

  connection.query('select * from emenu.' + elem + ';', function(err, results, fields) {
    if (err) {
      error = true;
      showStatus('error', 'Eroare la preluarea tabelei <i>' + elem + '</i>: ' + err);
    } else {
      fs.writeFile('db/' + elem + '.json', JSON.stringify(results), function(err) {
        if (err) {
          error = true;
          showStatus('error', 'Tabela <i>' + elem + '</i> nu a putut fi sincronizata ' + err);
        } else {
          showStatus('success', 'Tabela <i>' + elem + '</i> a fost sincronizata!');
        }

      });
    }
  });

});
</pre>

I am using fs.writeFile to write the files. What am I doing wrong?

**Comment by szwacz** [comment]
Yep, you want to save this file in folder where your JS files resides. It might give you problems.

The link I gave you in previous comment is what you need. You just need to put some understanding to this :) (there is separation of you application code and data which your application stores).
