### ISSUE TITLE
extra files ? 

### ISSUE THREAD

**Issue by gbaumgart** [szwacz/electron-boilerplate#62]
Hi,
I would like to have some extra files & directories added to my app. How can I do that ? I tried to place some in /app but they don't popup in the install folders (NSIS or deb).

Is that a electron matter or should I try to implement this in the boiler-plate ? 

and thank you for this plate! Its extremely helpful, and i tried many solutions!

**Comment by szwacz** [comment]
Those extra files need to be copied in build process. Please see `tasks/build.js`.
The part which interests you is:
```js
var paths = {
    copyFromAppDir: [
        './node_modules/**',
        './vendor/**',
        './**/*.html'
    ],
}
```
And probably you'll need some understanding of gulp :)

**Comment by gbaumgart** [comment]
awesome! thanks for the pointer!
