### ISSUE TITLE
Required module not found in release app (Windows)

### ISSUE THREAD

**Issue by activetheory** [szwacz/electron-boilerplate#73]
Hi there,

Thanks so much for this very helpful boilerplate.

I have got my project set up, and it works just fine when I using "npm start".

When I create a windows install file via "npm run release", my app builds but when I open it, I get an error that my kinect2 module can not be found.

I am trying to require the [kinect2](https://github.com/wouterverweirder/kinect2) module, which has native bindings. I tried to run `npm run app-install -- kinect2` but got a node-gyp error on compilation. The kinect2 lib has it's own install script, which I ran inside the boilerplate directory, and it runs fine in test mode.

Hopefully, I'm just missing something silly and it's not being copied over.

Thanks!

**Comment by szwacz** [comment]
I've just glanced on the kinect2 build script, but I wuould give it a try this way:

- Install kinect to optionalDependencies, so it can safely fail during `npm install`
- Then I would modify the postinstall script to:
```
"postinstall": "node ./tasks/app_npm_install && node path/to/kinect/tools\electronbuild.js --target=x.xx.x --arch=x64",
```
How about that?

**Comment by szwacz** [comment]
Ahhh that's not the real problem, sorry :)
The problem is in release script. I can't help there unfortunately, I'm a mac user and this is too much configuring on VM to run this on Windows.

**Comment by waynebloss** [comment]
According to [kinect2 issue 20](https://github.com/wouterverweirder/kinect2/issues/20), precompiled binaries are supported in [kinect2 v0.1.1](https://www.npmjs.com/package/kinect2) which is the latest on npm right now.
