### ISSUE TITLE
Understanding how to get React to work

### ISSUE THREAD

**Issue by samhagman** [szwacz/electron-boilerplate#75]
Hey first of all this is a great boilerplate, I really appreciate the work you put into the different release processes, this makes everything much much simpler.

My current problem is I am not sure what is the best way to work React into this boilerplate.  It seems that no matter what I do that it will error on any JSX code despite whether or not I load `require("babel-core/register");` in any file.  Is there an easy way to add this to your gulp file or is there some other way I can get this working.

Ideally I would be able to do `import { HelloWorldComponent } from './hello_world/hello_world.js'` where hello_world is a React component.  Any thoughts on how to make this happen?

**Comment by szwacz** [comment]
Hey, I didn't have chance to play with React yet, so can't give you solution. But this project uses rollup for bundling and probably in rollup configuration/usage is your problem. Have you read this? https://github.com/rollup/rollup/issues/153

**Comment by gbmhunter** [comment]
The app I am developing, [NinjaCalc] (https://github.com/mbedded-ninja/NinjaCalc), uses this boilerplate along with React. I modified the gulp task to hunt down React .jsx files and compile them into standard .js files.

See [build.js](https://github.com/mbedded-ninja/NinjaCalc/blob/master/tasks/build.js) for more insight into how this is done.

**Comment by samhagman** [comment]
@gbmhunter Thank you for this I will definitely check out how that is working.  Also, cool app you are working on.  Also thanks again @szwacz for the awesome boilerplate.

**Comment by cristipufu** [comment]
If anyone else needs an example: https://github.com/cristipufu/electron-react-router-fluxxor-boilerplate/commit/eb4f4c750044d4038f289813e7f303165b9fab0f

**Comment by warka0** [comment]
@cristipufu Your link is dead :'(
