### ISSUE TITLE
Another alternative to setting npm_config_arch=ia32 on 64-bit Windows

### ISSUE THREAD

**Issue by waynebloss** [szwacz/electron-boilerplate#76]
Another alternative to setting the environment variable `npm_config_arch` to `ia32` on 64-bit Windows is to have 32-bit Node.js (and npm) installed.

This is what I do since it's easy to switch between versions of Node.js and different architectures using [nvm-windows](https://github.com/coreybutler/nvm-windows).

(*Related but off-topic note: If you use nvm-windows, I recommend running `npm cache clear` before switching to a different version/arch of Node.js*)

**Comment by szwacz** [comment]
Hmm, interesting. Must test this out...

**Comment by szwacz** [comment]
Yep. It's that easy. I've replaced old info in readme with your solution. Thanks!
