### ISSUE TITLE
Slow rendering

### ISSUE THREAD

**Issue by sergiuwd** [szwacz/electron-boilerplate#80]
I have created an electron boilerplate app and I'm loading the CSS inside the page itself using
<pre>link rel="stylesheet" type="text/css" href="assets/css/style.css"</pre>
But it takes 1-2 seconds for the CSS to load. Can I preload the CSS somehow? Or create a preloader, I don't know... but the white flash looks really bad.

**Comment by szwacz** [comment]
What is the size of your CSS file? Are you sure CSS file is the culprit? (have you tried to comment this line and see if this 1-2 second delay is still there?)

**Comment by sergiuwd** [comment]
Hi, Jakub! You're right, it's not a CSS issue. But what can I do to speed up the process so it won't display that white flash?

**Comment by szwacz** [comment]
First you need to find the root cause why it's so slow. Probably a lot of JavaScript is initating at once or you do some computationaly heavy task. I'm afraid you're on your own with finding the problem :)
