### ISSUE TITLE
fs-jetpack missing when installed

### ISSUE THREAD

**Issue by lllama** [szwacz/electron-boilerplate#81]
On Windows, things run fine when I'm running via "npm start" but when I "npm run release", and then install, I get a "cannot find module fs-jetpack" error on launch.

Any tips for how to debug this?

**Comment by szwacz** [comment]
It might be some quirk with the fact that there are two package.json files in this project.

Please check if fs-jetpack has been installed in folder electron-boilerplate/app/node_modules.
If not you might want to try:
```
cd app
npm install
```

**Comment by lllama** [comment]
OK - just tried with a checkout of the latest head and release installs and runs fine. I also forgot that I'm actually using the Vue based version from https://github.com/bradstewart/electron-boilerplate-vue and that doesn't appear to be working, so I'll file this there. Feel free to close.
