### ISSUE TITLE
windows : Invalid command: Unicode

### ISSUE THREAD

**Issue by coclav** [szwacz/electron-boilerplate#82]
HI, just got a "fresh" boilerplate because i broke everything. couldn't make a windows release :

```Invalid command: Unicode
Error in script "C:\Users\coclav\electron-boilerplate2\tmp\installer.nsi" on line 31 -- aborting creation process```

I'm using windows 10 in Parallels on mac. When i comment out the line this works. THough i have a problem with the icons but i'll make another issue.

Colin

**Comment by youmnaHigagy** [comment]
I ran into this issue yesterday too, and removed the line of code you commented and yes it worked.
However, today I installed  NSIS 3.0b2 instead of NSIS 2.46 that was installed on my machine and it worked just fine without commenting or removing anything.

**Comment by szwacz** [comment]
I'm assuming this was NSIS version mismatch and closing.
