### ISSUE TITLE
Better assets management - usemin, bower, uglify, whatever

### ISSUE THREAD

**Issue by fourpixels** [szwacz/electron-boilerplate#83]
Hi there,
Thanks for the nice job on the boilerplate. I just started using it and I'm still configuring my base project (installing Angular and stuff). I just found that the scripts used for building your app, are actually using rollup for converting ES6 to ES5 and building it to a single file, as well as compiling a less file into css.

But I think there could be a few options in how you package your assets, and things like bower, [gulp-usemin](https://www.npmjs.com/package/gulp-usemin), uglify and even [gulp-rev](https://www.npmjs.com/package/gulp-rev) could be pretty nice asset!

Right now I'm going to hack into the build process and hopefully I'm gonna make it work, but I'm pretty sure it could be done in a sleeker way.

Cheers

**Comment by szwacz** [comment]
Hi, I don't fully understand what you want to add to build process but here are two small thoughts:

1. Rollup just does modules bundling, it doesn't add any extra ES6 features. Just to make things clear :)

2. Electron application files are loaded form local dist, what means instantly, what means things like minification are not needed (unless you want to protect your sourcecode from stealing).

**Comment by fourpixels** [comment]
Hi again,
Sorry for not being clear enough :)

My point was to introduce a way that the build procedure can be easily modified, like by passing some arguments. I know they are loaded instantly, but I still find some of the things rather helpful. I love using Bower and I think it's great in larger projects, but it's components should not reside in the app folder (in my opinion) because they have tons of stuff in them. It would be very convenient if I can easily get only the things I need and not all of the junk.

Minimizing/uglifying is good not only for protection, but sometimes even for optimization and faster performance.

Anyways, my main point is to at least provide a noop method that can be easily modified by others if they want to integrate some additional stuff, something like middleware. Because right now I must hack into build function and mess all the things around :)

**Comment by szwacz** [comment]
The point of gulp is that you mess with build functions :) I really don't see how I can make it simpler. Have you seen something like this in other projects?
