### ISSUE TITLE
Can't run release and no errors displayed

### ISSUE THREAD

**Issue by tlacaelelrl** [szwacz/electron-boilerplate#86]
I built my app and was able to test using npm start the application copies to the build directory and all runs fine.

Then on npm run release nothing happens other than start clean

    C:\Users\Users\TD\boilerplate>npm run release

    > @ release C:\Users\TD\boilerplate
    > gulp release --env=production

    [15:31:24] Using gulpfile ~\boilerplate\gulpfile.js
    [15:31:24] Starting 'clean'...

And nothing is rendered into the releases folder.
Then if I try again npm start I get "Error opening app. Not a valid electron app"
But note that it was previously running fine.

    C:\Users\TD\boilerplate>npm start

    > @ start C:\Users\TD\boilerplate
    > node ./tasks/start

    [15:50:14] Using gulpfile ~\boilerplate\gulpfile.js
    [15:50:14] Starting 'clean'...

    [15:50:15] Using gulpfile ~\boilerplate\gulpfile.js
    [15:50:15] Starting 'watch'...
    [15:50:17] Finished 'watch' after 2.46 s

Am I missing something here.

Is there anything inside the app folder that I am not supposed to touch?

**Comment by szwacz** [comment]
Have you introduced any changes to the code, or running those commands on fresh `git clone`? If on your app then please try fresh clone and see how that works.

If clean task never finishes it could be also something with write permissions to folders. Don't you have file explorer opened inside `tmp` folder or something?

**Comment by tlacaelelrl** [comment]
It is not a fresh clone, I am adding my app.

Here is what I am doing:

Clone->install->start "Works fine" ->release "Works fine"
However this is not the app I need so then
Remove files from the app folder
Add my own files for the app
do start -> "works"
->release I get nothing, no errors or anything that can lead me to a solution
Also after running release I have to start over from cloning as now "npm start" does not work either giving the "Not a valid electron app" error.

**Comment by tlacaelelrl** [comment]
Ok, so I did further testing and it seems that the issue is that I deleted needed files but I am unsure which ones they are.

I now just replaced the code in the app.js and app.html and the build worked however I would like to remove whatever is not needed from the app folder, do you have a list of the files that are absolutely needed?

Also after the installer is created I now ran into another issue.

The app has some binaries included which are required for it to fully function. Those binaries are inside the  asar file and I can execute them. What would be required for those not to be packed into the asar file?

**Comment by tlacaelelrl** [comment]
I figured a way to include my binaries.

I added a folder into the root of both electron-boilerplate and node_modules\electron-prebuilt\dist

All working now I would still like to know what can be removed from the default boiler template

**Comment by szwacz** [comment]
There is very few files in app directory of this project, so I don't know what you want to achieve :) I'm sure you can pretty quick figure out what every single file does and if you need it or not.
