### ISSUE TITLE
Unable to change icon for browser or tray

### ISSUE THREAD

**Issue by gte773h** [szwacz/electron-boilerplate#88]
Hi,

Thanks for putting this boilerplate together! I am trying to move my application into it and I'm having problems with changing the application icon and tray icon when doing an "npm start" in development. (I haven't tried to get this working for release yet).

I have tried multiple variations to change the icon. I have also made sure the build.js copies the image files to the build directory. 

Here are a few variations I have tried, each one I have verified that the file is available in the build directory.

mainWindow = new BrowserWindow({width: width, height: height, icon: "file://" + __dirname + "/favicon-96x96.png", title: "test application"});

mainWindow = new BrowserWindow({width: width, height: height, icon: "./favicon-96x96.png", title: "test application"});

mainWindow = new BrowserWindow({width: width, height: height, icon: "./vendors/images/favicon-96x96.png", title: "test application"});

I'm guessing the Tray problem is just an extension of the fact that I don't know how to reference images properly. The Tray is more severe though because it crashes the app when it can't find the image file.

Any help would be very much appreciated! Thanks!

**Comment by gte773h** [comment]
I tried one more variation and this seems to be working --- not sure if it is cross platform supported:

mainWindow = new BrowserWindow({width: width, height: height, icon: __dirname + "/favicon-96x96.png", title: "test application"});

**Comment by szwacz** [comment]
Yes, the way you do this is cross platform.
