### ISSUE TITLE
Replacement setup-banner.bmp Doesn't Work

### ISSUE THREAD

**Issue by gbmhunter** [szwacz/electron-boilerplate#89]
I replaced the `resources/windows/setup-banner.bmp` with what I believe to be a compatible file (still 32-bit bitmap, same pixel size, same file name, e.t.c), but now the NSIS installer no longer displays a banner image.

![image](https://cloud.githubusercontent.com/assets/2396869/11622203/7f8f2d3a-9d28-11e5-8d16-debe0ddcc471.png)

If I replace it with the default image, it works again! What could be different between the two files?

![image](https://cloud.githubusercontent.com/assets/2396869/11623613/fb199c60-9d32-11e5-9e24-e36e281f71b0.png)

**Comment by szwacz** [comment]
Hmm, I'm not master at BMP format. If I remember correctly what I did to have this bmp was saving it with MS Paint. You might try that expencive and sophisticated software ;)

**Comment by gbmhunter** [comment]
Thanks I will give that a go. I had saved it as a .bmp through GIMP.
