### ISSUE TITLE
npm peer dependencies

### ISSUE THREAD

**Issue by carlosperate** [szwacz/electron-boilerplate#9]
On a fresh install of the electron-boilerplate using npm 2.10.1, apart from the expected warnings I get the following:
```
npm WARN peerDependencies The peer dependency stream-browserify@* included from bl will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```
Might be worth adding explicit dependencies sooner rather than later?

**Comment by szwacz** [comment]
This is in `vinyl-map` of which I'm using here the latest version. Submited PR to `vinyl-map` repo.

**Comment by szwacz** [comment]
After switch to Babel `vinyl-map` isn't used anymore, so the problem self-resolved.
