### ISSUE TITLE
Have to add a line to build.js for each js file

### ISSUE THREAD

**Issue by black-snow** [szwacz/electron-boilerplate#92]
Hi there,

I found out the hard way (took me hours) to figure out I had to add a line to `build.js` for each js file I have in my `app` folder. Why is that?

build.js:73+

```javascript
var bundleApplication = function () {
    return Q.all([
        bundle(srcDir.path('background.js'), destDir.path('background.js')),
        bundle(srcDir.path('app.js'), destDir.path('app.js')),
        bundle(srcDir.path('about.js'), destDir.path('about.js')), // need to add this line for each of my 'custom' files
    ]);
};
```

How come I'm the first (or at least seem to be) to struggle with this? Am I doing something wrong?

**Comment by szwacz** [comment]
Hi!

Those `bundle()` calls are [rollup](https://github.com/rollup/rollup) entries, rollup is let's say next generation [browserify](http://browserify.org/). Make sure you're familiar with concept in one of those.

If you don't want to use bundling in your app, then simpler will be to drop bundle completetly and just add one line to this piece od code in `build.js` file:
```js
var paths = {
    copyFromAppDir: [
        './node_modules/**',
        './vendor/**',
        './**/*.html',
        './**/*.+(jpg|png|svg)',
        './**/*.js', // <-- this line added
    ],
}
```

**Comment by black-snow** [comment]
Thanks for the reply. I'm not sure I got what rollup does. It bundles my scripts into a single module?
Does this mean that I'll have to add lines like

     bundle(srcDir.path('myOtherScript.js'), destDir.path('app.js')),

for each of my files and they will all end up in `app.js`? Still I would have to add a line for each file.

**Comment by szwacz** [comment]
You just need to pass so called 'entry point' to `bundle()` function. Then rollup will read this file, follow all `import something from './my-dir/my-file'` declarations and combine all those files into one big file. I really don't know how to explain it in few sentences :) There are probably ton of good articles about it on the internet. Google Browserify first. Rollup is much newer and not so much resources on it yet.
