### ISSUE TITLE
Why ignore /app/spec.js?

### ISSUE THREAD

**Issue by waynebloss** [szwacz/electron-boilerplate#93]
Just wondering why you are ignoring `/app/spec.js` in the `.gitignore` file?

**Comment by szwacz** [comment]
Because this file isn't human-authored, but generated automatically. Here is the code generating it: https://github.com/szwacz/electron-boilerplate/blob/master/tasks/generate_specs_import.js

**Comment by waynebloss** [comment]
Thanks!
